### ISSUE TITLE
Add unit tests for UniswapV1

### ISSUE THREAD

**Issue by DanilYachmenev** [sorrentum/sorrentum#111]
Follow-up from https://github.com/sorrentum/sorrentum/issues/82#issuecomment-1494683821

Add unit tests for all public methods of `UniswapV1` class
For code ref see other test files (like `defi/dao_cross/test/test_dao_cross.py` or `defi/dao_cross/test/test_optimize.py`
Although, tests here should be really simple: set params, call, check

Assigning @tamriq to re-assign

**Comment by leggomyegg0** [comment]
Where is the cmamp container? I am struggling to find it in the files.

**Comment by gpsaggese** [comment]
@PomazkinG is releasing / putting together some doc. See the TG chat

**Comment by leggomyegg0** [comment]
While setting up the cmamp container, when running the command `i git_merge_master`, I get an error that says "The Git client is not clean." I was trying to troubleshoot it but could not find much on this error. Any ideas @PomazkinG?
![issue1](https://user-images.githubusercontent.com/119753704/232255533-55460dc2-d02e-4a12-a2f5-898ec5d54fe4.png)

**Comment by gpsaggese** [comment]
Git can't merge master in a branch that has changes. So you need to commit or reset the client, before `i git_merge_master`

We use Git extensively, so if you have doubts about Git you can check the slides

https://github.com/gpsaggese/umd_data605/blob/main/lectures/02.1%20-%20Git%2C%20Data%20Pipelines.pdf

and read the Git book https://git-scm.com/book/en/v2

**Comment by leggomyegg0** [comment]
Thank you I was able to get past that error and I will definitely read through the Git book. 

I have encountered an issue with the next command `i docker_bash` and I haven't been able to troubleshoot this one either. It gives an error that says "ValueError: Don't recognize host: host_os_name=Linux, am_host_os_name=None". Any tips on this? Is more information needed?
![dock error](https://user-images.githubusercontent.com/119753704/232338529-f3220b6f-71d6-429c-a13d-e7f9fa11b179.png)

**Comment by PomazkinG** [comment]
> Thank you I was able to get past that error and I will definitely read through the Git book.
> 
> I have encountered an issue with the next command `i docker_bash` and I haven't been able to troubleshoot this one either. It gives an error that says "ValueError: Don't recognize host: host_os_name=Linux, am_host_os_name=None". Any tips on this? Is more information needed? ![dock error](https://user-images.githubusercontent.com/119753704/232338529-f3220b6f-71d6-429c-a13d-e7f9fa11b179.png)

@leggomyegg0 could you please post the full trace? so that it's clear where in the code to look for the error, e.g.,
```
# Cmd to run.
> i docker_bash
# The error. The thing below is just an example, feel free to replace with the actual error you are hitting.
Traceback (most recent call last):
  File "/app/dataflow_orange/system/Cx/run_Cx_prod_system.py", line 145, in <module>
    _main(_parse())
  File "/app/dataflow_orange/system/Cx/run_Cx_prod_system.py", line 141, in _main
    hasynci.run(_run_real_time_pipeline(args), event_loop)
  File "/app/amp/helpers/hasyncio.py", line 142, in run
    ret = event_loop.run_until_complete(coroutine)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/app/dataflow_orange/system/Cx/run_Cx_prod_system.py", line 33, in _run_real_time_pipeline
    await dag_runner.predict()
  File "/app/amp/dataflow/system/real_time_dag_runner.py", line 154, in predict
    async for result_bundle in self.predict_at_datetime():
  File "/app/amp/dataflow/system/real_time_dag_runner.py", line 169, in predict_at_datetime
    async for event, result_bundle in creatime.execute_with_real_time_loop(
  File "/app/amp/core/real_time.py", line 419, in execute_with_real_time_loop
    result = await asyncio.gather(  # type: ignore[var-annotated]
  File "/app/amp/dataflow/system/real_time_dag_runner.py", line 246, in _run_dag
    await node.process_forecasts()
  File "/app/amp/dataflow/system/sink_nodes.py", line 67, in process_forecasts
    await oprofore.process_forecasts(
  File "/app/amp/oms/process_forecasts_.py", line 246, in process_forecasts
    hdbg.dassert_lte(timestamp, current_bar_timestamp)
  File "/app/amp/helpers/hdbg.py", line 248, in dassert_lte
    _dfatal(txt, msg, *args, only_warning=only_warning)
  File "/app/amp/helpers/hdbg.py", line 142, in _dfatal
    dfatal(dfatal_txt)
  File "/app/amp/helpers/hdbg.py", line 71, in dfatal
    raise assertion_type(ret)
AssertionError: 
################################################################################
* Failed assertion *
2023-03-13 09:20:00-04:00 <= 2023-03-13 09:15:00-04:00
################################################################################
```

**Comment by leggomyegg0** [comment]
Yes. Here is the full trace:
`(amp.client_venv) nfarb@Ubuntu:~/Documents/sorrentum$ i docker_bash`
`One and only one set-up config should be true:`
`is_cmamp_prod=False`
`is_dev4=False`
`is_dev_ck=False`
`is_ig_prod=False`
`is_inside_ci=False`
`is_mac=False`
`INFO: > cmd='/home/nfarb/src/venv/amp.client_venv/bin/invoke docker_bash'`
`report_memory_usage=False report_cpu_usage=False`
`\## docker_bash:`
`Traceback (most recent call last):`
`  File "/home/nfarb/src/venv/amp.client_venv/bin/invoke", line 8, in <module>`
 `   sys.exit(program.run())`
`  File "/home/nfarb/src/venv/amp.client_venv/lib/python3.10/site-packages/invoke/program.py", line 380, in run`
`self.execute()`
`  File "/home/nfarb/src/venv/amp.client_venv/lib/python3.10/site-packages/invoke/program.py", line 565, in execute`
`    executor.execute(*self.tasks)`
`  File "/home/nfarb/src/venv/amp.client_venv/lib/python3.10/site-packages/invoke/executor.py", line 127, in execute`
`    result = call.task(*args, **call.kwargs)`
`  File "/home/nfarb/src/venv/amp.client_venv/lib/python3.10/site-packages/invoke/tasks.py", line 115, in __call__`
`    result = self.body(*args, **kwargs)`
`  File "/home/nfarb/Documents/sorrentum/helpers/lib_tasks_docker.py", line 1280, in docker_bash`
`    docker_cmd_ = _get_docker_compose_cmd(`
`  File "/home/nfarb/Documents/sorrentum/helpers/lib_tasks_docker.py", line 1124, in _get_docker_compose_cmd`
`    docker_cmd_ = _get_docker_base_cmd(`
`  File "/home/nfarb/Documents/sorrentum/helpers/lib_tasks_docker.py", line 1053, in _get_docker_base_cmd`
`    docker_compose_files = _get_docker_compose_files(`
`  File "/home/nfarb/Documents/sorrentum/helpers/lib_tasks_docker.py", line 698, in _get_docker_compose_files`
`    enable_privileged_mode = henv.execute_repo_config_code(`
`  File "/home/nfarb/Documents/sorrentum/helpers/henv.py", line 498, in execute_repo_config_code`
`    ret = eval(code_to_execute)`
`  File "<string>", line 1, in <module>`
`  File "<string>", line 117, in enable_privileged_mode`
`  File "<string>", line 87, in _raise_invalid_host`
`ValueError: Don't recognize host: host_os_name=Linux, am_host_os_name=None`

**Comment by PomazkinG** [comment]
@leggomyegg0 

the problem is clear, will fix tmrw

**Comment by PomazkinG** [comment]
@leggomyegg0 can you try now? (after pulling the master and merging it into a branch)

fixed in a hacky way to unblock, but filed a separate bug to fix properly https://github.com/sorrentum/sorrentum/issues/142

**Comment by leggomyegg0** [comment]
@PomazkinG  Yeah it works now thank you

**Comment by leggomyegg0** [comment]
I just want to make sure I do everything correctly before I make any PR's related to this issue:
Would I use `i git_branch_create` to make the branch to write the tests in?
Then I would start the container with `i docker_bash` where I would subsequently write the tests?

**Comment by PomazkinG** [comment]
> I just want to make sure I do everything correctly before I make any PR's related to this issue: Would I use `i git_branch_create` to make the branch to write the tests in? Then I would start the container with `i docker_bash` where I would subsequently write the tests?

@tamriq @DanilYachmenev guys, you are the experts here, could you please help the students to get up to speed? I mean: how to edit the code, how to run the regressions, how to work with `git`. Feel free to update https://docs.google.com/document/d/1QqNyFWUmkHjb22I5Od2BMUrapcSOhb3QZWWdm35vIu0/edit#heading=h.q4rs4nlh3ltn with the instructions so that everyone can use the same guide

**Comment by DanilYachmenev** [comment]
Sure, thx for pinging

Hmm in terms of docs
I moved Git workflow info form this [Gdoc](https://docs.google.com/document/d/1zahC8uDnFGYRSgkBrQRgg3W3ZmDjZZJj6yln6YeuHq4/edit#) to the one [you've suggested](https://docs.google.com/document/d/1QqNyFWUmkHjb22I5Od2BMUrapcSOhb3QZWWdm35vIu0/edit#heading=h.q4rs4nlh3ltn).

However, the formatting is very raw so it might not be completely clear for now.

So due to that adding a small git toolkit about starting the work with branches
1. Before you start, checkout to `master` and pull its latest version:
    - `> git checkout master`
       `> git pull`
    - if some changed files block checkout to master, do
    `> git stash`
    and repeat the checkout
2. To create a new branch do:
    - `> git checkout -b BranchName`
    - See conventions for branch name at the [Gdoc](https://docs.google.com/document/d/1QqNyFWUmkHjb22I5Od2BMUrapcSOhb3QZWWdm35vIu0/edit#heading=h.q4rs4nlh3ltn ), "Workflow" stage
3. Add files that you've changed to the commit
    - `> git add full_path_to_file`
    - `> git add -u` - add all the files with changes to the commit
4. Make commit and push it, make PR
    - `>git commit -m "message"`
    - `> git push`

@leggomyegg0 lemme know what remains unclear in the working process so you could proceed

**Comment by gpsaggese** [comment]
PR is https://github.com/sorrentum/sorrentum/pull/167

**Comment by DanilYachmenev** [comment]
Done in #167
