### ISSUE TITLE
Build smart contract getting token prices with chainlink oracle

### ISSUE THREAD

**Issue by gpsaggese** [sorrentum/sorrentum#12]
Write simple smart contract that gets the token prices from binance using https://docs.chain.link/data-feeds/price-feeds/addresses

**Comment by gpsaggese** [comment]
@KangmingL you can start with this issue. Since it should be pretty simple and a way to exercise the toolchain

**Comment by gpsaggese** [comment]
@samarth9008 you can also use this as a warm up task

**Comment by leggomyegg0** [comment]
I have a few questions as I look at this problem and keep reading more of the materials:

Where would I write the smart contract? Would I leave it in this comment or insert into a specific sorrentum file?

We want the price for the Binance (BUSD) token right?

What would I do with the price? Print it out or just get it?

The contracts are written in Solidity right?

I just wanted to clear a few things up as I keep learning more about the toolchain and principles surrounding this project.

**Comment by gpsaggese** [comment]
> I have a few questions as I look at this problem and keep reading more of the materials:
> 
> Where would I write the smart contract? Would I leave it in this comment or insert into a specific sorrentum file?

In a file. @tamriq can suggest where.

> 
> We want the price for the Binance (BUSD) token right?

Any token is fine. The contract should be able to read any price from Chainlink.

> 
> What would I do with the price? Print it out or just get it?

Print or get it is fine.

> 
> The contracts are written in Solidity right?
>

Correct. 
> I just wanted to clear a few things up as I keep learning more about the toolchain and principles surrounding this project.

**Comment by gpsaggese** [comment]
- @tamriq already implemented this, but worth doing it / playing with it to understand
- @tamriq integrate and then develop here
- @leggomyegg0 try to switch to our Docker container. We can help with set-up

**Comment by leggomyegg0** [comment]
I need a little help setting up the docker container. Do I follow the instructions in the sandbox readme or is it something else?

**Comment by gpsaggese** [comment]
@samarth9008 can you pls help?

The goal is to have a gdoc or a markdown that we can point people to and they can follow.
Then we say "to onboard Web3 project follow this". Same thing we do with DATA605.
