### ISSUE TITLE
Unknown host when running from a local machine

### ISSUE THREAD

**Issue by PomazkinG** [sorrentum/sorrentum#142]
Yes. Here is the full trace:
`(amp.client_venv) nfarb@Ubuntu:~/Documents/sorrentum$ i docker_bash`
`One and only one set-up config should be true:`
`is_cmamp_prod=False`
`is_dev4=False`
`is_dev_ck=False`
`is_ig_prod=False`
`is_inside_ci=False`
`is_mac=False`
`INFO: > cmd='/home/nfarb/src/venv/amp.client_venv/bin/invoke docker_bash'`
`report_memory_usage=False report_cpu_usage=False`
`\## docker_bash:`
`Traceback (most recent call last):`
`  File "/home/nfarb/src/venv/amp.client_venv/bin/invoke", line 8, in <module>`
 `   sys.exit(program.run())`
`  File "/home/nfarb/src/venv/amp.client_venv/lib/python3.10/site-packages/invoke/program.py", line 380, in run`
`self.execute()`
`  File "/home/nfarb/src/venv/amp.client_venv/lib/python3.10/site-packages/invoke/program.py", line 565, in execute`
`    executor.execute(*self.tasks)`
`  File "/home/nfarb/src/venv/amp.client_venv/lib/python3.10/site-packages/invoke/executor.py", line 127, in execute`
`    result = call.task(*args, **call.kwargs)`
`  File "/home/nfarb/src/venv/amp.client_venv/lib/python3.10/site-packages/invoke/tasks.py", line 115, in __call__`
`    result = self.body(*args, **kwargs)`
`  File "/home/nfarb/Documents/sorrentum/helpers/lib_tasks_docker.py", line 1280, in docker_bash`
`    docker_cmd_ = _get_docker_compose_cmd(`
`  File "/home/nfarb/Documents/sorrentum/helpers/lib_tasks_docker.py", line 1124, in _get_docker_compose_cmd`
`    docker_cmd_ = _get_docker_base_cmd(`
`  File "/home/nfarb/Documents/sorrentum/helpers/lib_tasks_docker.py", line 1053, in _get_docker_base_cmd`
`    docker_compose_files = _get_docker_compose_files(`
`  File "/home/nfarb/Documents/sorrentum/helpers/lib_tasks_docker.py", line 698, in _get_docker_compose_files`
`    enable_privileged_mode = henv.execute_repo_config_code(`
`  File "/home/nfarb/Documents/sorrentum/helpers/henv.py", line 498, in execute_repo_config_code`
`    ret = eval(code_to_execute)`
`  File "<string>", line 1, in <module>`
`  File "<string>", line 117, in enable_privileged_mode`
`  File "<string>", line 87, in _raise_invalid_host`
`ValueError: Don't recognize host: host_os_name=Linux, am_host_os_name=None`

_Originally posted by @leggomyegg0 in https://github.com/sorrentum/sorrentum/issues/111#issuecomment-1512148475_

**Comment by PomazkinG** [comment]
We did not hit the problem before because we all work either from a dev server or from a mac pc

Fixed in a hacky way in https://github.com/sorrentum/sorrentum/pull/144 to unblock the students but we need to think how to adjust the system properly, e.g.,
```
# Instead of calling `_raise_invalid_host()`.
else:
   return False
```

**Comment by PomazkinG** [comment]
@gpsaggese FYI

**Comment by gpsaggese** [comment]
Agree that a warning is good enough here, instead of asserting

**Comment by DanilYachmenev** [comment]
Done
