### ISSUE TITLE
Create a Python script to convert a Parquet file to CSV

### ISSUE THREAD

**Issue by PomazkinG** [sorrentum/sorrentum#160]
From @gpsaggese 

> To bridge the gap of observability between Parquet and humans, it might be useful to have a simple script parquet_to_csv.py that converts a Parquet file in a CSV file or stdin for quick inspection and piping to https://csvkit.readthedocs.io/en/latest/
Can you pls file a bug on the Sorrentum side and put a label "good-first-bug" so we outsource it to students

FYI: there are some scripts that we can re-use (?), e.g.,:
- https://github.com/sorrentum/sorrentum/blob/master/im_v2/common/data/transform/convert_csv_to_pq.py
- https://github.com/sorrentum/sorrentum/blob/master/im_v2/common/data/transform/pq_convert.py

Add more specs here

**Comment by PomazkinG** [comment]
> Both links seem to be pointing to private or non existing repos. Are there any other sources you could provide?

Updated the original post, should be public now

**Comment by dchoi127** [comment]
[PR](https://github.com/sorrentum/sorrentum/pull/267)

**Comment by gpsaggese** [comment]
I've just noticed this. @dchoi127 you've assigned the review to yourself so we didn't get notified.

Routing to @DanilYachmenev for taking the first look (@PomazkinG feel free to also review)

**Comment by DanilYachmenev** [comment]
So guys lets talk about specs a bit

1. Following, https://github.com/sorrentum/sorrentum/pull/267#discussion_r1201092684, did I get it right that we want to build a script that converts 1 Parquet file to 1 CSV file?
2. If yes, then I have a question about `aws_profile`

Basically we have 2 files (input and output) and 1 `aws_profile` now

If we want to implement conversion just locally or only inside AWS, then everything is easy
But practically we may want to convert a `.pq` file that is stored locally to a location at AWS or between different AWS profiles

Should we care about that?
If yes, we can pass 2 AWS profiles: `src_aws_profile` and `dst_aws_profile`
Both can be optional (default is `None` which would mean that file is stored locally)
IMO it is going to look OK as well and not complicating interface too much

@PomazkinG, @gpsaggese wdyt?

**Comment by PomazkinG** [comment]
my 2 cents: I would start with implementing a basic functionality and extend it depending on use cases.

E.g., we start with 1 AWS profile but when we face an issue where we need to use the 2nd AWS profile we file a separate issue and extend the functionality.

**Comment by gpsaggese** [comment]
Agreed with @PomazkinG. Let's keep the specs simple and use Linux to compose behaviors.

@DanilYachmenev 
1) we want to support only one AWS profile when the original source file is on S3
    - If you want to convert multiple files on multiple buckets then you run the script multiple times (the interface is done at Unix level and not at the script level)

2) In general we prefer to read from S3, but write locally. If you want to save to S3 then you do an rsync

At hindsight, maybe the right amount of specs here was to copy-paste the other example and implement `parse`
