### ISSUE TITLE
Missing positional argument error in order_matching.py::match_orders

### ISSUE THREAD

**Issue by KangmingL** [sorrentum/sorrentum#161]
Missing a positional argument 'clearing_price' when order.base_token == quote_token and  get_equivalent_order() is invoked in line 80. @tamriq @DanilYachmenev 

https://github.com/sorrentum/sorrentum/blob/e9e9ec7007669735f02b7fb6d84c43ddb3f08c75/defi/dao_cross/order_matching.py#L80

**Comment by DanilYachmenev** [comment]
Fixed, thx!
