### ISSUE TITLE
Test OrderMinHeap library

### ISSUE THREAD

**Issue by tamriq** [sorrentum/sorrentum#165]
The goal is to create brownie tests that explore OrderMinHeap library directly, separately from DaoCross. 
Let's go through each function and try to find some corner cases.

**Comment by samarth9008** [comment]
@KangmingL Whats the progress on this issue?

**Comment by KangmingL** [comment]
> @KangmingL Whats the progress on this issue?

Hi Samarth, I'm still working on this issue.

**Comment by samarth9008** [comment]
Alright, if you find this difficult and parellely wants to work on another issue, we re-route it to someone else. Later on when you feel confident, you can work on the similar issues. LMK.
