### ISSUE TITLE
Create a mailing list for Sorrentum

### ISSUE THREAD

**Issue by gpsaggese** [sorrentum/sorrentum#170]
We have a `updates@sorrentum.org` account that we can use. I think there is a way to create a list where
- one sends an email to it and it gets propagated to everyone on the list
- anyone can subscribe (e.g., we send a link and people can opt-in)
- anyone can unsubscribe (e.g., you click the link "unsubscribe" and you are done)

I'm sure Google supports all this natively.

Probably there are even better solutions to track who reads the email, how many people open it, etc. (e.g., https://mailchimp.com)

**Comment by gpsaggese** [comment]
In order of priority @27sanjeevd, @samarth9008, @jsmerix anyone knows how to do it, wants to figure it out? It's a quick thing

**Comment by 27sanjeevd** [comment]
I'm going to be out of town for a few days, but once I get back I can take a look at this

**Comment by samarth9008** [comment]
I will take a look once I am done with brownie test scripts. I will be done with it today and generate a PR.

**Comment by gpsaggese** [comment]
Yes @samarth9008 pls. I'll assign it to you since you are free.
We will file more bugs so people can pick them up when they are free.

**Comment by samarth9008** [comment]
Is the end goal like we will send email to `updates@sorrentum.org` and it will be recieved by everyone?

**Comment by gpsaggese** [comment]
Correct. Right now, I send emails with 50-60 people in bcc, but we have reached the limit for Gmail. Also people don't have a way to unsubscribe, if they are not interested anymore. Furthermore we don't have a way to track who opens the email and so on. 

So we are looking for a simple solution to achieve all these things. 

You can create a free account on https://mailchimp.com/ and play with it and then we can buy a license for this.

**Comment by samarth9008** [comment]
With the help of google, we can create google groups using groups.google.com. Add members to the group and then we can broadcast the messages to all the members. They also have option to unsubscribe the group.

However, I am not sure how mailchimp is helpful and how to use that? Never used it before.

**Comment by samarth9008** [comment]
Sent a testing email 

> Next steps are:
> 
> * [x]  @gpsaggese create an account on Mailchimp
> * @samarth9008
> * [x]  create a small test mailing list with [gp@sorrentum.org](mailto:gp@sorrentum.org), [info@sorrentum.org](mailto:info@sorrentum.org), [saggese@gmail.com](mailto:saggese@gmail.com), and Samarth
   Sent a testing email to all the above contacts.

**Comment by samarth9008** [comment]
Reports on if email was opened or not.

![image](https://user-images.githubusercontent.com/58821247/234963063-a0ebc69e-65d0-44fa-a49b-f5a4acbf3cc6.png)

![image](https://user-images.githubusercontent.com/58821247/234963129-c3db50a3-1e86-4fa0-aa6a-440f55ebd841.png)

**Comment by samarth9008** [comment]
How does this looks for a welcome message?

Greetings to all potential contributors of Sorrentum!

We are thrilled to welcome you to our community of developers, enthusiasts, and visionaries who are dedicated to building Open-source DeFi protocol for advanced financial applications. We believe that decentralization is the future of the financial markets, and we are excited to embark on this journey with you.

As a contributor to Sorrentum, you will have the opportunity to collaborate with a diverse group of talented individuals, learn cutting-edge technologies, and make a meaningful impact in the world of Decentralised Finance. Whether you are an experienced developer or just starting your journey, we welcome your contribution and look forward to working with you.

Thank you for joining our mission to revolutionize the industry through decentralization. Let's build the future together!

**Comment by samarth9008** [comment]
@gpsaggese any update on this?
