### ISSUE TITLE
Sorrentum Calendar to subscribe for meetings

### ISSUE THREAD

**Issue by okritvik** [sorrentum/sorrentum#180]
- [ ] Calendar sorrentum.org
- [ ] Post it on the website

**Comment by gpsaggese** [comment]
I will create a info@sorrentum.org account and you and @samarth9008 can use that account to manage mailing lists and calendar

**Comment by okritvik** [comment]
Sounds good!

**Comment by gpsaggese** [comment]
Can you post the link to the calendar and then we put it in the README?

**Comment by okritvik** [comment]
Here is the branch link https://github.com/sorrentum/sorrentum/tree/SorrTask180_sorrentum_calendar
