### ISSUE TITLE
Compile info for funding Internships

### ISSUE THREAD

**Issue by okritvik** [sorrentum/sorrentum#187]
Create a spreadsheet with one line per internship and collect the information required.

**Comment by gpsaggese** [comment]
The questions to collect in the spreadsheet are:
- Who needs to apply: student or company?
- Does the company need to be a non-profit or for profit? So we know if Sorrentum or Kaizen should apply
- When is the deadline
- Website with info about the internship
- Email for internship contact
- Do you know what percentage of applications are actually assigned? Just to get a sense of how competitive it is.
- Do they know of other resources?
- Is it for Summer, Fall?
- How much do they pay an intern?

If infos are incomplete we should send an email (from your UMD account with [gsaggese@umd.edu](mailto:gsaggese@umd.edu) in cc) to the person in charge with the questions

**Comment by gpsaggese** [comment]
@okritvik to create spreadsheet in the proper dir

Other links to explore:
- [ ] https://careers.umd.edu/find-jobs-internships/internships/financing-your-internship
- [ ] https://scholarships.umd.edu/current-undergrads
- [ ] https://docs.google.com/document/d/1y-0Kgqs_BqfAE9MH-hj0GsH0RcaxJFtk8bfYsYpdBGc/edit#

**Comment by gpsaggese** [comment]
While put together the gsheet with all the info:
- Everyone interested should apply to https://www.rhsmith.umd.edu/centers-initiatives/dingman-center/initiatives-programs/kathryn-stewart-fellowship since we have applied as recipients.
- There's an article recently from the University https://careers.umd.edu/find-jobs-internships/internships/financing-your-internship about some other options though; students could use those funds for an internship
- We will apply to https://mtip.umbc.edu/mtip

**Comment by okritvik** [comment]
Looked at https://careers.umd.edu/find-jobs-internships/internships/financing-your-internship and included the one that is available for us in the Excel Sheet.
https://scholarships.umd.edu/current-undergrads is available for undergrads. They are organization-specific scholarships.
https://docs.google.com/document/d/1y-0Kgqs_BqfAE9MH-hj0GsH0RcaxJFtk8bfYsYpdBGc/edit# This document has more info about the internships available through https://scholarships.umd.edu/current-undergrads.

**Comment by gpsaggese** [comment]
The internship funding gsheet is under Growth at
https://docs.google.com/spreadsheets/d/19rs1T_puq6aR-VwPOtD5Oas2gZyuBOpnrqEu6eN4eNo/edit#gid=0

Added a tab with Links
