### ISSUE TITLE
Contributor technical on-boarding 

### ISSUE THREAD

**Issue by gpsaggese** [sorrentum/sorrentum#189]

**Comment by gpsaggese** [comment]
@Addy-mufc
[ ] Read [How to organize your work](docs/How_to_organize_your_work.md)
[ ] Read [Quick start for developing](docs/Quick_start_for_developing.md)
[ ] Make sure the Docker dev container works
[ ] Make sure the unit tests run successfully
[ ] Read [Sorrentum Python coding style guide](https://docs.google.com/document/d/1R6jhFDbZKvyDdbnSQ9DA_N8417YF13hMI_Uw4quO4Xk)
[ ] Get assigned a warm-up issue
[ ] Get up to speed in terms of the background knowledge for specific project
    - For Web3 / Crypto : [/defi/README.md](/defi/README.md)
    - For Arbitrage / Modeling: [/docs/From_zero_to_modeling.md](/docs/From_zero_to_modeling.md)

@canum05
[ ] Read [How to organize your work](docs/How_to_organize_your_work.md)
[ ] Read [Quick start for developing](docs/Quick_start_for_developing.md)
[ ] Make sure the Docker dev container works
[ ] Make sure the unit tests run successfully
[ ] Read [Sorrentum Python coding style guide](https://docs.google.com/document/d/1R6jhFDbZKvyDdbnSQ9DA_N8417YF13hMI_Uw4quO4Xk)
[ ] Get assigned a warm-up issue
[ ] Get up to speed in terms of the background knowledge for specific project
    - For Web3 / Crypto : [/defi/README.md](/defi/README.md)
    - For Arbitrage / Modeling: [/docs/From_zero_to_modeling.md](/docs/From_zero_to_modeling.md)

@Chandramani05
[ ] Read [How to organize your work](docs/How_to_organize_your_work.md)
[ ] Read [Quick start for developing](docs/Quick_start_for_developing.md)
[ ] Make sure the Docker dev container works
[ ] Make sure the unit tests run successfully
[ ] Read [Sorrentum Python coding style guide](https://docs.google.com/document/d/1R6jhFDbZKvyDdbnSQ9DA_N8417YF13hMI_Uw4quO4Xk)
[ ] Get assigned a warm-up issue
[ ] Get up to speed in terms of the background knowledge for specific project
    - For Web3 / Crypto : [/defi/README.md](/defi/README.md)
    - For Arbitrage / Modeling: [/docs/From_zero_to_modeling.md](/docs/From_zero_to_modeling.md)

@dchoi127
[ ] Read [How to organize your work](docs/How_to_organize_your_work.md)
[ ] Read [Quick start for developing](docs/Quick_start_for_developing.md)
[ ] Make sure the Docker dev container works
[ ] Make sure the unit tests run successfully
[ ] Read [Sorrentum Python coding style guide](https://docs.google.com/document/d/1R6jhFDbZKvyDdbnSQ9DA_N8417YF13hMI_Uw4quO4Xk)
[ ] Get assigned a warm-up issue
[ ] Get up to speed in terms of the background knowledge for specific project
    - For Web3 / Crypto : [/defi/README.md](/defi/README.md)
    - For Arbitrage / Modeling: [/docs/From_zero_to_modeling.md](/docs/From_zero_to_modeling.md)

@Dylan-Celli
[ ] Read [How to organize your work](docs/How_to_organize_your_work.md)
[ ] Read [Quick start for developing](docs/Quick_start_for_developing.md)
[ ] Make sure the Docker dev container works
[ ] Make sure the unit tests run successfully
[ ] Read [Sorrentum Python coding style guide](https://docs.google.com/document/d/1R6jhFDbZKvyDdbnSQ9DA_N8417YF13hMI_Uw4quO4Xk)
[ ] Get assigned a warm-up issue
[ ] Get up to speed in terms of the background knowledge for specific project
    - For Web3 / Crypto : [/defi/README.md](/defi/README.md)
    - For Arbitrage / Modeling: [/docs/From_zero_to_modeling.md](/docs/From_zero_to_modeling.md)

@thejameszhang
[ ] Read [How to organize your work](docs/How_to_organize_your_work.md)
[ ] Read [Quick start for developing](docs/Quick_start_for_developing.md)
[ ] Make sure the Docker dev container works
[ ] Make sure the unit tests run successfully
[ ] Read [Sorrentum Python coding style guide](https://docs.google.com/document/d/1R6jhFDbZKvyDdbnSQ9DA_N8417YF13hMI_Uw4quO4Xk)
[ ] Get assigned a warm-up issue
[ ] Get up to speed in terms of the background knowledge for specific project
    - For Web3 / Crypto : [/defi/README.md](/defi/README.md)
    - For Arbitrage / Modeling: [/docs/From_zero_to_modeling.md](/docs/From_zero_to_modeling.md)

@FirstSingularity
[ ] Read [How to organize your work](docs/How_to_organize_your_work.md)
[ ] Read [Quick start for developing](docs/Quick_start_for_developing.md)
[ ] Make sure the Docker dev container works
[ ] Make sure the unit tests run successfully
[ ] Read [Sorrentum Python coding style guide](https://docs.google.com/document/d/1R6jhFDbZKvyDdbnSQ9DA_N8417YF13hMI_Uw4quO4Xk)
[ ] Get assigned a warm-up issue
[ ] Get up to speed in terms of the background knowledge for specific project
    - For Web3 / Crypto : [/defi/README.md](/defi/README.md)
    - For Arbitrage / Modeling: [/docs/From_zero_to_modeling.md](/docs/From_zero_to_modeling.md)

@Samg54
[ ] Read [How to organize your work](docs/How_to_organize_your_work.md)
[ ] Read [Quick start for developing](docs/Quick_start_for_developing.md)
[ ] Make sure the Docker dev container works
[ ] Make sure the unit tests run successfully
[ ] Read [Sorrentum Python coding style guide](https://docs.google.com/document/d/1R6jhFDbZKvyDdbnSQ9DA_N8417YF13hMI_Uw4quO4Xk)
[ ] Get assigned a warm-up issue
[ ] Get up to speed in terms of the background knowledge for specific project
    - For Web3 / Crypto : [/defi/README.md](/defi/README.md)
    - For Arbitrage / Modeling: [/docs/From_zero_to_modeling.md](/docs/From_zero_to_modeling.md)

@lokashrinav
[ ] Read [How to organize your work](docs/How_to_organize_your_work.md)
[ ] Read [Quick start for developing](docs/Quick_start_for_developing.md)
[ ] Make sure the Docker dev container works
[ ] Make sure the unit tests run successfully
[ ] Read [Sorrentum Python coding style guide](https://docs.google.com/document/d/1R6jhFDbZKvyDdbnSQ9DA_N8417YF13hMI_Uw4quO4Xk)
[ ] Get assigned a warm-up issue
[ ] Get up to speed in terms of the background knowledge for specific project
    - For Web3 / Crypto : [/defi/README.md](/defi/README.md)
    - For Arbitrage / Modeling: [/docs/From_zero_to_modeling.md](/docs/From_zero_to_modeling.md)

@okritvik
[ ] Read [How to organize your work](docs/How_to_organize_your_work.md)
[ ] Read [Quick start for developing](docs/Quick_start_for_developing.md)
[ ] Make sure the Docker dev container works
[ ] Make sure the unit tests run successfully
[ ] Read [Sorrentum Python coding style guide](https://docs.google.com/document/d/1R6jhFDbZKvyDdbnSQ9DA_N8417YF13hMI_Uw4quO4Xk)
[ ] Get assigned a warm-up issue
[ ] Get up to speed in terms of the background knowledge for specific project
    - For Web3 / Crypto : [/defi/README.md](/defi/README.md)
    - For Arbitrage / Modeling: [/docs/From_zero_to_modeling.md](/docs/From_zero_to_modeling.md)

@samarth9008
[ ] Read [How to organize your work](docs/How_to_organize_your_work.md)
[ ] Read [Quick start for developing](docs/Quick_start_for_developing.md)
[ ] Make sure the Docker dev container works
[ ] Make sure the unit tests run successfully
[ ] Read [Sorrentum Python coding style guide](https://docs.google.com/document/d/1R6jhFDbZKvyDdbnSQ9DA_N8417YF13hMI_Uw4quO4Xk)
[ ] Get assigned a warm-up issue
[ ] Get up to speed in terms of the background knowledge for specific project
    - For Web3 / Crypto : [/defi/README.md](/defi/README.md)
    - For Arbitrage / Modeling: [/docs/From_zero_to_modeling.md](/docs/From_zero_to_modeling.md)

@lokashrinav
[ ] Read [How to organize your work](docs/How_to_organize_your_work.md)
[ ] Read [Quick start for developing](docs/Quick_start_for_developing.md)
[ ] Make sure the Docker dev container works
[ ] Make sure the unit tests run successfully
[ ] Read [Sorrentum Python coding style guide](https://docs.google.com/document/d/1R6jhFDbZKvyDdbnSQ9DA_N8417YF13hMI_Uw4quO4Xk)
[ ] Get assigned a warm-up issue
[ ] Get up to speed in terms of the background knowledge for specific project
    - For Web3 / Crypto : [/defi/README.md](/defi/README.md)
    - For Arbitrage / Modeling: [/docs/From_zero_to_modeling.md](/docs/From_zero_to_modeling.md)

@patel954
[ ] Read [How to organize your work](docs/How_to_organize_your_work.md)
[ ] Read [Quick start for developing](docs/Quick_start_for_developing.md)
[ ] Make sure the Docker dev container works
[ ] Make sure the unit tests run successfully
[ ] Read [Sorrentum Python coding style guide](https://docs.google.com/document/d/1R6jhFDbZKvyDdbnSQ9DA_N8417YF13hMI_Uw4quO4Xk)
[ ] Get assigned a warm-up issue
[ ] Get up to speed in terms of the background knowledge for specific project
    - For Web3 / Crypto : [/defi/README.md](/defi/README.md)
    - For Arbitrage / Modeling: [/docs/From_zero_to_modeling.md](/docs/From_zero_to_modeling.md)

**Comment by FirstSingularity** [comment]
The links for [How to organize your work](https://github.com/sorrentum/sorrentum/issues/docs/How_to_organize_your_work.md) and [Quick start for developing](https://github.com/sorrentum/sorrentum/issues/docs/Quick_start_for_developing.md) are not found. Will the files they point to be uploaded soon?

**Comment by gpsaggese** [comment]
Ops fixing

**Comment by gpsaggese** [comment]
@FirstSingularity should they work now. Can you pls retry?

**Comment by dchoi127** [comment]
@gpsaggese The links work for me. 

I was attempting to set up the docker environment detailed in [Quick start for developing](https://github.com/sorrentum/sorrentum/issues/docs/Quick_start_for_developing.md) however I'm having issues at first line.

```
> source dev_scripts/client_setup/build.sh
```
<img width="730" alt="Screenshot 2023-05-01 at 7 26 23 PM" src="https://user-images.githubusercontent.com/93415557/235548526-58cddbac-21cd-4e8b-b922-d1250b475e25.png">

Am I doing something incorrectly?

**Comment by gpsaggese** [comment]
The code needs to be cloned in a specific dir like `/Users/<YOUR_USER>/src` for everything to work automatically.
We have more documentation about this that we will add.

@PomazkinG can you pls add a line in the doc with this info?

**Comment by PomazkinG** [comment]
> @PomazkinG can you pls add a line in the doc with this info?

- [ ] https://github.com/sorrentum/sorrentum/pull/194

**Comment by FirstSingularity** [comment]
> @FirstSingularity should they work now. Can you pls retry?

All good now thanks.

**Comment by dchoi127** [comment]
Submitted a issue [here](https://github.com/sorrentum/sorrentum/issues/196) for docker

**Comment by Vishnusaju24** [comment]
@samarth9008 @gpsaggese
 I'm trying to set up the docker environment based on [Quick start for developing](https://github.com/sorrentum/sorrentum/issues/docs/Quick_start_for_developing.md).
 
 However I'm facing a 'refusing to fetch into branch' issue, when attempting 'I git_merge_master'
<img width="800" alt="Screenshot 2023-05-22 at 10 17 23 PM" src="https://github.com/sorrentum/sorrentum/assets/52094332/70a865ab-c4c3-4cc7-b459-135d0b85e964">

Is there something I'm doing wrong? I did the steps before this one. Though I didn't have a src, I created it and then cloned the repository there.

**Comment by samarth9008** [comment]
Are you running this command from a different branch then master? Because this command is used to merge master branch to your branch to keep your branch updated like master.

**Comment by yiyunlei** [comment]
@samarth9008 I have two checklists, could you delete one?

**Comment by gpsaggese** [comment]
@samarth9008 let's post a list for new contributors as a comment, instead of editing the same one (unless we need to fix things), since notifications don't help in that case. Thx for keeping an eye on this.

**Comment by samarth9008** [comment]
How's the progress? If you are facing any kind of errors, feel free to post it in the comment. Can you guys provide any kind of ETA? We would like you to get done with it in this week.

@Aniket-Parlikar  
@garg1998 
@aryananwar 
@zli00185 
@christyanthony 
@Vishnusaju24 
@yiyunlei 
@dhimuk

Feel free to edit this comment for your name.

**Comment by dhimuk** [comment]
@samarth9008 I should be done by the end of the week.

**Comment by aryananwar** [comment]
Hi, I'm having some trouble starting the docker container using "i
docker_bash", it says that "i" is not recognized. I've tried running the
docker_bash files by just clicking on them from, but that doesn't work
either.

**Comment by samarth9008** [comment]
What system you are using? Did you configure the python environment?

**Comment by aryananwar** [comment]
I'm on Windows10, I've realized my problem is I have not set up my
environment. Is there a readme for this?

**Comment by aryananwar** [comment]
Never mind, I've found it, I'll let you know if anything else arises.
Thanks!

**Comment by gpsaggese** [comment]
@samarth9008 if it makes your life easier you can file a bug per on-boarding, so that the threads are separated.
I would do as you go: no need to create issues beforehand, but you create one issue per "active" person.

**Comment by samarth9008** [comment]
What environment you are trying to develop? @aryananwar Wait for today, I will let you know what you have to do since you are using windows OS.

**Comment by samarth9008** [comment]
I would suggest to keep one issue for now as we do not have many people and also students can learn from the errors of other students by reviewing the comments. If needed I will create issue per active person.

**Comment by aryananwar** [comment]
Got it, I can use MacOS as well if that makes it easier for you

**Comment by samarth9008** [comment]
If you are using MacOs than just follow https://github.com/sorrentum/sorrentum/blob/master/docs/Quick_start_for_developing.md. If you run each step as mentioned, your environment should build up. If you still face any errors, post it here.

**Comment by yiyunlei** [comment]
> How's the progress? If you are facing any kind of errors, feel free to post it in the comment. Can you guys provide any kind of ETA? We would like you to get done with it in this week.
> 
> @Aniket-Parlikar @garg1998 @aryananwar @zli00185 @christyanthony @Vishnusaju24 @yiyunlei @dhimuk
> 
> Feel free to edit this comment for your name.

I will finish before the end of Sunday.

**Comment by aryananwar** [comment]
while im trying to merge the master branch, i'm getting an error "fatal: refusing to fetch into branch 'refs/heads/master'".

**Comment by samarth9008** [comment]
https://github.com/sorrentum/sorrentum/issues/189#issuecomment-1559165968

**Comment by Vishnusaju24** [comment]
@samarth9008 For "Make sure the unit tests run successfully" and "Get assigned a warm-up issue", do we reach out to you?

**Comment by aryananwar** [comment]
I've just finished the quick start to development, I also need to see if my unit tests run properly and getting assigned a warm up issue.

**Comment by samarth9008** [comment]
@gpsaggese How should they run unit tests? We will assign you the warm issue once you are done with coding style guide.

**Comment by aryananwar** [comment]
Hi, I've finished reading the coding style guide.

**Comment by samarth9008** [comment]
You guys can start with last steps. We will have the issue ready for you.

**Comment by aryananwar** [comment]
What are the last steps? Getting a background for a specific project?

**Comment by samarth9008** [comment]
The last item of the checklist.

**Comment by hhxjqm** [comment]
Hi, I follow "https://github.com/sorrentum/sorrentum/blob/master/docs/Quick_start_for_developing.md"

> i docker_bash
16:18:09 - WARN  hcache.py clear_global_cache:293                       Resetting 'global mem' cache '/mnt/tmpfs/tmp.cache.mem'
16:18:09 - WARN  hcache.py clear_global_cache:303                       Destroying '/mnt/tmpfs/tmp.cache.mem' ...

> i docker_jupyter
bash: /app/i: Permission denied

How can I fix this?

**Comment by PomazkinG** [comment]
> How can I fix this?

@hhxjqm run `i docker_jupyter` outside the Docker bash session, i.e. after doing `i docker_bash` type `exit` and press Enter to exit a Docker container

**Comment by dhimuk** [comment]
@samarth9008 Could u email the github invite link once again, I am not sure if I received it.

**Comment by yiyunlei** [comment]
@DanilYachmenev 
When I was reading the doc [Sorrentum Python coding style guide](https://github.com/sorrentum/sorrentum/blob/master/docs/Coding_Style_Guide.md), I couldn't find these two Python files: `helpers/system_interaction.py` and `dev_scripts/linter.py`. Perhaps they need to be updated.

<img width="836" alt="image" 
src="https://github.com/sorrentum/sorrentum/assets/42398651/1d510504-be73-4196-930d-2ff7124e6651">

**Comment by samarth9008** [comment]
> @samarth9008 Could u email the github invite link once again, I am not sure if I received it.

Sent one more time. @dhimuk

**Comment by samarth9008** [comment]
You do not need to learn about web3 currently because the project is paused. You will be assigned a warm-up issue and can also start with arbitrage reading.

**Comment by dhimuk** [comment]
@samarth9008 I think I have finished up everything on the checklist. What are my next steps?

**Comment by samarth9008** [comment]
> @samarth9008 I think I have finished up everything on the checklist. What are my next steps?

I can assign one warm-up issue available. LMK if you can work on it or need a more easy one.

**Comment by hhxjqm** [comment]
@samarth9008 I finish arbitrage reading, where can I find the warm-up issue or any task?

**Comment by samarth9008** [comment]
We will assign you.

**Comment by gpsaggese** [comment]
Let's close this bug and we can create an on-boarding file for each contributors using the new checklist.
