### ISSUE TITLE
Gather price data for the Arbitrage machine

### ISSUE THREAD

**Issue by thejameszhang** [sorrentum/sorrentum#193]
Juraj, GP told me to ask you if you can gather historical exchange rate data for this time interval (2019-2023) on these exchanges (binance, binance futures, binance spot, okx)

The original data is for this project is at this [gdrive link](https://docs.google.com/document/d/1SceHHhOWyusWJYibMvQhyz2_qxic9By-deGFwCHxKW8/edit#)

**Comment by gpsaggese** [comment]
Adding more details from yesterday meetings, the idea is to collect more data to throw in the arbitrage machinery:

1) Download data from DEXes (e.g., Uniswap, Pancake, Sushi)
   - We have an interface to do that. @samarth9008 knows the code that was implemented in one of the DATA605 project
   - [ ] @samarth9008 can file bugs to outsource this task to students
   - [ ] @jsmerix should think of how to on-board this data in our platform
   - This is also needed for DaoSwap project @DanilYachmenev @tamriq 

2) @jsmerix Do we have data from exchanges denominated in EUR or other non-USD currencies?

3) @jsmerix We should have data for Binance denominated in USDT vs BUSD
 
4) We are interested in any price data that has different denomination (probably even stable-coins, but there might not be many arbitrage opportunities unless there is some depegging)

**Comment by jsmerix** [comment]
> Do we have data from exchanges denominated in EUR or other non-USD currencies?

Our universes only work with `*_USDT` pairs

> We should have data for Binance denominated in USDT vs BUSD

We have some data for `BTC_BUSD` and `ETH_BUSD`

**Comment by gpsaggese** [comment]
Ok then a task for the students is to collect all the traded universes at all exchanges with 24hr volume from the exchange (before we download the price data). I'll file a bug.

Not sure if we have some code about this @PomazkinG @DanilYachmenev @mongolianjesus 
I am sure that @max-rsrch did some work on this at the very beginning. We should check his notebooks.

**Comment by jsmerix** [comment]
Obsolete.
