### ISSUE TITLE
Docker Syncing / Jupyter issue

### ISSUE THREAD

**Issue by dchoi127** [sorrentum/sorrentum#196]
While working through [Setting Up Docker](https://github.com/sorrentum/sorrentum/blob/master/docs/Quick_start_for_developing.md) I ran into some warnings / issues. 

No issues arise until running
```
> i docker_bash
```
In which I get errors like 

<img width="644" alt="Screenshot 2023-05-03 at 10 29 47 PM" src="https://user-images.githubusercontent.com/93415557/236098022-36c63e07-1161-42ee-b1a3-8ece7ce8e0f0.png">

Below are some warnings I get when executing the command

<img width="645" alt="Screenshot 2023-05-03 at 10 30 19 PM" src="https://user-images.githubusercontent.com/93415557/236098076-3d8624b6-c80a-4332-bcc4-468365ec3bb0.png">
<img width="710" alt="Screenshot 2023-05-03 at 10 31 04 PM" src="https://user-images.githubusercontent.com/93415557/236098149-4dd6b6f8-c24d-48ab-ad7c-bc13624d8ca4.png">

When running 
```
> i docker_jupyter
```

I get the following error 

<img width="1345" alt="Screenshot 2023-05-03 at 10 32 21 PM" src="https://user-images.githubusercontent.com/93415557/236098299-f9958ae3-cd10-4ba7-bf7a-6635de45a1c6.png">

This is what I get when attempting to connect to the browser

<img width="688" alt="Screenshot 2023-05-03 at 10 33 52 PM" src="https://user-images.githubusercontent.com/93415557/236098448-f3904d4b-9865-4c2d-bfd7-1cfdd36288dc.png">

**Comment by dchoi127** [comment]
> @dchoi127
> 
> 1. as for `i docker_bash`: is it blocking? Ok to ignore the warnings if it does not prevent you from runnings the tests
> 2. can you try: `http://localhost:5011/` or `http://127.0.0.1:5011` instead of `http://b504...:5011/`? https://jupyter-notebook.readthedocs.io/en/stable/public_server.html
> 
> lmk if it works and I'll update the docs

1. No blocking! It still allows me to run the tests (although I am not passing them but maybe that's unrelated)
2. Connecting to `http://localhost:5011/` or `http://127.0.0.1:5011` worked perfectly. Strangely the command output tells me to connect to `http://ed7090f5276b:5011/` which is wrong.

**Comment by PomazkinG** [comment]
updated the gdoc in https://github.com/sorrentum/sorrentum/pull/206, closing here
