### ISSUE TITLE
Organize and track the Web3 / Arbitrage bugs in ZenHub

### ISSUE THREAD

**Issue by DanilYachmenev** [sorrentum/sorrentum#204]
- [ ] Organize tasks on Zenhub
- [x] Give access to ZenHub to the team leaders
    - [x] Samarth @samarth9008
    - [x] Kumara @okritvik
    - [x] James @thejameszhang

FYI @tamriq @gpsaggese

**Comment by DanilYachmenev** [comment]
@gpsaggese, so actually before re-distributing remaining Zenhub tasks to EPICs, let's give the guys access to ZenHub as discussed

**Comment by gpsaggese** [comment]
I've invited our 3 friends. They should accept the invitation from ZenHub

@DanilYachmenev 
- can you post here the link to the ZenHub / GitHub doc so that they know how we use the systems for project management?
- Is it all markdown already? I have a bunch of PRs to process
- They should see only Sorrentum repo for now, but we can add them to cmamp and the rest if needed. For now I don't think it matters
- There is a bit of weirdness on the new EPICs / labels but I'll clean it up soon

**Comment by DanilYachmenev** [comment]
@samarth9008 @okritvik @thejameszhang
- Here is a link to [[ZenHub / GitHub doc](https://github.com/sorrentum/sorrentum/blob/master/docs/GitHub_ZenHub_workflows.md)]
- Read it pls, put additional attention to EPIC concept, get familiar with them
- After you get the idea, go to `New Issues` bucket at ZenHub, go over the bugs and when you are sure, do:
    - Set EPIC to the issues that do not have it
    - Put issues in the corresponding buckets

Text here if you have any questions and clarifications so we can clarify and update the docs

**Comment by samarth9008** [comment]
We do not have access to this link. **See the current list of Epics on GH [here](https://github.com/cryptokaizen/cmamp/issues?q=is%3Aopen+is%3Aissue+label%3AEpic)**

**Comment by DanilYachmenev** [comment]
> * ZenHub / GitHub doc

thx, fixed, should be available now

**Comment by DanilYachmenev** [comment]
Talking about bug organization
There are some GFI issues at `cmamp` that can be implemented by students, but they cannot access the specs IIUC
e.g.
https://github.com/cryptokaizen/cmamp/issues/1486
https://github.com/cryptokaizen/cmamp/issues/755

So my suggestion would be to create a dup of such bugs at Sorrentum and remove the obsolete versions

@gpsaggese, wdyt?

**Comment by gpsaggese** [comment]
Yes let's copy to Sorrentum and then delete the old ones

**Comment by DanilYachmenev** [comment]
> Yes let's copy to Sorrentum and then delete the old ones

Actually, after a closer observation I found that functions in these tasks are being used in `im_v2`, like at `im_v2/im_lib_tasks.py`

IIRC students do not have access to this lib
Therefore, we cant delegate these tasks to them through `sorrentum`

**Comment by DanilYachmenev** [comment]
Closing as mostly done and already obsolete
