### ISSUE TITLE
Team3: Implement sandbox for CoinMarketCap

### ISSUE THREAD

**Issue by samarth9008** [sorrentum/sorrentum#22]

**Comment by Alexander301301** [comment]
I have been running the code provided in GitHub and have been running into issues accessing the data. As mentioned, it seems as if the string responses are all encrypted so they just show up as random numbers and letters. In addition, the numerical data itself does not seem to represent reality as almost all the numbers are decimal points and the prices of ETH and BTC are not less than a dollar. Have you found any workaround to get the actual data?

**Comment by gpsaggese** [comment]
@Alexander301301 you want to give as much as possible around the problem and how to reproduce it.

E.g., can you show what are the encrypted responses?
Also pls provide more context around the decimal points. It might be that data is scaled with a fixed multiplier.

**Comment by Skylyyun** [comment]
> I have been running the code provided in GitHub and have been running into issues accessing the data. As mentioned, it seems as if the string responses are all encrypted so they just show up as random numbers and letters. In addition, the numerical data itself does not seem to represent reality as almost all the numbers are decimal points and the prices of ETH and BTC are not less than a dollar. Have you found any workaround to get the actual data?

I have found the solution from CoinMarketCap official docs:
https://coinmarketcap.com/api/documentation/v1#section/Introduction.

<img width="691" alt="image" src="https://user-images.githubusercontent.com/42398651/220685658-da17cd8e-3e18-4fda-8242-8fec6ad020fb.png">

So you have to get your own API key from the website and change the domain to `pro-api.coinmarketcap.com`.

<img width="1121" alt="image" src="https://user-images.githubusercontent.com/42398651/220684600-2bdc4884-8f0e-43fe-9da1-6d5449afa9bc.png">

After setting this, you can get real data by using the Jupyter Notebook example. The responses look like they are encrypted before because they are mock data for testing.

**Comment by gpsaggese** [comment]
@Skylyyun that's the attitude. Problems (in this case bugs) are only solved by keep trying without giving up.

**Comment by samarth9008** [comment]
Hello Team3,

The issue which we are facing is, we are not able to generate a pull request from your branch because you have made changes to a lot files which was not required. Here is a detailed solutions of what we want you to do so generating future pull requests will be easy for us. I understand the changes you have made was for your learning purpose and that is why we want you to create a new branch and you can keep using the old branch for your learning purpose.

Create a new branch "Issue22_Team3_Implement_sandbox_for_CoinMarketCap_2" from master

Switch to the new branch locally.
"git switch Issue22_Team3_Implement_sandbox_for_CoinMarketCap_2"

Make new directory inside "ml_projects" directory
"cd sorrentum_sandbox/examples/ml_projects/"
"mkdir SorrIssue22_Team3_Implement_sandbox_for_CoinMarketCap_2"

Copy all the code files which you have created for your project inside this new directory.

Push the changes to your new branch on github.

Make sure to use this directory for future submissions.

@YiyunLei @Alexander301301 @nnwosu3 @saadr1998 

Let us know if you face any problems.

**Comment by YiyunLei** [comment]
No problem, I'll do it later today.
