### ISSUE TITLE
WEB3 - Good First Issue

### ISSUE THREAD

**Issue by DanilYachmenev** [sorrentum/sorrentum#224]
EPIC to gather good first issues for the students

**Comment by gpsaggese** [comment]
Can we also use the corresponding label for the issues in the EPIC (the EPIC is visible only from ZH, while the label is visible for everyone)

**Comment by DanilYachmenev** [comment]
> Can we also use the corresponding label for the issues in the EPIC (the EPIC is visible only from ZH, while the label is visible for everyone)

Done

Should we also add issues with `Outsource` label from `cmamp` to this EPIC?
https://github.com/cryptokaizen/cmamp/labels/Outsource

**Comment by gpsaggese** [comment]
Closing this EPIC. Let's use EPICs to track milestones for software components and labels for Outsource and GFI
