### ISSUE TITLE
Programmatically change the sharing perms of Gdrive docs

### ISSUE THREAD

**Issue by samarth9008** [sorrentum/sorrentum#230]
We want to automatically assign permission to sorrentum google drive using a python script. We can create a group of contributors (maybe something that we can maintain like an audience)

Sources of contributors: https://docs.google.com/spreadsheets/d/1eRZJaj5-1g6W7w_Ay4UhJEdtAvrTTM1V94cKj6_Vwoc/edit#gid=1253964093

Link to the drive: https://drive.google.com/drive/u/1/folders/1LXwKpmaFWJI-887IoA50sVC8-dw_1L8I

Useful source: https://stackoverflow.com/questions/51411985/sharing-files-in-google-drive-using-python

**Comment by samarth9008** [comment]
Can you explain what are passing as an arguments in the program?

**Comment by gpsaggese** [comment]
Didn't review the code, but in terms of the interface:
```
> set_gdrive_perms.py --permission_file foobar.csv --account_info ...
```

Then permission file is a CSV like:
```
email,dir,permission
```
where dir is a Google dir and permission is "editor, commenter, viewer,none"

In this way we maintain a list of the current permissions and we can update the state.

Let's focus on deciding the interface, based on what's possible for the API and then we can finalize.
Also we want to have a quick markdown describing how to run the script, what info are needed (e.g., in terms of API key), examples of the script

FYI: Adding also @DanilYachmenev. Can you help with this to do it the way we usually do things?

**Comment by leggomyegg0** [comment]
[pr#276](https://github.com/sorrentum/sorrentum/pull/276)

**Comment by leggomyegg0** [comment]
@samarth9008 Yeah that's a good idea
