### ISSUE TITLE
Write unit tests to confirm that the timestamp representation for OHLCV data corresponds to what we expect

### ISSUE THREAD

**Issue by samarth9008** [sorrentum/sorrentum#244]
Generally we avoid interacting with 3rd party in unit test, that’s why we compromise by writing this as a superslow.

With this test we can keep updating the CCXT without worrying about silently changing the data semantics

In practice

- Let’s start with a test for binance spot and futures
- Pick two pairs (e.g. BTC_USDT, ETH_USDT), download ~5 minutes from a random time interval, i.e. dec 2022 -> this will be the golden outcome
- Use `CcxtExtractor` class to download the OHLCV  data
- Document which version of CCXT was used to download the data (inside the code is enough)
- The test should download the data and compare to the golden outcome to obtain a perfect match

**Comment by samarth9008** [comment]
@jsmerix Is there any reference to **`CcxtExtractor` class to download the OHLCV data**?

**Comment by samarth9008** [comment]
I have assigned myself temporarily. Once someone takes this issue, I will unassign myself.

**Comment by jsmerix** [comment]
> @jsmerix Is there any reference to CcxtExtractor class to download the OHLCV data?

Here is the class [definition](https://github.com/cryptokaizen/cmamp/blob/master/im_v2/ccxt/data/extract/extractor.py)

**Comment by yiyunlei** [comment]
I have some questions for this task:

1. Which specific version of CCXT should I use to generate the golden outcome data?

2. In the process of comparing the newly downloaded OHLCV data with the golden outcome, am I correct in understanding that all data points—not just the timestamp—need to perfectly match?

**Comment by jsmerix** [comment]
> Which specific version of CCXT should I use to generate the golden outcome data?

The one that is currently installed in the dev container, in this case it's `2.1,80`
```
>>> import ccxt
>>> ccxt.__version__
'2.1.80'
```

> In the process of comparing the newly downloaded OHLCV data with the golden outcome, am I correct in understanding that all data points—not just the timestamp—need to perfectly match?

For each timestamp, all fields (open, high, low, close, volume) need to match exactly between golden and actual (the currently downloaded data)

**Comment by yiyunlei** [comment]
When I tried to use `CcxtExtractor` class to download the OHLCV data, I got an ExchangeError and it shows that "Service unavailable from a restricted location". (https://api.binance.com/api/v3/exchangeInfo)
<img width="1123" alt="image" src="https://github.com/sorrentum/sorrentum/assets/42398651/e3ed89e4-5b11-441d-95f9-cc3a591af9cc">
<img width="1110" alt="image" src="https://github.com/sorrentum/sorrentum/assets/42398651/b418f9f4-1547-4f3d-a15f-ebd10bb1a3ce">
<img width="971" alt="image" src="https://github.com/sorrentum/sorrentum/assets/42398651/9be2a626-0d2b-4aeb-aa17-35662f689455">

I have searched for solutions but I only got this information:
https://www.reddit.com/r/api_connector/comments/z92w3p/binance_api/
We are ensuring our compliance controls restrict API trading based on IP address if your connection is from a restricted location, such as the United States, Malaysia, Ontario (Canada), Cuba, Iran, Syria, North Korea, Crimea, and other locations as designated by Binance Operators from time to time as a Restricted Location. If you are located in a restricted location your API trading will not be supported.

Can anyone use `CcxtExtractor` to download the OHLCV data, and how can I solve this bug?

**Comment by yiyunlei** [comment]
I can access https://api.binance.us/api/v3/exchangeInfo, but I cannot access https://api.binance.com/api/v3/exchangeInfo.

**Comment by gpsaggese** [comment]
Yeah they are geo-blocking. Let's talk on Telegram

**Comment by yiyunlei** [comment]
The test `test_download_ohlcv_timestamp_representation1` can run successfully in the new file `test_ccxt_version.py`, but after I moved it to the file `test_ccxt_extractor.py`, I got an unexpected bug.
