### ISSUE TITLE
Compile the list of the contributors to the Tulip white paper

### ISSUE THREAD

**Issue by samarth9008** [sorrentum/sorrentum#246]
Can everyone make sure there name is correct for the white paper?

We want to

- add everyone that makes a PR in Sorrentum
- make sure everyone tells us exactly how their name should be spelled
- keep people in alphabetical order by last name

List of names on the white paper currently

- Samarth KaPatel,
- Grisha Pomazkin,
- Juraj Smeriga,
- Danya Tikhomirov,
- Nina Trubacheva,
- Dan Yachmenev,
- Vladimir Yakovenko,
- Tamara Zhordaniya

FYI @PomazkinG @jsmerix @mongolianjesus @rheenina @DanilYachmenev @vladimir-yakovenko @tamriq

**Comment by PomazkinG** [comment]
> Grisha Pomazkin

Let' do `Grisha` (short version for friends) -> `Grigorii` (full version as in the ID)

**Comment by mongolianjesus** [comment]
> Danya Tikhomirov

Same as with Grisha: the correct name in all documents is "Daniil Tikhomirov".

**Comment by DanilYachmenev** [comment]
> * Dan Yachmenev,

Danil Iachmenev (I hate this "I" at the beginning, but docs are docs...)

**Comment by tamriq** [comment]
> Tamara Zhordaniya

Let's better use `Jordania`
