### ISSUE TITLE
Convert Docker Gdoc to Markdown

### ISSUE THREAD

**Issue by DanilYachmenev** [sorrentum/sorrentum#257]
- We need to convert a [Gdoc](https://docs.google.com/document/d/1SaHs0Q0uRUuFeNeTPrESjBDyMK7XMkgYlUosK6PFNew/edit?usp=sharing) about Docker to Markdown
- Instructions on how to convert Gdocs to Markdown are [here](https://github.com/sorrentum/sorrentum/blob/master/docs/Documentation_about_guidelines.md#gdocs---markdown)
-  PR example is [here](https://github.com/sorrentum/sorrentum/pull/198)

Assigning @samarth9008 to re-distribute

**Comment by Aniket-Parlikar** [comment]
@samarth9008 In which directory would you like me to update the .md file?

**Comment by DanilYachmenev** [comment]
> @DanilYachmenev @samarth9008 In which directory would you like me to update the .md file?

Same as Jupyter notebook you worked at, `/docs`

**Comment by samarth9008** [comment]
@yiyunlei Do not consider previous work done. Start everything from scratch by creating new branch.

**Comment by samarth9008** [comment]
For markdown, it will be image folders. @yiyunlei

**Comment by yiyunlei** [comment]
https://github.com/sorrentum/sorrentum/blob/master/docs/Documentation_about_guidelines.md#embedding-screenshots

The doc also mentions Markdown should use GitHub links?

<img width="665" alt="image" src="https://github.com/sorrentum/sorrentum/assets/42398651/605213e3-ff95-4ce0-8819-9a19bed655cb">

**Comment by DanilYachmenev** [comment]
> https://github.com/sorrentum/sorrentum/blob/master/docs/Documentation_about_guidelines.md#embedding-screenshots
> 
> The doc also mentions Markdown should use GitHub links?
> 
> <img alt="image" width="665" src="https://user-images.githubusercontent.com/42398651/247612668-605213e3-ff95-4ce0-8819-9a19bed655cb.png">

this is an approach to use if general approach with image folders is not applicable
will update the doc
