### ISSUE TITLE
Replace `pytest.raises` with `self.assertRaises`

### ISSUE THREAD

**Issue by DanilYachmenev** [sorrentum/sorrentum#258]
Replace `pytest.raises` with `self.assertRaises` everywhere in the code

- Use `dev_scripts/replace_text.py` and write `.sh` script to rename all the instances automatically
    - Read about the script usage right at the file
    - See `.sh` script examples at `dev_scripts/cleanup_scripts`, smth like `dev_scripts/cleanup_scripts/CMTask3336_rename_SimulatedBroker.sh`
- Find `pytest.raises` uses with `grep` or VScode/Pycharm search interface
    - e.g.
        ```
        > jackpy "raise" | grep with | grep -v assert
           dataflow/core/nodes/test/test_transformers.py:510:        with pytest.raises(AssertionError):
           dataflow/core/nodes/test/test_transformers.py:740:        with pytest.raises(AssertionError):
        ```
- Run tests after the replacement to check that nothing is broken

Assigning @samarth9008 to re-distribute

**Comment by Vishnusaju24** [comment]
Hello @DanilYachmenev @samarth9008 ,

I'm little confused about the second point. Find pytest.raises uses with grep or VScode/Pycharm search interface.

Do we need to find in a specific file or am I missing out on something?

Here is my broad understanding of replace_text.py:
1. Find and read all files, exclude the ones not needed.
2. Replace strings inside file.

**Comment by DanilYachmenev** [comment]
> Do we need to find in a specific file or am I missing out on something?

Replace all the instances that you find, in all the files
in this case you do not need to exclude anything

> Here is my broad understanding of replace_text.py:

Pls read `dev_scripts/replace_text.py` docstrings (top of the file basically)
It can do a lot more)

**Comment by samarth9008** [comment]
What is your script code? Can you create a branch and upload it under cleanup_scripts as shown in the specs?

**Comment by Vishnusaju24** [comment]
Branch name is: pytest_first_Issue
File Name:rename_pytestraises.sh

**Comment by samarth9008** [comment]
Branch Name should be like the way you had it for Data605. For now its fine.

**Comment by samarth9008** [comment]
I think `replace_text.py` is one level above the cleanup_scripts. So either run it from the directory where the replace script or change the `.sh` file with something like `../replace.py`. Go through [this](https://github.com/sorrentum/sorrentum/blob/master/docs/GitHub_ZenHub_workflows.md#issue-workflows) section to understand how to post errors you are facing.

**Comment by gpsaggese** [comment]
Just re-iterating

1) No screenshots to report errors
2) Let's follow the naming convention for branches
3) There are a bunch of examples of how to use the replacing flow here `dev_scripts/cleanup_scripts/`

@Vishnusaju24 pls re-read all the conventions to follow the procedures

**Comment by Vishnusaju24** [comment]
@gpsaggese @samarth9008 Will keep it mind.

**Comment by samarth9008** [comment]
I see you are near to the solution. 
1. We do not want to commit all those extra generated files such as logs, cfile..... so please do not commit them.
2. The name of your script is not right. This way you should name your branch. Look at other files in the directory to understand how the files should be named.
3. Create a new branch and PR to push only the required files. That is your script and the places where the text is replaced.

**Comment by Vishnusaju24** [comment]
> I see you are near to the solution.
> 
> 1. We do not want to commit all those extra generated files such as logs, cfile..... so please do not commit them.
>
Sure Samarth, I shall do that.
> 2. The name of your script is not right. This way you should name your branch. Look at other files in the directory to understand how the files should be named.
>
Noted.
> 3. Create a new branch and PR to push only the required files. That is your script and the places where the text is replaced.
>
Should I delete or close the current PR?

**Comment by KangmingL** [comment]
@samarth9008 Just for clarification, I need to write a `.sh` script to automatically call `replace_text.py` to replace all `pytest.raises` with `self.assertRaises` in the project. Is that correct?

**Comment by samarth9008** [comment]
You will create a `replace_text.py` and then run it to replace the text everywhere. Take a look at this PR #336.

**Comment by KangmingL** [comment]
@samarth9008 I'm a bit confused, `replace_text.py` already exists in `dev_script`, why do I need to create it again?

**Comment by samarth9008** [comment]
Oh yes! You are right. I misinterpreted it.

**Comment by DanilYachmenev** [comment]
> @samarth9008 Just for clarification, I need to write a `.sh` script to automatically call `replace_text.py` to replace all `pytest.raises` with `self.assertRaises` in the project. Is that correct?

Yess
and then call it to implement the renaming

**Comment by DanilYachmenev** [comment]
> @DanilYachmenev Is there any convenient method to run tests all together in my case, or testing has to be done one by one manually.

well, if there is too many of them, you can do
```
> i run_fast_tests
> i run_slow_tests
> i run_superslow_tests
```
depending on the type of tests that you've made updates at (if there are no `slow` tests, no need to run them ofc)

you can read more about unit tests in the doc that is being converted currently (go to changed files and open preview)
https://github.com/sorrentum/sorrentum/pull/307

but keep in mind that it takes time since it will run all the tests of the specified types

**Comment by KangmingL** [comment]
Got it! Thanks.

**Comment by DanilYachmenev** [comment]
@samarth9008 could you pls check out to a new branch related to this PR and run the [script](https://github.com/sorrentum/sorrentum/pull/350) there?
Just run the script, see if it did the right changes and file a PR
The GH action tests will start, we see if they pass and then merge the related changes

**Comment by samarth9008** [comment]
Are GH actions available on the sorrentum side?

**Comment by DanilYachmenev** [comment]
> Are GH actions available on the sorrentum side?

no, we need to do it on `cmamp`

**Comment by samarth9008** [comment]
Two test cases are failing one in each fast and slow.

https://github.com/cryptokaizen/cmamp/pull/4646

1. Fast
https://github.com/cryptokaizen/cmamp/blob/3439c865a51bf5cd940172f520c0449385a0bf14/im_v2/common/data/extract/test/test_extract_utils.py#L861C7-L861C7

```
Traceback (most recent call last):
  File "/app/im_v2/common/data/extract/test/test_extract_utils.py", line 875, in test_empty_dataset
    self.assertIn("No data", str(fail))
  File "/usr/lib/python3.8/unittest/case.py", line 1179, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib/python3.8/unittest/case.py", line 753, in fail
    raise self.failureException(msg)
AssertionError: 'No data' not found in '<unittest.case._AssertRaisesContext object at 0x7f492e464610>'
```
2. Slow
https://github.com/cryptokaizen/cmamp/blob/3439c865a51bf5cd940172f520c0449385a0bf14/im_v2/common/data/extract/test/test_extract_utils.py#L810

```
Traceback (most recent call last):
  File "/app/im_v2/common/data/extract/test/test_extract_utils.py", line 816, in test_download_and_resample_bid_ask_data
    self.check_resampler()
  File "/app/im_v2/common/data/extract/test/test_extract_utils.py", line 807, in check_resampler
    self.assertIn("Missing symbols", str(fail))
  File "/usr/lib/python3.8/unittest/case.py", line 1179, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib/python3.8/unittest/case.py", line 753, in fail
    raise self.failureException(msg)
AssertionError: 'Missing symbols' not found in '<unittest.case._AssertRaisesContext object at 0x7f02f3cefb50>'
```
