### ISSUE TITLE
Enable fast tests action

### ISSUE THREAD

**Issue by jsmerix** [sorrentum/sorrentum#282]

**Comment by jsmerix** [comment]
@gpsaggese can you add me as Admin on Sorrentum ( Settings > Collaborators and teams > Manage Access > Set Role to Admin). In order to make actions work we need to set the same set of secrets. Unless we have an enterprise package I believe we cannot set secress across organizations so it has to be done on a per repo basis.

**Comment by gpsaggese** [comment]
Done

- Do we have enterprise package in CK? If so we can upgrade here too to make our life easier
- There is a Python flow set up by Nikola to set all the secrets in one shot. I've used it a few times (it's documented in a gdoc)

**Comment by jsmerix** [comment]
> Do we have enterprise package in CK? If so we can upgrade here too to make our life easier

Enterprise is 20$/user/month, and right out of the bat I am not sure if it still would be possible to set cross-account secrets since cmamp repo is within user `cryptomtc` and `sorrentum` is within `sorrentum`

> There is a Python flow set up by Nikola to set all the secrets in one shot. I've used it a few times (it's documented in a gdoc)

I'll try to find and use it.

**Comment by gpsaggese** [comment]
> Enterprise is 20$/user/month, and right out of the bat I am not sure if it still would be possible to set cross-account secrets since cmamp repo is within user cryptomtc and sorrentum is within sorrentum

Good point. Cost is prohibitive. The easiest way is to use the script pointed by @PomazkinG to set the secrets in both repos.

**Comment by jsmerix** [comment]
We have got to a checkpoint of fast tests enabled but we need to resolve test failure (most of them due to conflicts within repos) https://github.com/sorrentum/sorrentum/pull/325

**Comment by jsmerix** [comment]
> @jsmerix anything else stopping from enabling the regressions?

Nothing else, this order and list of actions seems correct.

**Comment by LibertasSpZ** [comment]
Since checkpoint in #524 / #527 says all fast tests passed, would this and #283 be closed?

**Comment by jsmerix** [comment]
Fast tests are not enabled https://github.com/sorrentum/sorrentum/actions/runs/6229593355/job/16908348181
