### ISSUE TITLE
Fix `lint_md.sh`

### ISSUE THREAD

**Issue by DanilYachmenev** [sorrentum/sorrentum#285]
Follow-up from https://github.com/sorrentum/sorrentum/pull/284#discussion_r1206908770

Current version of `dev_scripts/lint_md.sh` is not working quite well
Probably need a refactoring or a guide on how to use it

@gpsaggese lets discuss it here so I could move it to the documentation afterwards

**Comment by gpsaggese** [comment]
Passing to @samarth9008 since this is a perfect good first issue.

We want to do the usual dockerization. In this case no need for extra Python code, it can be done just in bash (like you did for the Web3 linter)
