### ISSUE TITLE
Make `general.md` doc public

### ISSUE THREAD

**Issue by DanilYachmenev** [sorrentum/sorrentum#286]
- [x] Move `documentation/general/general.md` to `docs`
- [x] Update the doc with actual information

**Comment by gpsaggese** [comment]
Good job noticing that it is out of sync and filing a bug.

1) Can you pls merge any other info from https://docs.google.com/document/d/1Nn53hJem7stMsqZuruVvedhsWqHufyiLkANs2GSPgZo/edit#heading=h.gubmcz3yf1re
and kill that gdoc

2) Feel free to do a PR with the proposed changes based on our current process

3) Let's add a link to the README as usual

Pls try to do it ASAP so we can have the Summer interns digest it. Thx!
