### ISSUE TITLE
Rename _get_docker_cmd -> _get_docker_run_cmd

### ISSUE THREAD

**Issue by samarth9008** [sorrentum/sorrentum#298]
**Rename `_get_docker_cmd` -> `_get_docker_run_cmd` in `helpers/lib_tasks.py` and everywhere**
- Use `dev_scripts/replace_text.py` and write `.sh` script to rename all the instances automatically
    - Read about the script usage right at the file
    - See `.sh` script examples at `dev_scripts/cleanup_scripts`, smth like `dev_scripts/cleanup_scripts/CMTask3336_rename_SimulatedBroker.sh`
- Find `_get_docker_cmd` uses with `grep` or VScode/Pycharm search interface
    - e.g.
        ```
        > jackpy "raise" | grep with | grep -v assert
           dataflow/core/nodes/test/test_transformers.py:510:        with pytest.raises(AssertionError):
           dataflow/core/nodes/test/test_transformers.py:740:        with pytest.raises(AssertionError):
        ```
- Rename `_get_docker_cmd` -> `_get_docker_run_cmd` with the script
- Run tests after the replacement to check that nothing is broken

- [Docs](https://docs.google.com/document/d/1rAInLl-JENQtMqt6RvT1zfPX8kNPwJB0hM83pVy57oI/edit#heading=h.yjds78gy39ib)

**Comment by samarth9008** [comment]
How is the progress? Any questions?

**Comment by zli00185** [comment]
I quickly went through the replace_text.py yesterday and still try to figure out how to use those commands in it.

**Comment by zli00185** [comment]
How to run tests to make sure the file is not broken?

**Comment by samarth9008** [comment]
Did you created the script the for replacement? If so, push it on your branch on GitHub.

Is your script working successfully?

You can refer to this [file](https://github.com/sorrentum/sorrentum/blob/54a095377dd1efa073714fcadd45d4c91a0f2349/docs/python_unit_tests.md) to understand how to run the test.

**Comment by samarth9008** [comment]
> No, I haven't created replacement. Do I need to make sure the unit test run successfully before doing the editing and replacing?

The unit test should run successfully after doing the editing and replacing.

Understand the specs carefully. Proceed in written mannered. Ask questions if you are not clear.

**Comment by samarth9008** [comment]
> Questions: *Does everywhere in "rename ... in helpers/lib_tasks.py and everywhere" means rename the string in all other the files in helpers directory or something else?

Everywhere in the repo. Start from the root of the repo.

**Comment by zli00185** [comment]
File uploaded

**Comment by samarth9008** [comment]
Close as completed.
