### ISSUE TITLE
Interns to Send Morning Email

### ISSUE THREAD

**Issue by samarth9008** [sorrentum/sorrentum#304]
- As you start working after being assigned a issue, you will need to send a morning email to  gp@crypto-kaizen.com and s.kapatel@crypto-kaizen.com so we know who is working on what. 
- The format to the morning email can be found in this [doc](https://github.com/sorrentum/sorrentum/blob/3d4662670deca1f97b78d6afed7d7954c6fc05c2/docs/General_rules_of_collaboration.md#morning-email). 
- With each morning email you will also add, the approx number of hours you will work on that day. 
- This will provide us an overview of what you are working on and how many hours you worked on that day.

**Comment by gpsaggese** [comment]
1) If you are on a scholarship, we need to report the hours worked
    - Pls keep a daily gsheet with the number of hours worked (after the day is over, since what happens in reality is always different from one's plan in the morning)
    - Pls send us at the end of the day the number of hours worked when you are done
    - We use an honor system, so we let you count the hours yourselves, but if the time that it takes is too long either there is something funny going on (and this is not cool) or one doesn't know what to do (and this is not good). This is the same you will face when you get a job ... so here is the first taste of the real-world.

2) As to sending the email to all@crypto-kaizen.com, we need time to tweak the permissions. For now pls send the emails to gp@crypto-kaizen.com, s.kapatel@crypto-kaizen.com, d.yachmenev@crypto-kaizen.com

3) Please do not reach one of us directly (e.g., email, TG). Use the appropriate forums (e.g., interns TG channel) so you get a faster response, and if you need to send us an email put gp@crypto-kaizen.com, s.kapatel@crypto-kaizen.com, d.yachmenev@crypto-kaizen.com

@samarth9008 can you pls add some of these tips on the documentation. Thx!

**Comment by samarth9008** [comment]
Please **Mark it as done** for your username when you send a morning email.

- [ ] @yiyunlei 
- [ ] @Vishnusaju24 
- [ ] @christyanthony 
- [ ] @Dylan-Celli 
- [ ] @Aniket-Parlikar 
- [ ] @KangmingL 
- [ ] @aryananwar

**Comment by Vishnusaju24** [comment]
@samarth9008 I am unable to see anything in the morning email format [doc](`https://github.com/sorrentum/sorrentum/blob/master/documentation/general/general.md`).
Can you kindly check this up once?

**Comment by gpsaggese** [comment]
@samarth9008 if it makes your life easier you can just post it once, and then mark it as done for one person when you think our interns have developed the habit of sending the email (and remind them to do it on the TG channel for who forgets).
