### ISSUE TITLE
Unit test `get_universe_versions()` for CCXT

### ISSUE THREAD

**Issue by DanilYachmenev** [sorrentum/sorrentum#311]
Follow-up from https://github.com/cryptokaizen/cmamp/pull/4512#discussion_r1219798883
Add 2 unit tests for `get_universe_versions()` from `im_v2/common/universe/universe.py` for CCXT 

- The tests should go to `im_v2/ccxt/universe/test/test_universe.py`
- See `TestGetUniverseVersions1` in `im_v2/mock1/universe/test/test_mock1_universe.py` for reference
    - See how it works, being inherited from `imvcountt.TestGetUniverseVersions1_TestCase`
    - See how the class is named ad do the same for CCXT
    - Add 2 tests: 1 for `mode = "trade"` and 1 for `mode = "download"`
  
This one should be quite easy so pls spend time researching the code and getting familiar with how the testing is done via test cases

Assigning @samarth9008 to re-distribute
FYI @PomazkinG

**Comment by DanilYachmenev** [comment]
@dhimuk are you going to proceed with the task? Could you provide ETA pls

**Comment by christyanthony** [comment]
@DanilYachmenev , @samarth9008 , I have seen how the code has been written for  TestGetUniverseVersions1 actually its is TestGetUniverse1 and how it is being inherited from imvcountt.TestGetUniverse1_TestCase.

So, in this issue I am expecting to write unit tests for get_universe_versions() which can be inherited from im_v2/common/universe/universe.py and the tests should be written for im_v2/ccxt/universe/test/test_universe.py. 

However, I couldn't find get_universe_versions() in im_v2/common/universe/universe.py and initially I thought it might be a slight name change like the example case and would be able to find it. But no matter what I couldn't see this exact method name or atleast its resemblance in the said path. There are only _get_universe_file_path(), _get_vendor_universe(), get_vendor_universe() in im_v2/common/universe/universe.py

Could you please let me know if my understanding is correct?

**Comment by DanilYachmenev** [comment]
@christyanthony 
check if your master is updated
pull it in case you dont find what I write below

- the file is `amp/im_v2/common/universe/universe.py`, line 74, function name is `get_universe_versions()`
- reference test class is `TestGetUniverseVersions1`, located at `amp/im_v2/mock1/universe/test/test_mock1_universe.py`
- you need to put similar test to `amp/im_v2/ccxt/universe/test/test_universe.py`
- `TestGetUniverse1` is related to a different function and not related to this task
- when you write comments anywhere (GitHub, Telegram, code) put code objects in backticks to improve readability

**Comment by christyanthony** [comment]
@DanilYachmenev 
I also had the same doubt about master being not up to date and did the git pull again after you said and checked for the function name in the file. But still couldn't find it.

And also if the function `get_universe_versions()` is available in the file `amp/im_v2/common/universe/universe.py`, I should at least be able to view the same in the remote repository but I cannot find it here as well. The same goes with the example file. The last update of both these files happened in last month. 

I just attached a screenshot of the file `/im_v2/common/universe/universe.py,` at line 74, 
![image](https://github.com/sorrentum/sorrentum/assets/125942809/7bb7c16b-4ef6-4108-a0b4-b5869f35f84e)

Please let me know if there is anything I am missing here.

**Comment by DanilYachmenev** [comment]
@christyanthony you're actually right, `sorrentum` repo does not have it
it happened because `sorrentum` and `cmamp` are not integrated yet, so some recently added functions are not present here yet

Sorry for directing to the yet non-existent direction
I will think of another task for you then

**Comment by christyanthony** [comment]
Wow. I was racking my brain worried about missing something. Thanks a lot for the clarification.

**Comment by gpsaggese** [comment]
Yes, I should merge the code for im_v2 today / tomorrow

**Comment by samarth9008** [comment]
@christyanthony It is available now.

**Comment by DanilYachmenev** [comment]
> @christyanthony It is available now.

I've assigned her to https://github.com/sorrentum/sorrentum/issues/362 yesterday so she's not losing time
lets move this one to @venkyt97 since he's expecting the first task

**Comment by samarth9008** [comment]
@DanilYachmenev 

Re-routing to @zli00185 as it has been 5 days and no progress yet by @venkyt97.

**Comment by gpsaggese** [comment]
Good job re-routing

**Comment by samarth9008** [comment]
https://github.com/sorrentum/sorrentum/blob/da1d569ed5ef73380ba56641248dcf6315a12262/im_v2/common/universe/universe.py#L74

**Comment by DanilYachmenev** [comment]
@zli00185 should be there https://github.com/sorrentum/sorrentum/blob/master/im_v2/common/universe/universe.py

try to do `> i docker_pull` on your master branch

**Comment by zli00185** [comment]
It display after doing `git merge master`. Start working on the task now.
