### ISSUE TITLE
On-Board Venkatesh Tripuraneni

### ISSUE THREAD

**Issue by samarth9008** [sorrentum/sorrentum#314]
Please follow this checklist. Post any errors you face in this issue.

- [x] Read [How to organize your work](https://github.com/sorrentum/sorrentum/blob/master/docs/How_to_organize_your_work.md)
- [x] Read [Quick start for developing](https://github.com/sorrentum/sorrentum/blob/master/docs/Quick_start_for_developing.md). Read through the [first section](https://github.com/sorrentum/sorrentum/blob/master/docs/Quick_start_for_developing.md#supporting-os) if you are using Windows
- [x] Make sure the [Docker dev container](https://github.com/sorrentum/sorrentum/blob/master/docs/Quick_start_for_developing.md#sorrentum-dev-docker-container-aka-dev-container-cmamp-container) works
- [ ] Make sure the unit tests run successfully
- [x] Read [Sorrentum Python coding style guide](https://github.com/sorrentum/sorrentum/blob/master/docs/Coding_Style_Guide.md)
- [ ] Get assigned a warm-up issue
- [ ] Learn about the [Morning Email](https://github.com/sorrentum/sorrentum/blob/master/docs/General_rules_of_collaboration.md#morning-email)
- [ ] How to do a [review](https://github.com/sorrentum/sorrentum/blob/master/docs/First_review_process.md)
- [ ] If you are graduating soon and you would like to get a part- / full-time job in one of the companies in the Sorrentum ecosystem reach out to GP at gp@sorrentum.org
- [x] Get up to speed in terms of the background knowledge for specific project
- For Web3 / Crypto : [README.md](https://github.com/sorrentum/sorrentum/blob/master/defi/README.md)
- For Arbitrage / Modeling: [From_zero_to_modeling.md](https://github.com/sorrentum/sorrentum/blob/master/docs/From_zero_to_modeling.md)

FYI @gpsaggese @DanilYachmenev

**Comment by samarth9008** [comment]
@venkyt97 Whats the update on the on-boarding task?

**Comment by venkyt97** [comment]
Hello @samarth9008 . I finished reading up the items mentioned in the checklist. Can you let me know what I else have to do to get a warm-up issue assigne?

**Comment by samarth9008** [comment]
We will assign a warm-up issue. Please mark it as done as you complete them in the checklist.

@DanilYachmenev We need one more warm-up issue.

**Comment by samarth9008** [comment]
@venkyt97 Warm-up issue is assigned to you. #311

**Comment by samarth9008** [comment]
Unresponsive so closing.
