### ISSUE TITLE
Code version is not in sync with the container version

### ISSUE THREAD

**Issue by chloeleilyy** [sorrentum/sorrentum#318]
I'm receiving this warning constantly, even after executing all of the commands:
- `invoke git_merge_master`
- `invoke docker_pull`
- `i docker_pull`
- `i git_merge_master`
```shell
-----------------------------------------------------------------------------
This code is not in sync with the container:
code_version='1.4.3' != container_version='1.4.0'
-----------------------------------------------------------------------------
You need to:
- merge origin/master into your branch with `invoke git_merge_master`
- pull the latest container with `invoke docker_pull`
```
<img width="812" alt="image" src="https://github.com/sorrentum/sorrentum/assets/42398651/19eb2e33-fc03-4f7f-830f-8638b2dab683">

**Comment by gpsaggese** [comment]
Good attention to details and situational awareness @yiyunlei.

You can safely ignore it. It's a known issue with our internal way of releasing containers. Adding container master @jsmerix but this is P1

**Comment by yiyunlei** [comment]
It's just annoying that this warning is highlighted in red, so I always mistake it for a bug when I run the tests.

**Comment by samarth9008** [comment]
@Er1-x Can you try debugging this issue. Lets come up with the reason of why this warning is generated and what can be done to resolve this and turn the warning into an error

**Comment by Er1-x** [comment]
> @Er1-x Can you try debugging this issue. Lets come up with the reason of why this warning is generated and what can be done to resolve this and turn the warning into an error

sure, I will start looking into this problem.

**Comment by samarth9008** [comment]
@Er1-x No need to work on it as not required

**Comment by Er1-x** [comment]
> @Er1-x No need to work on it as not required

Got it.

**Comment by Er1-x** [comment]
> @Er1-x No need to work on it as not required

Ok.

**Comment by gpsaggese** [comment]
Obsolete
