### ISSUE TITLE
Convert `dev_scripts/convert_docx_to_markdown.sh` script to Python

### ISSUE THREAD

**Issue by DanilYachmenev** [sorrentum/sorrentum#322]
Currently we have a script `dev_scripts/convert_docx_to_markdown.sh` that is used for conversion of `.docx` files to `.md` ([link](https://github.com/sorrentum/sorrentum/blob/master/docs/Documentation_about_guidelines.md#using-pandoc))

This script is becoming too complicated and it should be converted in Python

For this:
- Read scripts code style and refs ([link](https://github.com/sorrentum/sorrentum/blob/master/docs/Coding_Style_Guide.md#scripts))
    - Put a special attention to the scripts interfaces and especially to `_parse()` func and how params are introduced
- Create a `.py` stript that does the same job as `convert_docx_to_markdown.sh` and accepts
    - `--docx_file`
    - `--md_file`
- Update the documentation ([link](https://github.com/sorrentum/sorrentum/blob/master/docs/Documentation_about_guidelines.md#using-pandoc))

Assigning @samarth9008 to re-distribute and control

**Comment by Dylan-Celli** [comment]
Where can I find the ghi_show.py file to properly name my branch mentioned [here](https://github.com/sorrentum/sorrentum/blob/master/docs/Git_workflow_and_best_practices.md#workflow)? I could not find it on master.

**Comment by DanilYachmenev** [comment]
> Where can I find the ghi_show.py file to properly name my branch mentioned [here](https://github.com/sorrentum/sorrentum/blob/master/docs/Git_workflow_and_best_practices.md#workflow)? I could not find it on master.

this one is actually obsolete
the doc is under refinement currently
but for now just follow the pattern `SorrTask####_Task_name`

> Additionally is the in-file and out-file supposed to be hardcoded to the following files? `IN_FILE="docs/Epics_and_Sprints.docx"` `OUT_PREFIX="docs/Sprint_planning_process"`

Yes, these are placeholders
replace these 2 vals with what you need and just run the script

**Comment by Dylan-Celli** [comment]
There is a lot of perl regex in the original script, is it recommended that I use perl through python commands to regex everything? I currently plan to convert the perl regex into python regex, but I know that there are advantage to using perl.

**Comment by Dylan-Celli** [comment]
Would it be acceptable if I created two files for this? The first file would contain the code to create the docker image that installs `pandoc`. The second file would contain the python for the regex that cleans the artifacts left over from pandoc. Additionally, the second file would run and stop the docker image during it's runtime. I figured that it would be better for separating out different functionalities.

**Comment by samarth9008** [comment]
I think you can convert perl regex to python. Am I right @DanilYachmenev ?

No need to create two separate files. You can create a single python script which creates a docker container on the fly itself. Refer to this file.

https://github.com/sorrentum/sorrentum/blob/master/dev_scripts/encrypt_model.py

**Comment by Dylan-Celli** [comment]
To make sure that I understand the perl regex logic, could I get some feedback on this perl regex before I commit anything?
```
perl -pi -e 's/^(\s+)> /\1/g' $OUT_FILE

s/ = regex the following as a single line
/g = globally match the pattern repeatedly in the string
^ = start of the regex sequence starts with the following
( ) = group the following
\s+ = match 1 or more white space characters
\1 = backreference to the first cature group or buffer

-e = compiles one line of perl script (the regex in the quotes)
-i = specifies that the operation must be done in place (it does this by creating an output file with the same name as the input file)
-p = causes the command to iterate through the entire file
```
Therefor this command iterates through the entire file one line at time and finds all lines that start with 1 or more white spaces, but only takes in as input the first occurrence of a line that starts with more than one whitespace.

The corresponding pythonic regex would be 'x = re.search("^(\s+)", infile)`

**Comment by gpsaggese** [comment]
1) Let's keep the scripts into one.  The current approach is to have the user run a command ignoring the Docker layer

2) I would actually argue against converting perl one liner to Python for a few non-obvious reasons:
     - This is kind of a throwaway script, once we are done with converting Gdocs this script is useless so any work spent in making it better is not really amortized over time
     - perl one-liner are easy to test one-by-one via command line
     - converting perl to Python can introduce subtle bugs that we won't catch since we don't have and not want unit test

Given all this I would keep the perl stuff into `hsystem.system` commands and use Python just to make the structure better since a shell script is horrible.

IMO the translation should take 1 day (after @Dylan-Celli understands how we write Python scripts), if it takes longer it might not be worth it.

Also @yiyunlei is still changing the code and this could create pains to maintain two scripts.
In any case my spider sense is telling me that this bug is going to be a pain in the neck. I would either pause it or pass it to @yiyunlei

**Comment by DanilYachmenev** [comment]
@Dylan-Celli re-assigned the task to @yiyunlei since she progressed on this one and it would contribute to the efficiency

Pls focus on your documentation task today
we will assign another coding task to you as well

**Comment by yiyunlei** [comment]
@Dylan-Celli
How about you commit the code you've already completed(a draft is okay)? This way, I can add code based on your work, without spending time on duplicative efforts.

**Comment by Dylan-Celli** [comment]
> @Dylan-Celli How about you commit the code you've already completed(a draft is okay)? This way, I can add code based on your work, without spending time on duplicative efforts.

Hello @yiyunlei, I did not get to convert any of the perl regex to python so I really only have some skeleton code written. If you still want I can commit it for you but I am not sure how useful it will be to you. There is also some skeleton code written in python at the bottom of the `dev_scripts/convert_docx_to_markdown.sh` file

**Comment by yiyunlei** [comment]
@Dylan-Celli Thanks. I will use the skeleton code in the `convert_docx_to_markdown.sh`.

**Comment by yiyunlei** [comment]
@samarth9008
I have gone through these examples about creating a Docker container and now roughly know how to write code.
- `dev_scripts/encrypt_model.py`
- `dev_scripts/lint_md.sh`
- `dev_scripts/convert_docx_to_markdown.sh`

Do you have any other sources or docs about it that I can read? I hope to gain a better understanding of this.

**Comment by samarth9008** [comment]
I think these are enough.
