### ISSUE TITLE
On-board Ishan Tripathi

### ISSUE THREAD

**Issue by samarth9008** [sorrentum/sorrentum#323]
Please follow this checklist. Post any errors you face in this issue.

- [x] Read [How to organize your work](https://github.com/sorrentum/sorrentum/blob/master/docs/How_to_organize_your_work.md)
- [x] Read [Quick start for developing](https://github.com/sorrentum/sorrentum/blob/master/docs/Quick_start_for_developing.md). Read through the [first section](https://github.com/sorrentum/sorrentum/blob/master/docs/Quick_start_for_developing.md#supporting-os) if you are using Windows
- [x] Make sure the [Docker dev container](https://github.com/sorrentum/sorrentum/blob/master/docs/Quick_start_for_developing.md#sorrentum-dev-docker-container-aka-dev-container-cmamp-container) works
- [ ] Make sure the unit tests run successfully
- [x] Read [Sorrentum Python coding style guide](https://github.com/sorrentum/sorrentum/blob/master/docs/Coding_Style_Guide.md)
- [ ] Get assigned a warm-up issue
- [x] Learn about the [Morning Email](https://github.com/sorrentum/sorrentum/blob/master/docs/General_rules_of_collaboration.md#morning-email)
- [ ] How to do a [review](https://github.com/sorrentum/sorrentum/blob/master/docs/First_review_process.md)
- [x] If you are graduating soon and you would like to get a part- / full-time job in one of the companies in the Sorrentum ecosystem reach out to GP at gp@sorrentum.org
- [x] Get up to speed in terms of the background knowledge for specific project
- For Web3 / Crypto : [README.md](https://github.com/sorrentum/sorrentum/blob/master/defi/README.md)
- For Arbitrage / Modeling: [From_zero_to_modeling.md](https://github.com/sorrentum/sorrentum/blob/master/docs/From_zero_to_modeling.md)

FYI @gpsaggese @DanilYachmenev

**Comment by ishant513** [comment]
Sorry, had some minor delays but will be done by EOD

**Comment by samarth9008** [comment]
> Sorry, had some minor delays but will be done by EOD

Mark each item as done as you do it.

**Comment by ishant513** [comment]
Hi Samarth, is it imperative that I am on the most recent version of docker? My laptop is old and I can't install the most recent macOS needed to download the newest edition of docker.

**Comment by samarth9008** [comment]
I am not sure about it. You can share you output after building the environment and we can tell you if its right or not.

**Comment by gpsaggese** [comment]
You can try to use an older version, but if it doesn't work we won't be able to help you. Unfortunately we don't have enough resources to deal with different environments and laptops. For this reason we use Docker.

**Comment by ishant513** [comment]
I see, will try with the older version for now and if issues occur I will work them out as they come

**Comment by samarth9008** [comment]
Whats the update with your issues?

**Comment by samarth9008** [comment]
Closing as dropped.
