### ISSUE TITLE
Convert Type Hints gDoc to Markdown

### ISSUE THREAD

**Issue by samarth9008** [sorrentum/sorrentum#328]
- We need to convert a [Gdoc](https://docs.google.com/document/d/1SuT4NHkpLxTzbJrD6A59bJQUyXCLAx0F9LUDzKYkOg4/edit#heading=h.2zulxba5bdto) of Python - Type hints to Markdown
- Instructions on how to convert Gdocs to Markdown are [here](https://github.com/sorrentum/sorrentum/blob/master/docs/Documentation_about_guidelines.md#gdocs---markdown)
- Read about the [First Review Process](https://github.com/sorrentum/sorrentum/blob/master/docs/First_review_process.md)
- Lint the markdown file using the [linter](https://github.com/sorrentum/sorrentum/blob/master/dev_scripts/lint_md.sh)
- PR example is https://github.com/sorrentum/sorrentum/pull/198

FYI @DanilYachmenev

**Comment by hhxjqm** [comment]
@samarth9008 
I don't know how to do it, but my commits show up in another place

https://github.com/sorrentum/sorrentum/pull/334

**Comment by samarth9008** [comment]
What do you mean by your commits show up in another place?

**Comment by hhxjqm** [comment]
I mean in #334

**Comment by hhxjqm** [comment]
#335
