### ISSUE TITLE
Convert Code Review gDoc to Markdown

### ISSUE THREAD

**Issue by samarth9008** [sorrentum/sorrentum#332]
- We need to convert a [Gdoc](https://docs.google.com/document/d/1DrulKZyvgdHPcXxblkO-uBtu_zTxD-rp476u1QPzGGc/edit#heading=h.6da73fq05ij1) of Code Review to Markdown
- Instructions on how to convert Gdocs to Markdown are [here](https://github.com/sorrentum/sorrentum/blob/master/docs/Documentation_about_guidelines.md#gdocs---markdown)
- Read about the [First Review Process](https://github.com/sorrentum/sorrentum/blob/master/docs/First_review_process.md)
- Lint the markdown file using the [linter](https://github.com/sorrentum/sorrentum/blob/master/dev_scripts/lint_md.sh)
- PR example is https://github.com/sorrentum/sorrentum/pull/198

FYI @DanilYachmenev

**Comment by zli00185** [comment]
Could you grant me access to the Gdoc file?

**Comment by samarth9008** [comment]
Done.

**Comment by zli00185** [comment]
Question:
After I Lint the markdown file, this is the error code it shows, I am not sure what to next.
<img width="1043" alt="Screen Shot 2023-06-22 at 3 57 09 AM" src="https://github.com/sorrentum/sorrentum/assets/112597810/010fd80d-678f-4672-91ed-d779eb7d99ad">

**Comment by samarth9008** [comment]
Try installing `realpath`.

Although I am not sure how it works on MacOs but online resources suggest something like this to install. 

`brew install coreutils`. You are free to explore on your owm.

**Comment by zli00185** [comment]
Question:
1. How to use the linter to check code for syntax errors, style violations, and other issues? The command runs successfully with the markdown file but I couldn't find any feedback of what I should modify. 
2. In this [section of the document](https://github.com/sorrentum/sorrentum/blob/master/docs/Documentation_about_guidelines.md#cleaning-up-converted-markdown), I am not sure what this parts refers to. Is this what we need to remove from markdown file? 
<img width="365" alt="Screen Shot 2023-06-23 at 3 39 47 AM" src="https://github.com/sorrentum/sorrentum/assets/112597810/56cb2256-9aa4-4b3a-8be4-80673e49467d">

**Comment by samarth9008** [comment]
The thing is the the tool does not convert the doc with complete correct format. You have to use the tool and than format it manually by comparing it with the word doc and other markdown files in the repo. After doing that you run the linter provided in specs.

**Comment by zli00185** [comment]
Question:
1. Will linter provide information of whether the format is appropriate or not? Or it just change the file?
2. How do I know linter messes up the text? 
3. One thing I need to do manually is deleting the empty line, but there md file where some empty lines are kept, and this [doc](https://github.com/sorrentum/sorrentum/blob/master/docs/First_review_process.md) doesn't mention anything about it. How do I further determine the part that needs to be modified?

**Comment by samarth9008** [comment]
> Question:
> 
> 1. Will linter provide information of whether the format is appropriate or not? Or it just change the file?

It just lints the file.

> 2. How do I know linter messes up the text?

You can check manually but chances are low.

> 3. One thing I need to do manually is deleting the empty line, but there md file where some empty lines are kept, and this [doc](https://github.com/sorrentum/sorrentum/blob/master/docs/First_review_process.md) doesn't mention anything about it. How do I further determine the part that needs to be modified?

Which linter are you running? I do not get your last question.

**Comment by zli00185** [comment]
> Which linter are you running? I do not get your last question.

The linter I run was provide from this [file](https://github.com/sorrentum/sorrentum/blob/master/dev_scripts/lint_md.sh) with command "> dev_scripts/lint_md.sh file1.md ... fileN.md". That question was not asking about the linter but more about a specific rule of manually editing the markdown file. I was confused what else need to be modified. Empty line is one thing, but there are empty lines not getting delete in the example md file. 

>2. In this [section of the document](https://github.com/sorrentum/sorrentum/blob/master/docs/Documentation_about_guidelines.md#cleaning-up-converted-markdown), I am not sure what this parts refers to. Is this what we need to remove from markdown file?
> <img width="365" alt="Screen Shot 2023-06-23 at 3 39 47 AM" src="https://github.com/sorrentum/sorrentum/assets/112597810/8aee3adf-2850-4545-9acd-f7e3c63474ed">

This part of the intruction only mentions deleting empty line, and I don't understand what the following code is about.

**Comment by samarth9008** [comment]
While editing manually, the best way to begin is to check the code of other already created markdown files. Compare your code and formatting with it.

Remove empty lines and format it manually.

**Comment by zli00185** [comment]
Question:
1. Do I need to push anything except for the Markdown file, for example the linter_output.txt?
2. Other md file have a  and  section, where  is like a short menu of the topic. Do I also need to summarize that manually?

**Comment by samarth9008** [comment]
> Question:
> 
> 1. Do I need to push anything except for the Markdown file, for example the linter_output.txt?

No. Just the md file.

> 2. Other md file have a  and  section, where  is like a short menu of the topic. Do I also need to summarize that manually?

I did not get it. Could you please repeat?

**Comment by zli00185** [comment]
> I did not get it. Could you please repeat?

Every other md file have a section with comment \<!--ts--\>, where the information following are a short menu like this:
<img width="641" alt="Screen Shot 2023-06-24 at 12 07 47 AM" src="https://github.com/sorrentum/sorrentum/assets/112597810/7cf463d7-6dea-4a01-bc98-f0b59a9deb20">

I wonder whether this part need to be written for the submitted file.

**Comment by samarth9008** [comment]
You can refer the linter file to understand why they are required and it will be required in your file too to generate TOH

**Comment by zli00185** [comment]
I found a md file called "code_review.md" which contain completely same information with the gdoc that I am editing. Do I still need to make a copy of the same information?

**Comment by samarth9008** [comment]
Can you pls tell which info is common?

**Comment by zli00185** [comment]
> Can you pls tell which info is common?

Almost all the information besides the menu are same. The short menu contain some errors where the sections it points to doesn't exist. I could fix that.

**Comment by samarth9008** [comment]
https://docs.google.com/document/d/1DrulKZyvgdHPcXxblkO-uBtu_zTxD-rp476u1QPzGGc/edit#heading=h.jjtmulc9yvjb

Are you referring to this doc?

**Comment by zli00185** [comment]
> https://docs.google.com/document/d/1DrulKZyvgdHPcXxblkO-uBtu_zTxD-rp476u1QPzGGc/edit#heading=h.jjtmulc9yvjb

Yes

**Comment by samarth9008** [comment]
Where is the file "code_review.md" located?

**Comment by zli00185** [comment]
> Where is the file "code_review.md" located?

documentation/general/code_review.md

**Comment by DanilYachmenev** [comment]
> What should we do @DanilYachmenev ?
> 
> As a reference, The doc which @zli00185 is editing is already present in `documentation/general/code_review.md`.

good finding, usually files in this dir are really outdated but in this case info seems really similar

anyways, we're not going to use `documentation` dir for public publishing
you can use it for formatting and reference

overall, follow the process as it is suggested, good exercise
and well, TOC now should be created using `lint_md` script, so this definitely needs to be changed

**Comment by zli00185** [comment]
I just ran lint_md.sh with my md file and this is what I get:
<img width="925" alt="Screen Shot 2023-06-24 at 1 09 37 AM" src="https://github.com/sorrentum/sorrentum/assets/112597810/8d64bcf1-5cee-4f7e-a555-6be6304175f3">

I am not sure how it works since I didn't see any content being generated

**Comment by samarth9008** [comment]
Did you read the content on the top of the lint_md.sh file?

**Comment by samarth9008** [comment]
Remove markdown from your file name.
