### ISSUE TITLE
On-board Alejandro Ballesteros

### ISSUE THREAD

**Issue by samarth9008** [sorrentum/sorrentum#333]
Please follow this checklist. Post any errors you face in this issue.

- [x] Read [How to organize your work](https://github.com/sorrentum/sorrentum/blob/master/docs/How_to_organize_your_work.md)
- [x] Read [Quick start for developing](https://github.com/sorrentum/sorrentum/blob/master/docs/Quick_start_for_developing.md). Read through the [first section](https://github.com/sorrentum/sorrentum/blob/master/docs/Quick_start_for_developing.md#supporting-os) if you are using Windows
- [x] Make sure the [Docker dev container](https://github.com/sorrentum/sorrentum/blob/master/docs/Quick_start_for_developing.md#sorrentum-dev-docker-container-aka-dev-container-cmamp-container) works
- [x] Make sure the unit tests run successfully
- [x] Read [Sorrentum Python coding style guide](https://github.com/sorrentum/sorrentum/blob/master/docs/Coding_Style_Guide.md)
- [x] Get assigned a warm-up issue
- [x] Learn about the [Morning Email](https://github.com/sorrentum/sorrentum/blob/master/docs/General_rules_of_collaboration.md#morning-email)
- [x] How to do a [review](https://github.com/sorrentum/sorrentum/blob/master/docs/First_review_process.md)
- [x] If you are graduating soon and you would like to get a part- / full-time job in one of the companies in the Sorrentum ecosystem reach out to GP at gp@sorrentum.org
- [x] Get up to speed in terms of the background knowledge for specific project
- For Web3 / Crypto : [README.md](https://github.com/sorrentum/sorrentum/blob/master/defi/README.md)
- For Arbitrage / Modeling: [From_zero_to_modeling.md](https://github.com/sorrentum/sorrentum/blob/master/docs/From_zero_to_modeling.md)

FYI @gpsaggese @DanilYachmenev

**Comment by alejandroBallesterosC** [comment]
**Seeing warning even after invoking docker_pull,**

-----------------------------------------------------------------------------
This code is not in sync with the container:
code_version='1.4.3' != container_version='1.4.0'
-----------------------------------------------------------------------------
You need to:
- merge origin/master into your branch with `invoke git_merge_master`
- pull the latest container with `invoke docker_pull`
## docker_pull:

**Comment by alejandroBallesterosC** [comment]
seeing zsh: command: i not found
when running i docker_jupyter

**Comment by gpsaggese** [comment]
1) Yes the warning is a known problem from our release / deploying process (I think we've filed a bug few days ago). Maybe we can make it less intimidating than glaring red.

2) We support only bash. No shell wars please :-)
If you are using Mac you can make it default, the switch from bash to zsh default was a recent change from Apple, I believe

**Comment by gpsaggese** [comment]
If you are a tmux lover (if not, you should become) you can use `dev_scripts/tmux.sh` which is the way we tend to run on the dev server
