### ISSUE TITLE
Fix `gh_issue_title` for Sorrentum

### ISSUE THREAD

**Issue by DanilYachmenev** [sorrentum/sorrentum#341]
Follow-up from https://github.com/sorrentum/sorrentum/pull/324#discussion_r1227361105

Currently, if we call `> i gh_issue_title {issue number}`  at `sorrentum` it would give the same output as for `cmamp`:
```
> i gh_issue_title 319
```
Logs:
```
...
CmTask319_Refine_convert_gdoc_to_markdown.sh: https://github.com/sorrentum/sorrentum/issues/319
```

when instead it should be 
```
SorrTask319_Refine_convert_gdoc_to_markdown.sh: https://github.com/sorrentum/sorrentum/issues/319
```

So `CmTask...` -> `SorrTask...`

FYI @gpsaggese @samarth9008 

Assigned to myself as P1 for now but can do in the coming sprint or re-direct if needed

**Comment by LibertasSpZ** [comment]
Hello @DanilYachmenev , on my end this issue seems already fixed before. When I run `i git_issue_title 319` in my local `sorrentum1` directory it does produce the desired correct output:
`# Copied to system clipboard:
SorrTask319_Refine_convert_gdoc_to_markdown.sh: https://github.com/sorrentum/sorrentum/issues/319`

-----------------

I did some tracing and found `gh_issue_title` was defined in `helpers/lib_tasks_gh.py`. In the current implementation the function eventually calls:

    1: `hgit.get_repo_name(hgit.get_repo_full_name_from_dirname(".",...))` to obtain a `repo_short_name` of the *current* repo, and
    2: `hgit.get_task_prefix_from_repo_short_name(repo_short_name)` to add the prefix, using current `repo_short_name` from 1.

    Since *current* repo name is `Sorrentum*` rather than `Cmamp*`, it seems reasonable to get `Sorr` instead of `Cm` as task prefix.

     Please let me know if I missed something. Thank you!

**Comment by DanilYachmenev** [comment]
@LibertasSpZ, you're right! I've done the call by myself now and it worked correctly
So it seems like the issue has been resolved by some recent changes indeed

Very nice report, thx!
What could be useful here now is to add some info to `gh_issue_title` docstring for other users.
We need:
- Mention, that before running the invoke one must check the login status on GH by running `gh auth status`
- If a user is not logged in GH, he needs to auth using personal token. Add a reference to the instructions in `Configure gh` [section](https://github.com/cryptokaizen/cmamp/blob/master/docs/Development_Set_up.md#configure-gh) of the Development set-up doc 

So yes, just a docstring update here
Meanwhile I'll assign you to a different task where GP has asked for your involvement

**Comment by LibertasSpZ** [comment]
@DanilYachmenev thanks for your comment, Danil. Will do, but could you provide the correct link to the `Configure gh` section? I tried `grep -r Configure docs` but only found two instances, both occurring inside a comment.

**Comment by DanilYachmenev** [comment]
> @DanilYachmenev thanks for your comment, Danil. Will do, but could you provide the correct link to the `Configure gh` section? It's broken here, and I tried `grep -r Configure docs` but only found two instances, both occurring inside a comment.

ohs, it is at another repo, sorry
nevermind then, just add a part about `gh auth status`, I'll do the rest
