### ISSUE TITLE
Improve Convert Gdoc to Markdown script and documentation

### ISSUE THREAD

**Issue by yiyunlei** [sorrentum/sorrentum#348]
While I was working on #257, I found some Perl regex replacements in the script `convert_docx_to_markdown.sh` don't work, and the script also lacks some necessary regex replacements. Therefore, I will try to improve the script.

I also did more steps than what was described in the doc [Convert between Gdocs and Markdown](https://github.com/sorrentum/sorrentum/blob/master/docs/Documentation_about_guidelines.md#convert-between-gdocs-and-markdown) to finish the conversion task, so I will add some necessary content to the doc.

I noticed that issue #322 is converting the script to Python, I think our work is not in conflict. This is because I will more focus on improving the regex replacements in the script, which can be easily incorporated into Python; I will add instructions about what needs to be done after running the script/python file, to the documentation.

The main goal is to save some time for future conversion tasks, both for assignees and reviewers.

FYI @gpsaggese @DanilYachmenev @samarth9008

**Comment by DanilYachmenev** [comment]
np
however, could you extrapolate more on what exactly does not work in the script?
like put specific code pieces and probably error logs if there are some
so we are on the same page

And another suggestion
If the changes are not very crucial, you can do it right in the PR related to Gdoc conversion
`.sh` script is going to be deprecated anyways so do not spend too much time on refining the script that is sentenced to deprecation

**Comment by yiyunlei** [comment]
You can check my commit in the branch [SorrTask348](https://github.com/sorrentum/sorrentum/tree/SorrTask348_Improve_Gdoc_markdown_conversion_script_and_doc), which is the markdown file I got after just running the convert script.
There are many artifacts in this markdown that need to be removed.

- Example 1

    For `line 1, 13, 15` in `Tools_Docker_Test.md`
    ```
    # \# Introduction
    
    # \# Concepts
    ## \#\# Docker image
    ```
    They should be:
    
    ```
    # Introduction
    # Concepts
    ## Docker image
    ```
    And they are expected to be replaced correctly by the `line 88` in `Convert_docx_to_markdown.sh`: 
(Actually, this is a wrong regex replacement)
    ```
    # "# \# Running PyCharm remotely" -> "# Running PyCharm remotely"
    perl -pi -e 's/# \\#+ /# /g' $OUT_FILE
    ```
    
    Same for this one:
    ```
    ## **\#\# amp / cmamp container**
    ```
    ```
    # **\# Connecting via VNC**
    perl -pi -e 's/^\*\*\\#+ /**/g' $OUT_FILE
    ```
- Example 2
    Line 1835 in `Tools_Docker_Test.md`:
    ```
     - We can skip code based dynamically on a \`try ... except ImportModule\` to
        check what packages are present
    ```
    It should be 
    ```
    - We can skip code based dynamically on a `try ... except ImportModule` to
        check what packages are present
    ```
    The corresponding Perl regex code `Line 91`: 
    ```
    # \`nid\` -> `nid`
    perl -pi -e "s/\\\\\`(.*?)\\\\\`/\`\1\`/g" $OUT_FILE
    ```

- Also, the script misses regex replacements for
    ```
    ``\`    --->     ```
    ```
    - This is very important for code block.

There are still other issues in the converted markdown.
These small formatting issues can be fixed manually, but they will need a lot of time to fix and check, especially for long docs/markdowns.
So I think there are a lot of improvements that can be done for the regex replacements, and it won't be a waste of time since the new Python will also need these regex replacements.
I can also help add these replacements to the new Python file if needed.

**Comment by yiyunlei** [comment]
Oops! And the link formatting regex replacement also doesn't work, the comments in PR #347 remind me of this.
```
# [[https://plugins.jetbrains.com/plugin/7234-wrap-to-column]{.underline}](https://plugins.jetbrains.com/plugin/7234-wrap-to-column)
perl -pi -e 's/\[\[(._)\](\{\.underline\})?]\((._)\)/[\1](\3)/g' $OUT_FILE
```

**Comment by yiyunlei** [comment]
Also, I noticed that other assignees are doing redundant work due to the same issues. [#338 comment](https://github.com/sorrentum/sorrentum/pull/338#issuecomment-1601887500)

**Comment by DanilYachmenev** [comment]
Solid, very nice observation and great proactive approach!

Lets do it this way then
Since you've already figured out a lot about the script, I assign #322 to you
Pls read GP comments there and lets do a python script with your suggestions there right away
