### ISSUE TITLE
Unit test `dassert_increasing_index`

### ISSUE THREAD

**Issue by DanilYachmenev** [sorrentum/sorrentum#353]
Add unit tests for `dassert_increasing_index()` from `helpers/hpandas.py`

Before implementing read Unit tests [doc](https://github.com/sorrentum/sorrentum/blob/master/docs/Unit_tests.md) carefully

Lets add 3 test methods in a test case:
- index is obviously not increasing at a certain data points
- index is not monotonically increasing (e.g duplicated)
- index is correct and assert passes

See how testing of asserts is implemented in the corresponding test file and at `helpers/test/test_dbg.py`

Assigning @samarth9008 to re-distribute

**Comment by zli00185** [comment]
Hi,
After the system update of my Mac, the invoke command is not working after activating the thin environment. I have tried "pip install invoke" and the error shows "WARNING: Can't find s3fs: continuing." 

I just ran the command "source dev_scripts/client_setup/build.sh" to re-build the environment. But the it has kept running for almost 30 minutes, which is still not done yet. I am not sure what to do under this scenario.

**Comment by samarth9008** [comment]
Can you share more details? like the logs, commands you used and as much as you can.

**Comment by zli00185** [comment]
I was trying to use "i docker_jupyter" and it worked well before the system update. After the updating it shows "zsh: command not found: invoke". 

The environment building command just crash for unknown reason. Now I couldn't even open the terminal, the error shows "The terminal process failed to launch: Starting directory (cwd) "/Users/leosmacbook/Desktop/Sorretum_Intern1" does not exist."

**Comment by samarth9008** [comment]
https://github.com/sorrentum/sorrentum/issues/333#issuecomment-1594943710

**Comment by zli00185** [comment]
When I run `i docker_jupyter`  inside the python environment
the error shows 
`WARNING: Can't find s3fs: continuing
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/invoke", line 8, in <module>
    sys.exit(program.run())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/invoke/program.py", line 387, in run
    self.parse_collection()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/invoke/program.py", line 479, in parse_collection
    self.load_collection()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/invoke/program.py", line 716, in load_collection
    module, parent = loader.load(coll_name)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/invoke/loader.py", line 91, in load
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/leosmacbook/Desktop/Sorretum_Intern/tasks.py", line 10, in <module>
    from helpers.lib_tasks import (  # This is not an invoke target.
  File "/Users/leosmacbook/Desktop/Sorretum_Intern/helpers/lib_tasks.py", line 15, in <module>
    from helpers.lib_tasks_docker_release import *  # isort:skip  # noqa: F401,F403 # pylint: disable=unused-import,unused-wildcard-import,wildcard-import
  File "/Users/leosmacbook/Desktop/Sorretum_Intern/helpers/lib_tasks_docker_release.py", line 18, in <module>
    import helpers.hs3 as hs3
  File "/Users/leosmacbook/Desktop/Sorretum_Intern/helpers/hs3.py", line 49, in <module>
    AwsProfile = Optional[Union[str, s3fs.core.S3FileSystem]]
NameError: name 's3fs' is not defined`

**Comment by samarth9008** [comment]
Did you try building the environment again? The reason is in the error logs the path is `/Users/leosmacbook/Desktop/Sorretum_Intern`, however previously you mentioned the path was `"/Users/leosmacbook/Desktop/Sorretum_Intern1" `

**Comment by zli00185** [comment]
I did. The terminal crash during the middle of the building process. I tried it twice and the crash still happens

**Comment by samarth9008** [comment]
Without logs its hard to debug. Try doing everything from beginning. With cloning a new repo and build new envirnoment.

**Comment by zli00185** [comment]
Just cloned a new repo and have the same issue when build the environment. It shows the same error as this:

> 

> I did. The terminal crash during the middle of the building process. I tried it twice and the crash still happens. Here is the error codes shows before crashing: `ERROR: Cannot install -r dev_scripts/client_setup/requirements.txt (line 2) because these package versions have conflicting dependencies.`
> 
> `The conflict is caused by: docker-compose 1.29.2 depends on dockerpty<1 and >=0.4.1 docker-compose 1.29.1 depends on dockerpty<1 and >=0.4.1 docker-compose 1.29.0 depends on dockerpty<1 and >=0.4.1` `To fix this you could try to:` `1. loosen the range of package versions you've specified` `2. remove package versions to allow pip attempt to solve the dependency conflict`
> 
> `ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts`

**Comment by samarth9008** [comment]
Some issues with docker in your system. You can try installing docker again.

**Comment by zli00185** [comment]
Still having the same issue after reinstalling and delete all the container in the docker.

**Comment by samarth9008** [comment]
Not just containers. Install docker again.

**Comment by zli00185** [comment]
Yes, I delete the original docker, reinstalled it, and same error code shows again during building environment.

**Comment by zli00185** [comment]
Issue fixed
**Cause of the issue:** 
Mac system update (12.4 -> 13.4.1) might change or rename the path, which causes the original environment change.
**Solution:** 
Install Miniconda from [here](https://docs.conda.io/en/main/miniconda.html) and activate python environment with command `conda activate`. Redo the environment building process with command `source dev_scripts/client_setup/build.sh`. The file name has to be end with a digit otherwise could not start the Jupyter server.
