### ISSUE TITLE
Unit test `tee` param for `hsystem.system()`

### ISSUE THREAD

**Issue by DanilYachmenev** [sorrentum/sorrentum#355]
Add unit tests for `system()` from `helpers/hsystem.py`

Before implementing read Unit tests [doc](https://github.com/sorrentum/sorrentum/blob/master/docs/Unit_tests.md) carefully

We need to add a test to `Test_system1` in `helpers/test/test_system_interaction.py` that runs `.system()` on a failing cmd with `--tee` switch enabled.

the idea is to test that if a failing command is executed with the `—tee` switch the cmd will fail (it had not been the case until we added the `PIPESTATUS` thing)
See how failing is being tested at `test7`

Assigning @samarth9008 to re-distribute
FYI @PomazkinG

**Comment by Dylan-Celli** [comment]
Also can I include the tests where I pass a string, an int, and a float in the same method or should I put each in a different method?

**Comment by DanilYachmenev** [comment]
> Also can I include the tests where I pass a string, an int, and a float in the same method or should I put each in a different method? 

Not sure what you mean, extrapolate

> Additionally could someone explain the naming convention behind the variable `act = str(cm.exception)` in `test7`? Just so I can be consistent with the naming convention.

`act` is for "actual" function outcome that should be compared with expected. Better name your actual as `actual`

**Comment by DanilYachmenev** [comment]
> Is this cause for concern?

not sure personally
@samarth9008 do you know anything bout it?

**Comment by samarth9008** [comment]
I am not sure. I think even I got it sometime.

**Comment by Dylan-Celli** [comment]
> Not sure what you mean, extrapolate

I am creating a unit test to verify that if the `-tee` flag takes in a non-valid, non-boolean, value that the user gets an error thrown on the CLI. I want to create tests for incorrectly inputting strings, ints, and float values. I wanted to know if these tests should all have their own unit test method or if I can put them all into the same unit test method.

**Comment by Dylan-Celli** [comment]
Hello I am running into trouble with the following command

`i run_fast_tests --coverage -p /home/dcelli/src/sorrentum1/helpers/test/test_system_interaction.py::Test_system1::test8`

When I run it I get the following error
```
ERROR: file or directory not found: /home/dcelli/src/sorrentum1/helpers/test/test_system_interaction.py::Test_system1::test8
ERROR: 4
```
But when I run the pytest command myself from the bash terminal the test is able to find the file and run normally

**Comment by DanilYachmenev** [comment]
> I am creating a unit test to verify that if the `-tee` flag takes in a non-valid, non-boolean, value that the user gets an error thrown on the CLI. I want to create tests for incorrectly inputting strings, ints, and float values. I wanted to know if these tests should all have their own unit test method or if I can put them all into the same unit test method.

the type does not really matter IMO
just pass a command to `system()` that should fail
and inside `system()` do `tee=True`
expected behavior is a failure and you should capture it with the unit test

**Comment by DanilYachmenev** [comment]
> But when I run the pytest command myself from the bash terminal the test is able to find the file and run normally

not sure about `i run_fast_tests --coverage -p` yet, will check a bit later
but why do you need it overall?

running specific `pytest` should be run only from bash and my expectation that it should be enough for you now

**Comment by gpsaggese** [comment]
You can ignore the error from Git, but I'll file a bug to remove the issues.

**Comment by Dylan-Celli** [comment]
> but why do you need it overall?

Using the `i run_fast_tests --coverage -p` is one of the ways in which the `Unit tests.py` doc described how to run the unit tests

**Comment by gpsaggese** [comment]
You can / should run with `--coverage` when you want to see the coverage. To test functionality you can skip that.

**Comment by Dylan-Celli** [comment]
Also, when I run the `pytest /home/dcelli/src/sorrentum1/helpers/test/test_system_interaction.py::Test_system1::test8` I get the following error. I tried running other tests with `pytest` as well with the same result. I would think it is something wrong with the environment but the thin shell is up and running properly so I am not sure where the issue lies. I looked into the error and most sources said that I need to change the python version to a version that accepts the config option.

```
FAILED helpers/test/test_system_interaction.py::Test_system2::test_get_user_name - pandas._config.config.OptionError: No such keys(s): 'display.column_space'
```

**Comment by samarth9008** [comment]
Are you running it inside the docker container?

**Comment by gpsaggese** [comment]
You need to report more context. Are you running inside `i docker_bash`? You should

@samarth9008 @DanilYachmenev we should have a step on the on-boarding that say "run `i run_fast_tests` to make sure the tests and your env is properly configured"
The problem is now that people get failures since we don't have the testlist that @alejandroBallesterosC is working on.

**Comment by Dylan-Celli** [comment]
I got the pytest to run on my unit test but I have a question about how extensively I am supposed to test because I believe that I may have found an edge case. The following command fails as expected with a `AssertionError`
```
hsystem.system("ls this_should_fail", tee=True)
```
However if an output file is specified like so
```
hsystem.system("ls this_should_fail", tee=True, output_file="tmp_hsystem_Test_system1_test8_output.txt")
```
No errors are thrown. Is this second case intentional functionality, since this file is supposed to have the redirected output, or should the code be throwing an error that is expected to be caught?

If the first case is the only scenario that this issue needs to test then I can be finished with this issue, but if I should create more expansive testing by specifying other parameters the issue will take a bit longer.

**Comment by DanilYachmenev** [comment]
@Dylan-Celli  good job thinking bout corner cases

- Failure of usage of `tee` without log file specified is a correct behaviour since log file is a prerequisite for it, so yes, lets add a test for it, good notice
- However, the second case you describe is actually surprising
I ran it in the notebook in the way you put it and it broke on my end
<img width="1037" alt="Снимок экрана 2023-07-03 в 02 07 47" src="https://github.com/sorrentum/sorrentum/assets/31514660/0729026b-2bbc-4b8d-bc96-19a0b438c991">
Please, double check yourself
The expected behaviour in this case is a run failure and this also should be tested


- Also your comment pointed me to another important test case that should be tested
We need to test the case when `tee=True`, log file is passed and `abort_on_error=False`
In this case the command should pass
but please, check its output using `rc`, that should be equal to `2` in this case
<img width="1027" alt="Снимок экрана 2023-07-03 в 02 08 02" src="https://github.com/sorrentum/sorrentum/assets/31514660/f4aa4cb0-87e9-4cb5-a178-af7bf332e207">

In this case we should also use a scratch dir to test the content of your log file
It is done simply by doing:
```
log_dir = self.get_scratch_space()
log_file_path = os.path.join(log_dir, "tee_log")
```
and then pass `output_file=log_file_path` it to the tested  `system()` func
and then before the end of the test do
```
# Check that log file contains error message.
log_content = hio.from_file(log_file_path)
self.check_string(log_content)
```

**Comment by DanilYachmenev** [comment]
@Dylan-Celli lets file a draft PR with code skeleton for all 3 tests and then if any questions left - we will discuss it on the code

**Comment by Dylan-Celli** [comment]
I added the additional unit tests but I am running into an issue with `helpers/test/test_system_interaction.py::System_test1::test9` after I added the `self.check_string(log_content)`, the rest of the unit test runs as intended. If I understand the comment in `helpers/hunit_test.py::check_string` correctly the method automatically checks the contents of the given file against the output of the given unit test. Which leads me to some confusion as I am unsure of what I can do to resolve the differences.

Additionally, should I be expecting any specific error/exceptions types to be thrown for these unit tests? Right now I am just catching whatever error/exceptions the command throws out each time.
EX
```
System_test1::test8
self.assertRaises(AssertionError)

System_test1::test9
self.assertRaises(RuntimeError)

System_test1::test10
self.assertRaises(TypeError)
```

**Comment by DanilYachmenev** [comment]
@Dylan-Celli lets step away from `check_string` actually and compare logs signatures
see my comments in the PR

Type of errors you specify are mostly correct, but checking signatures is what will allow us to see what exactly fails
use `-s --dbg` when running the test to get more detailed logs and update your signatures accordingly
