### ISSUE TITLE
Check for vulnerabilities

### ISSUE THREAD

**Issue by gpsaggese** [sorrentum/sorrentum#366]
Since this is a public repo, let's take a look at the vulnerabilities from
```
remote: .
remote: GitHub found 60 vulnerabilities on sorrentum/sorrentum's default branch (1 critical, 18 high, 39 moderate, 2 low). To find out more, visit:
remote:      https://github.com/sorrentum/sorrentum/security/dependabot
remote: 
```
Typically they are silly stuff. The only thing that worries me is having some leaked passwords (PTSD).

I recall we were talking to add a git leak detector as GH action. This might be a good task for the new IT hire.

**Comment by jsmerix** [comment]
We are looking for a solution in https://github.com/cryptokaizen/cmamp/issues/3727
