### ISSUE TITLE
Unit test `plot_histograms_and_lagged_scatterplot`

### ISSUE THREAD

**Issue by DanilYachmenev** [sorrentum/sorrentum#374]
Follow-up from https://github.com/cryptokaizen/cmamp/issues/4630

We need to unit test `plot_histograms_and_lagged_scatterplot()`

Sample for the test can be taken from https://github.com/cryptokaizen/cmamp/pull/4659#issue-1779435238

The most tricky part is the testing approach itself, since we need to do 2 things:
- Show that charts are being plotted correctly in a gallery notebook
- Test the plotting function itself so the coverage report considers the function tested

My suggestion would be to do the following:
- Create `test_gallery_notebook.ipynb` in `amp/core/plotting/test` where we will plot all the charts from `amp/core/plotting`, including this one
- Add a test file `test_plots.py` (or smth like that) where we will run plotting functions from `amp/core/plotting/test` just as a smoke tests so the coverage is green

@gpsaggese @gitpaulsmith wdyt?

FYI @samarth9008 @PomazkinG 

Assigned myself to re-distribute to interns after we agree on file structure

**Comment by gpsaggese** [comment]
This is a good idea IMO. Are the specs ok and can be farmed out or do we need anything else?

**Comment by DanilYachmenev** [comment]
@dchoi127

So to clarify the specs one more for this function specifically:
- Create `test_gallery_notebook.ipynb` in `amp/core/plotting/test` and plot `plot_histograms_and_lagged_scatterplot()` using the example from here https://github.com/sorrentum/sorrentum/issues/374#issuecomment-1618181009
Please follow https://github.com/sorrentum/sorrentum/blob/master/docs/Jupyter_notebook_best_practices.md
- Add a test file test_plots.py to `amp/core/plotting/test` and add a test for `plot_histograms_and_lagged_scatterplot()` func there. No need to check any outcomes. Just set the same inputs as above and run the function in a way similar notebook. Since we do not check any outcomes, this is called "smoke" test - we just need to check if the function passes through the `.py` testing code

let us know if you have any questions

**Comment by dchoi127** [comment]
@DanilYachmenev 

The links in the original description and follow up appear to be broken. I kindly request that these links be updated, they would help me greatly.

**Comment by DanilYachmenev** [comment]
@dchoi127 there is actually nothing more than in this message provided by @samarth9008
https://github.com/sorrentum/sorrentum/issues/374#issuecomment-1618181009

So just use it as reference that I mention in the issue

**Comment by dchoi127** [comment]
@DanilYachmenev 

When attempting to plot in a gallery notebook. The following errors occur

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In [7], line 1
----> 1 cpvistte.plot_histograms_and_lagged_scatterplot(srs, lag)

File /app/core/plotting/visual_stationarity_test.py:62, in plot_histograms_and_lagged_scatterplot(srs, lag, oos_start, nan_mode, title, figsize, hist_kwargs, scatter_kwargs, axes)
     60 # Plot histograms.
     61 if axes is None:
---> 62     _, axes = cplpluti.get_multiple_plots(3, 2, y_scale=figsize[1] / 2)
     63     plt.suptitle(title or srs.name)
     64 sns.histplot(
     65     srs_first_part, ax=axes[0], kde=True, stat="probability", **hist_kwargs
     66 )

TypeError: 'NoneType' object is not subscriptable


Replicate this error:
```
import numpy as np
import pandas as pd
import core.plotting.visual_stationarity_test as cpvistte

srs = pd.Series(
    np.concatenate([np.random.uniform(-1, 1, 100), np.random.choice([5, 10], 100)]),
    index=pd.date_range(start="2023-01-01", periods=200, freq="D")
)
lag = 7

cpvistte.plot_histograms_and_lagged_scatterplot(srs, lag)
```

**Comment by dchoi127** [comment]
@DanilYachmenev 

UPDATE:

After putting in some dummy values for figsize using `cpvistte.plot_histograms_and_lagged_scatterplot(srs, lag, figsize = (20,20))` it works as expected.
