### ISSUE TITLE
On-board Yuanxuan (Brandon) Fang 

### ISSUE THREAD

**Issue by DanilYachmenev** [sorrentum/sorrentum#389]
Please follow this checklist. Post any errors you face in this issue.

- [x] Read [How to organize your work](https://github.com/sorrentum/sorrentum/blob/master/docs/How_to_organize_your_work.md)
- [x] Read [Quick start for developing](https://github.com/sorrentum/sorrentum/blob/master/docs/Quick_start_for_developing.md). Read through the [first section](https://github.com/sorrentum/sorrentum/blob/master/docs/Quick_start_for_developing.md#supporting-os) if you are using Windows
- [x] Make sure the [Docker dev container](https://github.com/sorrentum/sorrentum/blob/master/docs/Quick_start_for_developing.md#sorrentum-dev-docker-container-aka-dev-container-cmamp-container) works
- [x] Make sure the [unit tests](https://github.com/sorrentum/sorrentum/blob/master/docs/Unit_tests.md) run successfully
- [x] Read [Sorrentum Python coding style guide](https://github.com/sorrentum/sorrentum/blob/master/docs/Coding_Style_Guide.md)
- [x] Get assigned a warm-up issue
- [x] Learn about the [Morning Email](https://github.com/sorrentum/sorrentum/blob/master/docs/General_rules_of_collaboration.md#morning-email)
- [x] How to do a [review](https://github.com/sorrentum/sorrentum/blob/master/docs/First_review_process.md)
- [x] If you are graduating soon and you would like to get a part- / full-time job in one of the companies in the Sorrentum ecosystem reach out to GP at gp@sorrentum.org
- [x] Get up to speed in terms of the background knowledge for specific project
- For Web3 / Crypto : [README.md](https://github.com/sorrentum/sorrentum/blob/master/defi/README.md)
- For Arbitrage / Modeling: [From_zero_to_modeling.md](https://github.com/sorrentum/sorrentum/blob/master/docs/From_zero_to_modeling.md)
 
FYI @gpsaggese @samarth9008

**Comment by samarth9008** [comment]
How is the progress? Any ETA?

**Comment by brandonnsc** [comment]
Hi Samarth,

Thank you for your concern. All is going well. I'm currently working on the
Unit Test and will complete all tasks on the checklist by the end of this
weekend. I'll keep you updated.

Best,
Yuanxuan

**Comment by brandonnsc** [comment]
Hi Samarth,

I just added Test8 in test_system_interaction.py which is 
```
def test8(self) -> None:
        """
        Test a failing command with the --tee switch.
        """
        with tempfile.NamedTemporaryFile() as fp:
            temp_file_name = fp.name
            with self.assertRaises(RuntimeError) as cm:
                hsystem.system("ls this_file_doesnt_exist", tee=True, output_file=temp_file_name)
            act = str(cm.exception)
            # Different systems return different rc.
            act = re.sub(r"rc='(\d+)'", "rc=''", act)
            self.check_string(act)  
```
Then, I run `i run_fast_tests --coverage`, and it shows passing the test.

But when I tried to create a branch and do git push for visible latest changes, it shows I cannot access with return error 403:
```
(amp.client_venv) brandonnsc@brandonnsc:~/src/sorrentum1$ git push origin SorrTask355_Unit_test_tee_param_for_hsystem.system
Username for 'https://github.com': brandonnsc
Password for 'https://brandonnsc@github.com': 
remote: Permission to sorrentum/sorrentum.git denied to brandonnsc.
fatal: unable to access 'https://github.com/sorrentum/sorrentum.git/': The requested URL returned error: 403
```
I tried to use personal access tokens here, and it still doesn't work. 

Also, I just sent the request for join group in the morning email.

Summary above questions:
1. How to solve the permission to sorrentum/sorrentum.git denied to brandonnsc?
2. Please check my request of join group in morning email

**Comment by DanilYachmenev** [comment]
@brandonnsc why did you add `test8` to `test_system_interaction.py`?

**Comment by brandonnsc** [comment]
![Capture](https://github.com/sorrentum/sorrentum/assets/106702167/2f5d1fa6-ec62-485b-a4fc-67fd570db809)
Because in the #335 issues, you mentioned that we need add a test to `Test_system1`  that runs `.system()` on failing cmd with`--tee` switch enabled.

**Comment by DanilYachmenev** [comment]
@brandonnsc respect for being initiative!

However, lets follow the process which is to implement tasks that are assigned to you
And if you see that smth has to be done or you have a proposal - write in the corresponding issue or ping us in Telegram

Otherwise, there is always a risk of doing a work that is already in progress by other team members
Like in this case, for which I've just merged the tests added by an assigned student
https://github.com/sorrentum/sorrentum/pull/378

So nothing bad done here ofc, keep pushing, keep doing code, we respect it
However, lets confirm it with us upfront so your efforts do not go in vain

**Comment by DanilYachmenev** [comment]
So when you finish the on-boarding, let us know and we will assign you a task

**Comment by brandonnsc** [comment]
Thank you for your explanation. I believe I may have misunderstood the content in the 'Quick_start' doc. I initially thought I had to choose an issue marked as 'good as first bug' as a warm-up issue. Therefore, other than waiting for the approval from the Morning Email, I am now ready to undertake any task you assign to me.

**Comment by DanilYachmenev** [comment]
@brandonnsc has your Morning Email request been approved and could you make sure that unit test run successfully on your end?
If yes, please mark checkboxes on [top](https://github.com/sorrentum/sorrentum/issues/389#issue-1788196143) as completed and we can close this one

**Comment by brandonnsc** [comment]
Thank you for your previous guidance. I have successfully joined the Morning Email group. 

I noticed there's a requirement to send a TODO email within the group conversation. Could you please confirm if this is to be sent daily before commencing my work? Furthermore, should I reply within the existing conversation or start a new one each time to send this email?

**Comment by DanilYachmenev** [comment]
> Thank you for your previous guidance. I have successfully joined the Morning Email group.
> 
> I noticed there's a requirement to send a TODO email within the group conversation. Could you please confirm if this is to be sent daily before commencing my work? Furthermore, should I reply within the existing conversation or start a new one each time to send this email?

- yes, sent at each day when you're going to work. 1st thing to do in a day basically
- no, no need to reply to emails. Send a new one each time. The most important thing is to send it and to have it in the right format

**Comment by DanilYachmenev** [comment]
Done, closing
warm-up issue is https://github.com/sorrentum/sorrentum/issues/423
