### ISSUE TITLE
On-board Yuan Wang

### ISSUE THREAD

**Issue by samarth9008** [sorrentum/sorrentum#392]
Please follow this checklist. Post any errors you face in this issue.

- [x] Read [How to organize your work](https://github.com/sorrentum/sorrentum/blob/master/docs/How_to_organize_your_work.md)
- [x] Read [Quick start for developing](https://github.com/sorrentum/sorrentum/blob/master/docs/Quick_start_for_developing.md). Read through the [first section](https://github.com/sorrentum/sorrentum/blob/master/docs/Quick_start_for_developing.md#supporting-os) if you are using Windows
- [x] Make sure the [Docker dev container](https://github.com/sorrentum/sorrentum/blob/master/docs/Quick_start_for_developing.md#sorrentum-dev-docker-container-aka-dev-container-cmamp-container) works
- [x] Make sure the [unit tests](https://github.com/sorrentum/sorrentum/blob/master/docs/Unit_tests.md) run successfully
- [x] Read [Sorrentum Python coding style guide](https://github.com/sorrentum/sorrentum/blob/master/docs/Coding_Style_Guide.md)
- [x] Get assigned a warm-up issue
- [x] Learn about the [Morning Email](https://github.com/sorrentum/sorrentum/blob/master/docs/General_rules_of_collaboration.md#morning-email)
- [x] How to do a [review](https://github.com/sorrentum/sorrentum/blob/master/docs/First_review_process.md)
- [x] If you are graduating soon and you would like to get a part- / full-time job in one of the companies in the Sorrentum ecosystem reach out to GP at gp@sorrentum.org
- [x] Get up to speed in terms of the background knowledge for specific project
- For Web3 / Crypto : [README.md](https://github.com/sorrentum/sorrentum/blob/master/defi/README.md)
- For Arbitrage / Modeling: [From_zero_to_modeling.md](https://github.com/sorrentum/sorrentum/blob/master/docs/From_zero_to_modeling.md)

FYI @gpsaggese @DanilYachmenev

**Comment by gpsaggese** [comment]
Waiting for Yuan to accept the invitation to assign, right?

**Comment by samarth9008** [comment]
Yes

**Comment by Ro0k1e** [comment]
Hi, I encounter some problems with the unit-test. After I activate the thin environment, I tried to run the following code
`i run_fast_tests --stage local`,
and this was the error message:
`Pulling app (sorrentum/cmamp:local-ywang)
ERROR: manifest for sorrentum/cmamp:local-ywang not found: manifest unknown: manifest unknown`. 

I am not sure how to fix it.

**Comment by samarth9008** [comment]
Try to run `i run_fast_tests`

**Comment by Ro0k1e** [comment]
Thank you it worked!

**Comment by Ro0k1e** [comment]
Hi, I have finished the on-boarding checklist except for the warm-up issue! Looking forward to my assigned warm-up issue!

**Comment by DanilYachmenev** [comment]
Done, closing
