### ISSUE TITLE
Unit test plotting gallery notebook

### ISSUE THREAD

**Issue by DanilYachmenev** [sorrentum/sorrentum#395]
After https://github.com/sorrentum/sorrentum/pull/393 is finished and merged

Add a unit test for `core/plotting/notebooks/gallery_notebook.ipynb`
- create a file `core/plotting/notebooks/test/test_gallery_notebook.py`
- add unit test for the notebook there using `dev_scripts/notebooks/run_notebook.py` script
    - for reference see `research_amp/cc/notebooks/test/test_algo_notebook.py`

As usually follow the unit test doc specs

FYI @samarth9008 @gpsaggese

**Comment by dchoi127** [comment]
@DanilYachmenev 

Looking at the reference files and saw that the unit test in `research_amp/cc/notebooks/test/test_algo_notebook.py` uses a config builder. Is that necessary here?

**Comment by DanilYachmenev** [comment]
> @DanilYachmenev
> 
> Looking at the reference files and saw that the unit test in `research_amp/cc/notebooks/test/test_algo_notebook.py` uses a config builder. Is that necessary here?

Yes, config builder is required for `run_notebook.py` script

We will pass some params to it later
For now just create a dummy one, just like in the algo notebook
