### ISSUE TITLE
Download Info for students

### ISSUE THREAD

**Issue by samarth9008** [sorrentum/sorrentum#396]
- We want to scrape this web page and get useful information about students such as name, email, contact and any other which can be useful to contact them
https://www.cs.umd.edu/people/phonebook/grad-student

- We will not be pushing this script so feel free to do it in your way.
- The end result would be a google spreadsheet file which contains all the useful information in readable format for each student.

FYI @DanilYachmenev @gpsaggese

**Comment by gpsaggese** [comment]
I'd say we will push to the repo for posterity but it can be a hacky one (no unit test, ...).

It could be as simple as downloading the HTML, and do a simple regex
There are packages like scrapy and beautiful soup that make this a breeze.

I'd spend something like 2-3 hours on it.

Feel free to post a short plan on the bug if you want to have feedback.
Makes sense?
