### ISSUE TITLE
Order book data

### ISSUE THREAD

**Issue by gpsaggese** [sorrentum/sorrentum#41]
@jsmerix can we pls save to the data dir some order book data?

Ideally:
- 10 levels
- 1 sec resolution is best (1 min is ok)
- 1 year of history is enough
- Universe v7 or a subset of it

If it's more complicated than a copy from our S3 bucket, feel free to ping me to discuss

**Comment by jsmerix** [comment]
If we want parquet than it's simple, if we want csv, a bit of work is needed.

**Comment by gpsaggese** [comment]
Only Parquet. If somebody asks for CSV, you are authorized to say "we don't support it"

**Comment by jsmerix** [comment]
Just to confirm, should these be binance spot or futures data?

**Comment by gpsaggese** [comment]
Futures

**Comment by jsmerix** [comment]
Added new dataset `periodic_daily.airflow.downloaded_1sec.parquet.bid_ask.futures.v3.crypto_chassis.binance.v1_0_0`
into the [gdrive folder](https://drive.google.com/drive/u/0/folders/1O9FCMY61LDUCjiT4nPBG9XPpCmbTsCFC)

- 1 year worth of orderbook (AKA bid/ask or market-depth) futures data for 7 symbols from Binance  (up to 10th level of orderbook)

**Comment by gpsaggese** [comment]
Thank you @jsmerix  and good job reading my mind adding documentation here 
https://docs.google.com/document/d/1SceHHhOWyusWJYibMvQhyz2_qxic9By-deGFwCHxKW8/edit#heading=h.3nb09noyuuql

@canum05 can you figure out who in your team needed 1 sec data? 
We can start building 1-sec models. We have enough data here to even use deep learning
