### ISSUE TITLE
Run PhantomBuster from Python (automatically)

### ISSUE THREAD

**Issue by gpsaggese** [sorrentum/sorrentum#411]
Moving from https://github.com/gpsaggese/umd_icorps/issues/16 (unfortunately GH doesn't allow me to just move it, so horrible copy&paste)

==========

[gpsaggese](https://github.com/gpsaggese) commented [3 days ago](https://github.com/gpsaggese/umd_icorps/issues/16#issue-1795472425) • 
This is like https://github.com/gpsaggese/umd_icorps/issues/15 but we want to write a Python script to automate the flow.

There are two parts are:

Control PhantomBuster from Python
Save output to gsheet
Results are here https://docs.google.com/document/d/15zTRgmcbK3sm0KqLRBRhUFzJFGfzAhm0Ah0LXOLnwWs/edit#heading=h.e3iwj7fpanob

@[gpsaggese](https://github.com/gpsaggese) gpsaggese assigned [yiyunlei](https://github.com/yiyunlei) [2 days ago](https://github.com/gpsaggese/umd_icorps/issues/16#event-9777980444)
@gpsaggese
Author
[gpsaggese](https://github.com/gpsaggese) commented [2 days ago](https://github.com/gpsaggese/umd_icorps/issues/16#issuecomment-1629461877) • 
Given a linkedin search

https://www.linkedin.com/search/results/people/?geoUrn=%5B%2290000097%22%5D&keywords=Retired&origin=FACETED_SEARCH&schoolFilter=%5B%223638%22%5D&sid=BVh

Write a notebook to control the scraper from Python using the API https://hub.phantombuster.com/reference/getagentrecord-1

IMO the best example is https://github.com/Magic-Wike/Icebreaker/blob/master/phantombuster.py

I've started cleaning the example in
http://localhost:8889/notebooks/data/umd_icorps_1/project/icorps/notebooks/phantom_utils.py

@[yiyunlei](https://github.com/yiyunlei)
yiyunlei commented [yesterday](https://github.com/gpsaggese/umd_icorps/issues/16#issuecomment-1631121076)
I found a super easy way to save the output to Gsheet and it can update dynamically. :)
Resource Link: [View your Results with Google Spreadsheets](https://support.phantombuster.com/hc/en-us/articles/360007125739-View-your-Results-with-Google-Spreadsheets)
Therefore, we just need to use the =IMPORTDATA formula to import data.

Gsheet examples I created:

https://docs.google.com/spreadsheets/d/1xLdTYj7tjUbg0m2wtY5F0-nt3JHXzbo97CcmdKvK3Q8/edit?usp=sharing
https://docs.google.com/spreadsheets/d/1xLdTYj7tjUbg0m2wtY5F0-nt3JHXzbo97CcmdKvK3Q8/edit?usp=sharing
image
The only issue is that this function cannot import result files larger than 100k cells(assume 20 cells for one data, then ~5000 data), and I found this solution: [Phantombuster’s googlesheet templates: How to handle heavy files?](https://fabian-maume.medium.com/phantombusters-googlesheet-templates-how-to-handle-heavy-files-851a6eb7ae2d)

As our data is way less than 5000, so we can use the IMPORTDATA function for now.

This solution works beautifully for small data sets. If we need to handle larger data, I can test the alternative solution I've found.

@[yiyunlei](https://github.com/yiyunlei)
yiyunlei commented [yesterday](https://github.com/gpsaggese/umd_icorps/issues/16#issuecomment-1631152404)
I have updated some progress in the doc:
https://docs.google.com/document/d/15zTRgmcbK3sm0KqLRBRhUFzJFGfzAhm0Ah0LXOLnwWs/edit#heading=h.2oolqq6k9fv3

I also figured out the process and tested the Python example you offered:

Python example works, and I can get result_csv of GP LinkedIn Profile Scraper:
{
  "resultObject": "{\"csvURL\":\"https://phantombuster.s3.amazonaws.com/jqWbRHyznhM/YdJCf08D0aKIi59rSI6D3Q/result.csv\",\"jsonUrl\":\"https://phantombuster.s3.amazonaws.com/jqWbRHyznhM/YdJCf08D0aKIi59rSI6D3Q/result.json\"}"
}
but I can't get reslut_csv of GP Sales Navigator Search Export.

{
  "resultObject": null
}
Maybe it because the setting of GP Sales Navigator Search Export, which doesn't save result_csv to phantombuster aws.

The process of using python to control PhantomBuster.
Use agents/save or GUI to create the agent.
Use agents/launch and agents/stop to control launch and stop.
Use container/fetch_all to get containers of one specific agent.
Use container/fetch_result_object to get result_csv url.
@gpsaggese
Author
[gpsaggese](https://github.com/gpsaggese) commented [25 minutes ago](https://github.com/gpsaggese/umd_icorps/issues/16#issuecomment-1632795452)
Very good job thinking about the problem and documenting it.

They used to support natively Gsheet outputs and recently switched to using S3 files (but good finding)

The use case we have is:

One comes up with a search
We kick off the search
The search runs for hours or days due to throttling
(ideally with a script so we don't have to click on the GUI)
When the search is done, we save the results in a gsheet (ideally making a copy as CSV instead of relying on the S3 file, what if they remove it?)
Then we go through the notebook flow to:
do some automatic processing (e.g., find all the people with a valid email)
interface with humans (e.g., remove crap from the results)
We can use gsheet as input and output of notebook flows to interface with PhantomBuster (when we want to run multiple phantoms in a row, e.g., scrape search and then profiles)
Taking a step back (given the new specs and your findings), we should try to run this flow "manually" and then we can see which parts are problematic and we can automate.

I'll add some more info to the gdoc

**Comment by yiyunlei** [comment]
Update: Also got the result date of GP Sales Navigator Search Export through API.

**Comment by yiyunlei** [comment]
It was closed because of  PR #515.
