### ISSUE TITLE
Glossary gDoc to MD

### ISSUE THREAD

**Issue by samarth9008** [sorrentum/sorrentum#419]
- We need to convert a [Gdoc](https://docs.google.com/document/d/11tifXzRNEOkpnlar08pE9C8UBNJQzB0v_mFxc5Auyo0/edit#heading=h.5ox0o89lzqmb) of Glossary to Markdown
- Instructions on how to convert Gdocs to Markdown are [here](https://github.com/sorrentum/sorrentum/blob/master/docs/Documentation_about_guidelines.md#gdocs---markdown)
- Read about the [First Review Process](https://github.com/sorrentum/sorrentum/blob/master/docs/First_review_process.md)
- Lint the markdown file using the [linter](https://github.com/sorrentum/sorrentum/blob/master/dev_scripts/lint_md.sh)
- PR example is https://github.com/sorrentum/sorrentum/pull/198

FYI @DanilYachmenev

**Comment by dhimuk** [comment]
@samarth9008 I am trying to push my local branch to the remote repository, but its giving me an "Authentication Failed Error"

**Comment by samarth9008** [comment]
Its hard to debug without logs. Paste the logs over here. It is probably bcz you need to authenticate with `ssh` or PAT token.

**Comment by DanilYachmenev** [comment]
done
