### ISSUE TITLE
Create empty gsheet through API

### ISSUE THREAD

**Issue by gpsaggese** [sorrentum/sorrentum#420]
From Sonya

A good new issue to file, related to Step 2.3 of the plan, would be figuring out if it is possible to automatically, through python/API, create an (empty) gsheet with a given name on the gdrive. There must be some solution, a quick Google gives lots of things to try, e.g. https://stackoverflow.com/questions/73167028/create-a-google-sheet-file-stored-in-my-google-drive-and-share-it-with-python

**Comment by yiyunlei** [comment]
Update: Run the sample code in the https://stackoverflow.com/questions/73167028/create-a-google-sheet-file-stored-in-my-google-drive-and-share-it-with-python successfully and it can create a new gDoc. I will improve the code.

**Comment by yiyunlei** [comment]
Resource: 
- Google API docs: https://developers.google.com/sheets/api/guides/create#python

**Comment by yiyunlei** [comment]
TODO: 
- Need to add: create the empty google sheets in a specific dir / shared dir.
