### ISSUE TITLE
Run Search5 through LIN marketing process

### ISSUE THREAD

**Issue by gpsaggese** [sorrentum/sorrentum#421]
We want to run Search5 from https://docs.google.com/document/d/1WGH1wVOzJSAVES7tGYP8XGkkXZEoePXSZFeAsrEC_js/edit#heading=h.yul22melwh8h
through the manual flow following the process described at
https://docs.google.com/document/d/1dfAVMJZtHtQ3sX7UHwpXNAWPiJs17w0V8FlsOI7a32M/edit
updating the status of the scraping on
https://docs.google.com/spreadsheets/d/1Hfk8wvhVw84G239cexAGlS4mIeVU-bVAkzgZAdG4UUY/edit#gid=0

The goal is to exercise all the pieces and verify that the flow works, before we start automating.

Pls ping me on TG and I can give you my API key so that you can run through my account.

**Comment by yiyunlei** [comment]
If we want the entire flow can be run in the Sorrentum docker environment, we need to install `gspread_pandas` in the environment. Could this be added?
@gpsaggese

**Comment by yiyunlei** [comment]
Existing Issues Found in Search 5:

- `gspread_pandas` needs to be installed in the environment.
- It is necessary to run the search several times to obtain a Linkedin Profile. (Search Scraping might also need to run multiple times)
  - Consider using Airflow to schedule these tasks / the entire flow.
- If you change the Phantom setup and launch it again, the changes won't take effect. (This is a Phantombuster issue, and can be ignored)

- It's easy to modify other documents/sheets using the Google API that I have access to. (Be careful with this)
- Need to be added to the filter scripts/notebooks: 
   - delete the error column.
   - Ensure that the ProfileURL is in the first column to run the Linkedin Profile Search.

I will work on these issues.

**Comment by yiyunlei** [comment]
@gpsaggese I finished running search5 manually. Should I run search7? (I haven't gotten search7 yet.)

**Comment by gpsaggese** [comment]
> Existing Issues Found in Search 5:
> 
> * `gspread_pandas` needs to be installed in the environment.

For now you can just do in the notebook something like install locally
```
!sudo /bin/bash -c "(source /venv/bin/activate; pip install yfinance)"
```
> * It is necessary to run the search several times to obtain a Linkedin Profile. (Search Scraping might also need to run multiple times)
>   

Because of LinkedIn throttling you might need to let the system run multiple iterations (e.g., every hour). Is this what you mean?
E.g., setting this up

<img width="1162" alt="image" src="https://github.com/sorrentum/sorrentum/assets/33238329/238846c5-8561-40f4-8f87-cfb6bc255f8f">

If that's the problem pls update the gdoc with the process

>   * Consider using Airflow to schedule these tasks / the entire flow.

Let's keep running manually and exploring until we understand what / how to automate. We can't / don't want to automate the entire flow but make it more automatic.

> * If you change the Phantom setup and launch it again, the changes won't take effect. (This is a Phantombuster issue, and can be ignored)

I think I understand, but feel free to explain better on the gdoc (with figures and so on). We want to have a doc that we can have people to read and learn how to use the system.

> * It's easy to modify other documents/sheets using the Google API that I have access to. (Be careful with this)
> * Need to be added to the filter scripts/notebooks:
>   
>   * delete the error column.
>   * Ensure that the ProfileURL is in the first column to run the Linkedin Profile Search.
>

Let's do a PR with the notebooks. I would keep only 2 notebooks for the 2 post-processing and then one can point it to different gsheet (with Search5 and Search7).
 
> I will work on these issues.

> @gpsaggese I finished running search5 manually. Should I run search7? (I haven't gotten search7 yet.)

I would work on getting Search5 done end-to-end and then we can move to Search7 (unless you want to start in background)

Good job. Keep it up!

**Comment by yiyunlei** [comment]
> For now you can just do in the notebook something like install locally
> 
> ```
> !sudo /bin/bash -c "(source /venv/bin/activate; pip install yfinance)"
> ```

Great. Thanks.

> Because of LinkedIn throttling you might need to let the system run multiple iterations (e.g., every hour). Is this what you mean? E.g., setting this up
> 
> <img alt="image" width="1162" src="https://user-images.githubusercontent.com/33238329/254991167-238846c5-8561-40f4-8f87-cfb6bc255f8f.png">
> If that's the problem pls update the gdoc with the process

Yes, that's exactly what I wanted to say. I mention this because I thought we wanted to eliminate the need for clicking the Phantombuster GUI, which means this function needs to be implemented. In other words, how do we run a phantom multiple times or iterations without interacting with the GUI? (I haven't found the API for it, perhaps it needs to be written into the scraping script.)


> I think I understand, but feel free to explain better on the gdoc (with figures and so on). We want to have a doc that we can have people to read and learn how to use the system.

Okay, no problem.

> Let's do a PR with the notebooks. I would keep only 2 notebooks for the 2 post-processing and then one can point it to different gsheet (with Search5 and Search7).

Yep, I'm planning to add these filters/functions to Sonya's notebooks.


> I would work on getting Search5 done end-to-end and then we can move to Search7 (unless you want to start in background)
Ok, will do.

**Comment by yiyunlei** [comment]
> Let's keep running manually and exploring until we understand what / how to automate. We can't / don't want to automate the entire flow but make it more automatic.

I have been considering automating the entire flow since you suggested avoiding GUI clicks. 🤣

Are you suggesting that it's acceptable if we manually run these Phantom/Filter Python scripts? If so, does that mean we only run these Google Sheets/Filter Python scripts once, after Phantom has run multiple iterations? In other words, do we wait for Phantom to finish its job and then perform the filtering?

I think I understand now. If we don't fully automate the process and instead make it more automated, we would need a markdown guide to explain the process.

**Comment by gpsaggese** [comment]
> > Let's keep running manually and exploring until we understand what / how to automate. We can't / don't want to automate the entire flow but make it more automatic.
> 
> I have been considering automating the entire flow since you suggested avoiding GUI clicks. 🤣

Yes, the idea is that we don't know yet how annoying is the clicking vs how complicate it is to automate

Mandatory XKCD reference
https://xkcd.com/1205/

So the right approach is to run a few times manually and then judge what are the pain points

> 
> Are you suggesting that it's acceptable if we manually run these Phantom/Filter Python scripts? If so, does that mean we only run these Google Sheets/Filter Python scripts once, after Phantom has run multiple iterations? In other words, do we wait for Phantom to finish its job and then perform the filtering?

Yes, we can run Phantom multiple iterations through the GUI and maybe we can "automate" some other piece of the flow.

> 
> I think I understand now. If we don't fully automate the process and instead make it more automated, we would need a markdown guide to explain the process.

Yes, let's do it by hand a few times and explain how to do it in the Gdoc https://docs.google.com/document/d/1dfAVMJZtHtQ3sX7UHwpXNAWPiJs17w0V8FlsOI7a32M/edit#heading=h.7un0ebyk18ti
