### ISSUE TITLE
Tools - Profiling gdoc to md

### ISSUE THREAD

**Issue by samarth9008** [sorrentum/sorrentum#428]
- We need to convert a [Gdoc](https://docs.google.com/document/d/1p9y6nCp5dZ4t6NkJi43hGsV7bbS-blt2pDSQNs4JVu8/edit#heading=h.uozte5s2n04) of Glossary to Markdown
- Instructions on how to convert Gdocs to Markdown are [here](https://github.com/sorrentum/sorrentum/blob/master/docs/Documentation_about_guidelines.md#gdocs---markdown)
- Read about the [First Review Process](https://github.com/sorrentum/sorrentum/blob/master/docs/First_review_process.md)
- Lint the markdown file using the [linter](https://github.com/sorrentum/sorrentum/blob/master/dev_scripts/lint_md.sh)
- PR example is https://github.com/sorrentum/sorrentum/pull/198

FYI @DanilYachmenev

**Comment by Ro0k1e** [comment]
Hi Samarth, I wonder where I should upload the image so that the image embedded in the md file can be shown.

**Comment by samarth9008** [comment]
You can create a folder, upload image over there and then reference it. You can take a look at other docs where image is being uploaded.

**Comment by Ro0k1e** [comment]
Thank you Samarth! Working on it now!
