### ISSUE TITLE
Remove instructions related to mailchimp

### ISSUE THREAD

**Issue by jsmerix** [sorrentum/sorrentum#438]
https://github.com/sorrentum/sorrentum/blob/master/docs/Signing_up_for_Sorrentum.md

> Add the contributor to Mailchimp

If I understand correctly, this is no longer used, right? If it is, can you point me to a document describing how it is used and who has access?

**Comment by samarth9008** [comment]
I have already created PR for it. 
https://github.com/sorrentum/sorrentum/pull/436

**Comment by samarth9008** [comment]
Are you asking about the use of mailchimp?

**Comment by jsmerix** [comment]
Oh okay, yes, sounds good, closing then.
