### ISSUE TITLE
On-board Oleksandr Horielov

### ISSUE THREAD

**Issue by DanilYachmenev** [sorrentum/sorrentum#440]
Please follow this checklist. Post any errors you face in this issue.

  - [x] Acknowledge the pledge to put time in the project [here](https://github.com/sorrentum/sorrentum/blob/master/README.md#Important) 
  - [x] Read [How to organize your work](https://github.com/sorrentum/sorrentum/blob/master/docs/How_to_organize_your_work.md)
  - [x] Read [Quick start for developing](https://github.com/sorrentum/sorrentum/blob/master/docs/Quick_start_for_developing.md)
  - [x] Make sure the [Docker dev container](https://github.com/sorrentum/sorrentum/blob/master/docs/Quick_start_for_developing.md#sorrentum-dev-docker-container-aka-dev-container-cmamp-container) works
  - [x] Make sure the [unit tests](https://github.com/sorrentum/sorrentum/blob/master/docs/Unit_tests.md) run successfully
  - [x] Read [Sorrentum Python coding style guide](https://github.com/sorrentum/sorrentum/blob/master/docs/Coding_Style_Guide.md)
  - [x] Fork, star, watch the Sorrentum repo so that GitHub promotes our repo (we gotta work the system)
  - [x] Get assigned a warm-up issue
  - [x] Learn about the [Morning Email](https://github.com/sorrentum/sorrentum/blob/master/docs/General_rules_of_collaboration.md#morning-email)
  - [x] How to do a [review](https://github.com/sorrentum/sorrentum/blob/master/docs/First_review_process.md)
  - [x] If you are graduating soon and you would like to get a full-time job in one of the companies in the Sorrentum ecosystem reach out to GP at gp@sorrentum.org
 
FYI @gpsaggese @PomazkinG

**Comment by gpsaggese** [comment]
@DanilYachmenev can you pls file the issue from the gdoc? For simplicity's sake we are skipping enabling Gdoc access

**Comment by DanilYachmenev** [comment]
Filed https://github.com/sorrentum/sorrentum/issues/444

**Comment by critrange** [comment]
@DanilYachmenev I sent request access to warm-up issue link.
https://docs.google.com/document/d/1kmybx8u6eJsJBYndPb4r3jPcKM1yNpXIHpLJeRKK4l4/edit#heading=h.wmiblgturcbb
@PomazkinG

**Comment by gpsaggese** [comment]
They already filed it at #444 (no need to access that doc)

**Comment by critrange** [comment]
> They already filed it at #444 (no need to access that doc)

So this issue is my first task? @gpsaggese

**Comment by gpsaggese** [comment]
Correct. Let's:
- follow all the procedures carefully
- do quick iterations, always committing your branch
- ask questions when things are not clear (rather than going off tangents)

I look forward to us blowing us away with beautiful code. Good luck.

**Comment by critrange** [comment]
> 

Okay, I will start the task as soon as i mark all items in above list. It's quite a lot to study.

**Comment by critrange** [comment]
@gpsaggese @DanilYachmenev I just marked all items and gonna start actual tasks now.
I just saw #444 but I don't think it's related with access problem to the my warm-up issue link (https://docs.google.com/document/d/1kmybx8u6eJsJBYndPb4r3jPcKM1yNpXIHpLJeRKK4l4/edit#heading=h.wmiblgturcbb)
Can you please double check the issue?

**Comment by PomazkinG** [comment]
@critrange #444 is your warm-up issue, the gdoc link leads to the same text but in the gdoc

in other words, for your convenience @DanilYachmenev filed an issue in the Github directly so that we do not need to solve the access issue

**Comment by critrange** [comment]
> 

Ah, I see. thanks

**Comment by PomazkinG** [comment]
Done

**Comment by critrange** [comment]
Hi @gpsaggese @DanilYachmenev  @PomazkinG 
My PRs are waiting for review and are close to being merged now. Can you please assign more issues to me?

Btw as I checked below guide, I should ping you in Telegram chat in this case. Please let me know your TG channel id.
https://github.com/sorrentum/sorrentum/blob/master/docs/General_rules_of_collaboration.md#ping-team-leaders-when-you-are-out-of-tasks

**Comment by DanilYachmenev** [comment]
> Hi @gpsaggese @DanilYachmenev @PomazkinG My PRs are waiting for review and are close to being merged now. Can you please assign more issues to me?

will do shortly, yes

> Btw as I checked below guide, I should ping you in Telegram chat in this case. Please let me know your TG channel id. https://github.com/sorrentum/sorrentum/blob/master/docs/General_rules_of_collaboration.md#ping-team-leaders-when-you-are-out-of-tasks

The invite should've reached you yesterday - didnt it?
I'll repeat the invitation rn

**Comment by DanilYachmenev** [comment]
@critrange link to the channel in the pre-last bullet point in this doc
https://github.com/sorrentum/sorrentum/blob/master/docs/Signing_up_for_Sorrentum.md

**Comment by critrange** [comment]
> The invite should've reached you yesterday - didnt it?
> I'll repeat the invitation rn

No yet

> @critrange link to the channel in the pre-last bullet point in this doc https://github.com/sorrentum/sorrentum/blob/master/docs/Signing_up_for_Sorrentum.md

I just joined the TG group.
