### ISSUE TITLE
Unit test `plot_heatmap()` from `core/plotting/correlation.py`

### ISSUE THREAD

**Issue by samarth9008** [sorrentum/sorrentum#443]
We need to unit test `plot_heatmap()` from `core/plotting/correlation.py`

Create a simple test DF for the test and use it to test for  for mode=`clustermap`

Unit testing of a plotting function consists of 2 parts:
- Call the function in a `core/plotting/notebooks/gallery_notebook.ipynb` to demonstrate that it works
- Add a smoke test for the function to `core/plotting/test/test_plots.py`. Use the same inputs as in the gallery

For reference see https://github.com/sorrentum/sorrentum/pull/393

FYI @DanilYachmenev

**Comment by sonaalKant** [comment]
Closing the issue, let me know if anything needs to be done more on this. Thanks
