### ISSUE TITLE
Handle root path purification outliers

### ISSUE THREAD

**Issue by DanilYachmenev** [sorrentum/sorrentum#444]
There is a function `purify_from_environment()` in `helpers/hunit_test.py` that replaces the path to git root dir with `$GIT_ROOT`.
E.g., `/app` (root dir inside a Docker container) is replaced with `$GIT_ROOT`.

However there are some false positives, e.g., `jupyter_core/application.py` is replaced with `jupyter_core$GIT_ROOTlication.py`

The goal is to:
- [x] Modify the text replacement such that `jupyter_core/application.py` remains as-is after applying `purify_from_environment()`
- [x] Add a unit test to https://github.com/sorrentum/sorrentum/blob/master/helpers/test/test_unit_test.py (use the tests in the file as a reference)
Create a new test class `Test_purify_from_environment`
Use `jupyter_core/application.py` as an input for the test
See more detailed info about unit tests in the [doc](https://github.com/sorrentum/sorrentum/blob/master/docs/Unit_tests.md)

FYI @PomazkinG

**Comment by critrange** [comment]
@DanilYachmenev 
So "/app/jupyter_core/application.py" should be replaced with "$GIT_ROOT/jupyter_core/application.py"?

**Comment by samarth9008** [comment]
Yes, but make sure it doesn't replace the `app` in `application.py`

**Comment by critrange** [comment]
> Yes, but make sure it doesn't replace the `app` in `application.py`

Okay, got it. thanks!

**Comment by critrange** [comment]
@DanilYachmenev @samarth9008 
This is current code for this replace.
txt = txt.replace(super_module_path, "$GIT_ROOT")
I am gonna replace this line with below code.
txt = txt.replace(super_module_path+"/", "$GIT_ROOT"+"/")

Do you think it will work for this issue?

**Comment by critrange** [comment]
Okay

**Comment by critrange** [comment]
I added new unit test `Test_purify_from_environment` to helpers/test/test_unit_test.py 
And run docker container by `i docker_bash` and run below command to run the unit test.
`pytest helpers/test/test_unit_test.py::Test_purify_from_environment`
But I got this error.
```
...
helpers/test/test_unit_test.py::Test_purify_from_environment::test1 (0.06 s) FAILED                                                                          [100%]

======================================================================== FAILURES =========================================================================
___________________________________________________________ Test_purify_from_environment.test1 ____________________________________________________________
Traceback (most recent call last):
  File "/app/helpers/test/test_unit_test.py", line 1198, in test1
    self.helper(txt, exp)
  File "/app/helpers/test/test_unit_test.py", line 1188, in helper
    act = hunitest.purify_from_environment(txt)
  File "/app/helpers/hunit_test.py", line 429, in purify_from_environment
    user_name = hsystem.get_user_name()
  File "/app/helpers/hsystem.py", line 73, in get_user_name
    res = getpass.getuser()
  File "/usr/lib/python3.8/getpass.py", line 169, in getuser
    return pwd.getpwuid(os.getuid())[0]
KeyError: 'getpwuid(): uid not found: 1000'
=================================================================== slowest 3 durations ===================================================================
0.08s call     helpers/test/test_unit_test.py::Test_purify_from_environment::test1
0.00s setup    helpers/test/test_unit_test.py::Test_purify_from_environment::test1
0.00s teardown helpers/test/test_unit_test.py::Test_purify_from_environment::test1
================================================================= short test summary info =================================================================
FAILED helpers/test/test_unit_test.py::Test_purify_from_environment::test1 - KeyError: 'getpwuid(): uid not found: 1000'
==================================================================== 1 failed in 2.18s ====================================================================
```
Have you ever faced this error? @DanilYachmenev  @samarth9008

**Comment by critrange** [comment]
> 

1. I use LInux (Ubuntu20.04)
2. This is output of `id` outside Docker
 ```
> id
uid=1000(dato) gid=1000(dato) groups=1000(dato),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),116(lpadmin),126(sambashare),999(docker)
```

I changed code in `devops/docker_build/create_users.sh` like this.
`for current_linux_id in {1000..1050}`
And removed docker image and regenerated it by `i docker_pull`
But same error when run pytest.
@gpsaggese

**Comment by gpsaggese** [comment]
Same problem hit also here https://github.com/sorrentum/sorrentum/issues/446 (you can look at the proposal there)

That

After changing that script `you need to regenerate the Docker image, but this is complicated.

A

**Comment by PomazkinG** [comment]
@critrange when doing `i docker_pull` you pull the image without the fix (i.e. the version from the Docker registry), so it's expected. 

Another option is to do `set_user_name("user_1000")` in the test and see what will happen, see below.  

https://github.com/sorrentum/sorrentum/blob/91d5d489777e6c15ef6783cde2ee9436de5bf106/helpers/hsystem.py#L60-L67

**Comment by gpsaggese** [comment]
Same problem was hit also here https://github.com/sorrentum/sorrentum/issues/446 (you can look at the proposal there)

@PomazkinG is correct
devops/docker_build/create_users.sh is used when the Docker image is generated so it's not enough to pull.
To patch it up you need to: 
```
> i docker_bash
Run the part of the script to create the missing user with uid 1000 from devops/docker_build/create_users.sh
```
Outside Docker, get the docker id from the running docker container and do a Docker commit so that you freeze your local image with the fix inside

@PomazkinG
Do you know if this `set_user_name("user_1000")` works?  If not, can you run this flow (if it makes sense) and maybe push so that we fix the problem for everyone at least with a patch?
I know it's late, so we might need to try tomorrow

**Comment by critrange** [comment]
I added set_user_name("user_1000") in my unit test and the error was gone.
And I should create PR without this code. right?
@gpsaggese  @PomazkinG

**Comment by gpsaggese** [comment]
Yes, just use that `set_user_name` to keep going and you remove it before the PR. We'll fix the root cause better

**Comment by critrange** [comment]
In `purify_from_environment()`, there is part that replace path with "$PWD" after the part replacing with "$GIIT_ROOT"
This is the code.
```
pwd = os.getcwd()
txt = txt.replace(pwd, "$PWD")
```
So after my code is added, "jupyter_core/application.py" is replaced with "jupyter_core$PWDlication.py".
Should I fix it as well in this issue #444?

**Comment by critrange** [comment]
I just created PR for this issue.
https://github.com/sorrentum/sorrentum/pull/464
Who should I assign as reviewer?
@gpsaggese was recommended so I assigned him as reviewer.

**Comment by DanilYachmenev** [comment]
@critrange assign me and @PomazkinG to your PRs first
We comment it first and when it is approved by us we move it to GP ourselves

Read more about it here https://github.com/sorrentum/sorrentum/blob/master/docs/First_review_process.md

**Comment by PomazkinG** [comment]
> Same problem was hit also here #446 (you can look at the proposal there)
> 
> @PomazkinG is correct devops/docker_build/create_users.sh is used when the Docker image is generated so it's not enough to pull. To patch it up you need to:
> 
> ```
> > i docker_bash
> Run the part of the script to create the missing user with uid 1000 from devops/docker_build/create_users.sh
> ```
> 
> Outside Docker, get the docker id from the running docker container and do a Docker commit so that you freeze your local image with the fix inside
> 
> @PomazkinG Do you know if this `set_user_name("user_1000")` works? If not, can you run this flow (if it makes sense) and maybe push so that we fix the problem for everyone at least with a patch? I know it's late, so we might need to try tomorrow

@jsmerix can you please allow me to login / push on the sorrentum side? I understand that it is a horrible hack, but for the on-boarding purposes I believe it would be useful to have a way to quickly patch up the image. Re-releasing is a painful process that we do not want to do frequently.

```
(AccessDeniedException) when calling the GetAuthorizationToken operation: User: arn:aws:iam::623860924167:user/grisha is not authorized to perform: ecr:GetAuthorizationToken on resource: * because no identity-based policy allows the ecr:GetAuthorizationToken action
````

**Comment by PomazkinG** [comment]
done
