### ISSUE TITLE
Telegram gDoc to MD

### ISSUE THREAD

**Issue by samarth9008** [sorrentum/sorrentum#447]
- We need to convert a [Gdoc](https://docs.google.com/document/d/1NplHoFZxL_CVQnTZkrH7BIk3tAHYr2mSzST0Kqt5YPY/edit) of Telegram to Markdown
- Add a reference to this Doc to the [README](https://github.com/sorrentum/sorrentum/blob/master/docs/README.md) under `In-depth docs` section 
- Instructions on how to convert Gdocs to Markdown are [here](https://github.com/sorrentum/sorrentum/blob/master/docs/Documentation_about_guidelines.md#gdocs---markdown)
- Read about the [First Review Process](https://github.com/sorrentum/sorrentum/blob/master/docs/First_review_process.md)
- Lint the markdown file using the [linter](https://github.com/sorrentum/sorrentum/blob/master/dev_scripts/lint_md.sh)
- PR example is https://github.com/sorrentum/sorrentum/pull/347

FYI @DanilYachmenev

**Comment by Dylan-Celli** [comment]
Hey, I think that there was a slight error but I want to double check 
`- Regular chats cannot be accessed via Telegram Desktop version`
I believe that regular chats can be accessed by the Desktop Telegram so I think that this was meant to say
` - Regular chats can be accessed via Telegram Desktop version`
