### ISSUE TITLE
Contributor Scorecard doc to MD

### ISSUE THREAD

**Issue by DanilYachmenev** [sorrentum/sorrentum#450]
- We need to convert a [Gdoc](https://docs.google.com/document/d/1fkLeBPeJ4HLlJK0FanRuYrdIhhZk_X2IabM7oQYwy0g/edit#heading=h.cv11anjvcm2d) of Contributor Scorecard to Markdown
- Add a reference to this Doc to the [README](https://docs.google.com/document/d/1fkLeBPeJ4HLlJK0FanRuYrdIhhZk_X2IabM7oQYwy0g/edit#heading=h.cv11anjvcm2d) under `On-boarding` section 
- Make it look like other docs, remove letter attributes (e.g. put everything in bullet lists, remove `Thanks` etc)
- Instructions on how to convert Gdocs to Markdown are [here](https://github.com/sorrentum/sorrentum/blob/master/docs/Documentation_about_guidelines.md#gdocs---markdown)
- Read about the [First Review Process](https://github.com/sorrentum/sorrentum/blob/master/docs/First_review_process.md)
- Lint the markdown file using the [linter](https://github.com/sorrentum/sorrentum/blob/master/dev_scripts/lint_md.sh)
- PR example is https://github.com/sorrentum/sorrentum/pull/347

Assigning @samarth9008 to re-distribute

**Comment by samarth9008** [comment]
This is the link as you have mentioned over here https://app.asana.com/0/0/1204762351658251/1205104054762906/f

**Comment by gpsaggese** [comment]
Race condition: it was fixed. Specs look good now. Thx

**Comment by sonaalKant** [comment]
I have created a pull request, where do you want me to add the reference of this markdown? @DanilYachmenev

**Comment by DanilYachmenev** [comment]
> convert doc to md issue #450 #454

Add it to the [README](https://github.com/sorrentum/sorrentum#readme) under `On-boarding` section as a 2nd bullet point
