### ISSUE TITLE
Unit test `plot_qq()` from `core/plotting/normality.py`

### ISSUE THREAD

**Issue by samarth9008** [sorrentum/sorrentum#455]
We need to unit test `plot_qq()` from `core/plotting/normality.py`

Create a simple test series for the test and use it to test

Unit testing of a plotting function consists of 2 parts:
- Call the function in a `core/plotting/notebooks/gallery_notebook.ipynb` to demonstrate that it works
- Add a smoke test for the function to `core/plotting/test/test_plots.py`. Use the same inputs as in the gallery

For reference see https://github.com/sorrentum/sorrentum/pull/393

FYI @DanilYachmenev

**Comment by samarth9008** [comment]
Make sure you still have to complete the unit tests of the previous task once it is done.

**Comment by KangmingL** [comment]
Yeah, I got it done. And GP said he will finish it when he start using it.

**Comment by samarth9008** [comment]
Yeah but you still have to implement the unit tests once it is done.

**Comment by Sameep2808** [comment]
Merged
