### ISSUE TITLE
Unit test `plot_effective_correlation_rank()` from `core/plotting/correlation.py`

### ISSUE THREAD

**Issue by samarth9008** [sorrentum/sorrentum#456]
We need to unit test `plot_effective_correlation_rank()` from `core/plotting/correlation.py`

Create a simple test DF for the test.

Unit testing of a plotting function consists of 2 parts:
- Call the function in a `core/plotting/notebooks/gallery_notebook.ipynb` to demonstrate that it works
- Add a smoke test for the function to `core/plotting/test/test_plots.py`. Use the same inputs as in the gallery

For reference see https://github.com/sorrentum/sorrentum/pull/393

FYI @DanilYachmenev

**Comment by samarth9008** [comment]
@DanilYachmenev Can you make sure if everything is correct in the spec related to the function?

**Comment by DanilYachmenev** [comment]
All good

an addition: add 2 tests
- 1 for `q_values=None`
- 1 for `q_values=[some list of vals]`
