### ISSUE TITLE
Unit Test `plot_rets_signal_analysis()`

### ISSUE THREAD

**Issue by samarth9008** [sorrentum/sorrentum#460]
We need to unit test `plot_rets_signal_analysis()` from [dataflow/model/model_plotter.py](https://github.com/sorrentum/sorrentum/blob/8f557a920251a972b1f6e3190141f03eee226048/dataflow/model/model_plotter.py#L50)

Unit testing of a plotting function consists of 2 parts:
- Call the function in a `core/plotting/notebooks/gallery_notebook.ipynb` to demonstrate that it works
- Add a smoke test for the function to `core/plotting/test/test_plots.py`. Use the same inputs as in the gallery

For reference see https://github.com/sorrentum/sorrentum/pull/393

FYI @DanilYachmenev

**Comment by samarth9008** [comment]
@DanilYachmenev Can you please take a look and see if anything is missing from the specs?

**Comment by DanilYachmenev** [comment]
In fact there is already a smoke test for this function in `dataflow/model/test/test_model_plotter.py`
therefore, we only need to do the 1st bullet point: call the function in a `core/plotting/notebooks/gallery_notebook.ipynb` to demonstrate that it works

you can see the test in `dataflow/model/test/test_model_plotter.py::TestModelPlotter1::test_plot_rets_signal_analysis1` to see the inputs

**Comment by samarth9008** [comment]
Closing as completed.
