### ISSUE TITLE
Unit Test `plot_performance()`

### ISSUE THREAD

**Issue by samarth9008** [sorrentum/sorrentum#462]
We need to unit test `plot_performance()` from [dataflow/model/model_plotter.py](https://github.com/sorrentum/sorrentum/blob/8f557a920251a972b1f6e3190141f03eee226048/dataflow/model/model_plotter.py#L123)

Unit testing of a plotting function consists of 2 parts:
- Call the function in a `core/plotting/notebooks/gallery_notebook.ipynb` to demonstrate that it works
- Add a smoke test for the function to `core/plotting/test/test_plots.py`. Use the same inputs as in the gallery

For reference see https://github.com/sorrentum/sorrentum/pull/393

FYI @DanilYachmenev

**Comment by zli00185** [comment]
There is a test file in the path `dataflow/model/test/test_model_plotter.py`. Should I add the smoke test to `core/plotting/test/test_plots.py` or `dataflow/model/test/test_model_plotter.py` ?

**Comment by DanilYachmenev** [comment]
@zli00185, keep the test in `dataflow/model/test/test_model_plotter.py`, no  need to add a new one

Note that the test method where it is being called is duplicated: there are 2 `test_plot_rets_signal_analysis1` methods in `TestModelPlotter1` and one is calling `plot_performance`

Could you pls
- rename the test method where `plot_performance()` is called accordingly
- run all the tests in `TestModelPlotter1` and confirm that they all are being called and passed

And thats it for the test
then use the same input and call this function in `core/plotting/notebooks/gallery_notebook.ipynb`

**Comment by zli00185** [comment]
Should I remove param `self` in `def _get_example_model_plotter(self):` from `dataflow/model/test/test_model_plotter.py` since it was not used at all in the function?

**Comment by DanilYachmenev** [comment]
done

**Comment by DanilYachmenev** [comment]
Done

@gpsaggese I will move the plotting gallery notebook and plotting unit test file in one PR to `cmamp` since there were many other PRs related to them
