### ISSUE TITLE
Test dassert_file_extension()

### ISSUE THREAD

**Issue by DanilYachmenev** [sorrentum/sorrentum#466]
The function is: https://github.com/sorrentum/sorrentum/blob/master/helpers/hdbg.py#L794C5-L794C27

Do not forget to remove the TODO

Create a new test class in https://github.com/sorrentum/sorrentum/blob/master/helpers/test/test_dbg.py

Test cases:
- [x] Extension is string: e.g., `.csv.gz` and file name ends with `.csv.gz`
- [x] Extension is a list: e.g., `[“.csv.gz”, “csv”]` and file name ends with `csv`
- [x] Incorrect extension: e.g., file name ends with `.txt` while the extensions are “.csv, .csv.gz”
    - Use self.AssertRaises to catch an assertion, e.g., see https://github.com/sorrentum/sorrentum/blob/master/helpers/test/test_dbg.py#L63

Read more about unit tests in the corresponding [doc](https://github.com/sorrentum/sorrentum/blob/master/docs/Unit_tests.md)

FYI @PomazkinG

**Comment by dreamcatcher0101** [comment]
For the Case1:
If we assume that the filename ends with `.csv.gz`, the extension must be `.gz`.
Then the result is `failed`. I think it's needed to modify the `dassert_file_extension()` from [helpers/test_dbg.py](https://github.com/sorrentum/sorrentum/blob/master/helpers/test/test_dbg.py). Is it Ok to modify?

**Comment by PomazkinG** [comment]
@dreamcatcher0101 feel free to modify

the expected outcome is:
- file name ends with `.csv.gz`
- `.csv.gz` is in the list of extensions
- no assertion is raised

**Comment by DanilYachmenev** [comment]
> Hi @DanilYachmenev For the Case1: If we assume that the extension is `.csv.gz` and the filename ends with `.csv.gz`, the extension must be `.gz`. Then the result is `failed`. Is it correct? I think it's needed to modify the `dassert_file_extension()` from [helpers/test_dbg.py](https://github.com/sorrentum/sorrentum/blob/master/helpers/test/test_dbg.py) to fix it. Is it Ok to modify?

Yes, `act_ext = os.path.splitext(file_name)[-1].lower()` in the function is not processing `.csv.gz` extensions correctly
so modify it and add a unit test for such case pls

**Comment by DanilYachmenev** [comment]
done via #477, closing
