### ISSUE TITLE
Remove unused functions from `dataflow/system/system_builder_utils.py`

### ISSUE THREAD

**Issue by DanilYachmenev** [sorrentum/sorrentum#468]
The goal is to kill the functions from `dataflow/system/system_builder_utils.py` that are not used anywhere:
- [x] `get_RealTimeDag_from_System()`
- [x] `apply_log_dir()`
- [x] `get_realtime_DagRunner_from_system()`

check that functions are not used anywhere and remove them with all the corresponding tests and mentions (if there are any)

run linter on every touched file

@PomazkinG

**Comment by samarth9008** [comment]
Whats the update? @brandonnsc

**Comment by brandonnsc** [comment]
> Whats the update? @brandonnsc

I am currently discussing the details of the offer with GP. Additionally, my parents have recently come to the US to visit me. We haven't seen each other for three years, so I'm spending some time traveling with them in LA.

**Comment by gpsaggese** [comment]
@samarth9008 let's reroute, but no rush

**Comment by DanilYachmenev** [comment]
Re-routed to @aaryapatel100

**Comment by DanilYachmenev** [comment]
Re-routed to @Sameep2808

**Comment by Sameep2808** [comment]
@DanilYachmenev I was not able to find any reference for the function get_RealTimeDag_from_System() but its being used in [dev_scripts/cleanup_scripts/CMTask2829_Rename_functions_to_use_object_names_20220916.sh](https://github.com/sorrentum/sorrentum/blob/fb1e591e1ce1f8233ca14e68b36a674f6f795bb6/dev_scripts/cleanup_scripts/CMTask2829_Rename_functions_to_use_object_names_20220916.sh#L37) but found out that even that is not getting used further. But just to make sure no ones working on it and I can delete and make the final commit. 

![Screenshot from 2023-08-18 15-42-27](https://github.com/sorrentum/sorrentum/assets/85573083/1141f232-9d81-467e-9170-90ac08c08494)

**Comment by gpsaggese** [comment]
@Sameep2808

If you are blocked or need more issues (if you are really done with an issue) you can ping @DanilYachmenev and @samarth9008 on the TG chat

FYI you can use permalinks besides screenshots (which we don't like that much)
https://github.com/sorrentum/sorrentum/blob/fb1e591e1ce1f8233ca14e68b36a674f6f795bb6/dataflow/system/system_builder_utils.py#L10C1-L10C1

@DanilYachmenev this is one of the PR that we should merge to cmamp once it's done since it's painful to integrate

**Comment by Sameep2808** [comment]
@gpsaggese Yes sure I was just not on the TG chat hence communicated here. Can you share the link or ids for TG chat.
Yes I understand I'll make sure to avoid images next time

**Comment by gpsaggese** [comment]
The link to TG is in the documentation / on-boarding
