### ISSUE TITLE
On-board Gurtajbir Herr Aka gurtajbir

### ISSUE THREAD

**Issue by jsmerix** [sorrentum/sorrentum#470]
Please follow this checklist. Post any errors you face in this issue.
 
- [x] Acknowledge the pledge to put time in the project [here](https://github.com/sorrentum/sorrentum/blob/master/README.md#commitment-to-Contribute)
- [x] Read [How to organize your work](https://github.com/sorrentum/sorrentum/blob/master/docs/How_to_organize_your_work.md)
- [x] Read [Quick start for developing](https://github.com/sorrentum/sorrentum/blob/master/docs/Quick_start_for_developing.md)
- [x] Make sure the [Docker dev container](https://github.com/sorrentum/sorrentum/blob/master/docs/Quick_start_for_developing.md#sorrentum-dev-docker-container-aka-dev-container-cmamp-container) works
- [x] Make sure the [unit tests](https://github.com/sorrentum/sorrentum/blob/master/docs/Unit_tests.md) run successfully
- [x] Read [Sorrentum Python coding style guide](https://github.com/sorrentum/sorrentum/blob/master/docs/Coding_Style_Guide.md)
- [x] Fork, star, watch the Sorrentum repo so that GitHub promotes our repo (we gotta work the system)
- [x] Get assigned a warm-up issue
- [x] Learn about the [Morning Email](https://github.com/sorrentum/sorrentum/blob/master/documentation/general/general.md#morning-email)
- [x] How to do a [review](https://github.com/sorrentum/sorrentum/blob/master/docs/First_review_process.md)
- [ ] If you are graduating soon and you would like to get a full-time job in one of the companies in the Sorrentum ecosystem reach out to GP at gp@sorrentum.org

**Comment by gurtajbir** [comment]
Hi. I just ran the unit tests and got the following output after the tests ran. Is this the expected output ?

`========================================== 97 failed, 2139 passed, 207 skipped, 191 deselected, 2 xfailed, 15 errors, 79 rerun in 1271.00s (0:21:10) ==========================================
10:14:25 @ 2023-08-01 06:05:38 - INFO  hcache.py clear_global_cache:292 Before clear_global_cache: 'global mem' cache: path='/mnt/tmpfs/tmp.cache.mem', size=28.0 KB
10:14:25 @ 2023-08-01 06:05:38 - WARN  hcache.py clear_global_cache:293 Resetting 'global mem' cache '/mnt/tmpfs/tmp.cache.mem'
10:14:25 @ 2023-08-01 06:05:38 - WARN  hcache.py clear_global_cache:303 Destroying '/mnt/tmpfs/tmp.cache.mem' ...
10:14:25 @ 2023-08-01 06:05:38 - INFO  hcache.py clear_global_cache:319 After clear_global_cache: 'global mem' cache: path='/mnt/tmpfs/tmp.cache.mem', size=nan
ERROR: 1`

**Comment by samarth9008** [comment]
Yes it is expected.

**Comment by gurtajbir** [comment]
Thanks @samarth9008  for clarifying. @jsmerix  Can you please assign me a warm-up issue?

**Comment by samarth9008** [comment]
Feel free to close it once you complete the checklist.

**Comment by gurtajbir** [comment]
The link to information about the morning email is broken. Could you please point me in the right direction?

**Comment by samarth9008** [comment]
https://github.com/sorrentum/sorrentum/blob/master/docs/General_rules_of_collaboration.md#morning-email
