### ISSUE TITLE
Create a function that converts str timestamps to pd.Timestamp

### ISSUE THREAD

**Issue by DanilYachmenev** [sorrentum/sorrentum#474]
Add the function to `helpers/hdatetime.py`

Add unit tests to `helpers/test/test_hdatetime.py`

Inputs to the function:
- Timestamp as string, e.g., `"20230523_150513"`
- Timezone info
- Optional: date format (e.g., `%Y%m%d_%H%M%S`). if `None`, infer automatically

Output:
- pd.Timestamp with tz info, e.g., `Timestamp('2023-02-13 12:05:00+0000', tz='UTC')`

FYI @PomazkinG

**Comment by critrange** [comment]
@DanilYachmenev What should return when fail to parse str timestamp?

**Comment by DanilYachmenev** [comment]
> @DanilYachmenev What should return when fail to parse str timestamp?

You need to add a regex assert that the passed string has the desired format
so throw an error if format is incorrect

**Comment by critrange** [comment]
> You need to add a regex assert that the passed string has the desired format
> so throw an error if format is incorrect

IMO, regex is need for this feature if we use below pd function.
`pd.to_datetime(datetime_str, format=format)`
It throws ValueError if datetime_str doesn't match format.

**Comment by critrange** [comment]
> You need to add a regex assert that the passed string has the desired format
> so throw an error if format is incorrect

IMO, regex is not need for this feature if we use below pd function.
pd.to_datetime(datetime_str, format=format)
It throws ValueError if datetime_str doesn't match format.

**Comment by critrange** [comment]
PR: https://github.com/sorrentum/sorrentum/pull/478
