### ISSUE TITLE
Unit test `plot_autocorrelation()`

### ISSUE THREAD

**Issue by samarth9008** [sorrentum/sorrentum#483]
We need to unit test `plot_autocorrelation()` from [core/plotting/misc_plotting.py](https://github.com/sorrentum/sorrentum/blob/master/core/plotting/misc_plotting.py#L407)

Unit testing of a plotting function consists of 2 parts:
- Call the function in a `core/notebooks/gallery_signal_processing.ipynb` to check that it works (do not commit, just confim how it looks in the PR with a screenshot)
- Add a smoke test for the function to `core/plotting/test/test_plots.py`. Use the same inputs as in the `core/notebooks/gallery_signal_processing.ipynb`

For reference see https://github.com/sorrentum/sorrentum/pull/393

FYI @DanilYachmenev

**Comment by samarth9008** [comment]
@DanilYachmenev Can you PTAL bcz the doc says `Already in a gallery but not covered`?

**Comment by DanilYachmenev** [comment]
@samarth9008 I've updated the issue desc accordingly
@Ro0k1e consider the issue description correct and implement pls

**Comment by DanilYachmenev** [comment]
@Ro0k1e any progress? ETA?

**Comment by DanilYachmenev** [comment]
done
