### ISSUE TITLE
Convert Hubstaff gDoc to Markdown

### ISSUE THREAD

**Issue by DanilYachmenev** [sorrentum/sorrentum#489]
Warm-up issue

- We need to convert a [Gdoc](https://docs.google.com/document/d/1Re-nJp-bk80YwIYuQkqVf4ZnEsXahbqt6IIKvHb-2f0/edit?usp=sharing) of Hubstaff to Markdown
- Instructions on how to convert Gdocs to Markdown are [here](https://github.com/sorrentum/sorrentum/blob/master/docs/Documentation_about_guidelines.md#gdocs---markdown)
- Read about the [First Review Process](https://github.com/sorrentum/sorrentum/blob/master/docs/First_review_process.md)
- Lint the markdown file using the [linter](https://github.com/sorrentum/sorrentum/blob/master/dev_scripts/lint_md.sh)
- PR example is https://github.com/sorrentum/sorrentum/pull/397
- Create markdown in `docs` folder
- Add a link to this file to `sorrentum/README.md` to `In-depth docs` section

FYI @samarth9008

**Comment by samarth9008** [comment]
How's the progress?

**Comment by gpsaggese** [comment]
@gurtajbir we appreciate the SIY (solve-it-yourself) approach.

You can post the error here so we can see if it's a set up issue vs a Git problem.

**Comment by gurtajbir** [comment]
@gpsaggese Appreciate it. Will do from next time.

**Comment by DanilYachmenev** [comment]
@jainamp14 this is your first warm-up issue

ignore already implemented work, start from scratch
however you can use it for reference and inspiration

**Comment by DanilYachmenev** [comment]
FYI @rheenina

**Comment by rheenina** [comment]
@jainamp14 tag me when it's ready for review

**Comment by jainamp14** [comment]
Thank you I will do that and I am still reviewing things prior to warm-up in the checklist. Hoping to get that done today and will start the warm-up Monday.

**Comment by jainamp14** [comment]
@rheenina I have completed my first warm-up task. Could you please review it? Thank you.

**Comment by rheenina** [comment]
@samarth9008 could pls integrate https://github.com/sorrentum/sorrentum/pull/578 to cmamp

**Comment by rheenina** [comment]
Integrated to cmamp, closing
