### ISSUE TITLE
Create brownie tests for DaoSwap

### ISSUE THREAD

**Issue by tamriq** [sorrentum/sorrentum#49]
Create local tests in `dao_swap/test` dir to run with `brownie test` command from /dao_swap project root.
Since DaoSwap should interact with ERC20 tokens, to test its flow we need first create mock erc20 token contract and deploy it to local network (within test script).
 
About mock contracts: https://soliditydeveloper.com/mocking-contracts
Guide to testing ethereum smart contracts with brownie+pytest: https://iamdefinitelyahuman.medium.com/an-in-depth-guide-to-testing-ethereum-smart-contracts-3e07b8c38755

**Comment by samarth9008** [comment]
@gpsaggese @tamriq 

I was going through the DaoSwap contract and I believe I have understood the flow of it. I was wondering if I can move forward with this task if there are no changes to be made to the DaoSwap contract. Please let me know.

**Comment by tamriq** [comment]
In my opinion this task is a little outdated as the idea of "dao swap" has slightly changed since the moment DaoSwap.sol was created. The flow in new DaoSwap & DaoCross is in fact the same and a lot of code will overlap, but the matching algorithm is the different.
I'm in the process of implementing DaoCross, and once the first version is ready I'll create a task for you to test its flow. But this issue should be closed — the code in this directory will be replaced to the whitepaper version of DaoSwap further.

@gpsaggese What do u think?
