### ISSUE TITLE
`Development - Diagnosing server/network issues` gdoc to MD

### ISSUE THREAD

**Issue by samarth9008** [sorrentum/sorrentum#491]
Warm-up issue

- We need to convert a [Gdoc](https://docs.google.com/document/d/1Tef2bkY5n1RrWD7yrw8_DAc8dn4eq22BUy-hdj5PEb0/edit#heading=h.r5kmj9atbe45) of Development - Diagnosing server/network issues to Markdown
- Instructions on how to convert Gdocs to Markdown are [here](https://github.com/sorrentum/sorrentum/blob/master/docs/Documentation_about_guidelines.md#gdocs---markdown)
- Read about the [First Review Process](https://github.com/sorrentum/sorrentum/blob/master/docs/First_review_process.md)
- Lint the markdown file using the [linter](https://github.com/sorrentum/sorrentum/blob/master/dev_scripts/lint_md.sh)
- PR example is https://github.com/sorrentum/sorrentum/pull/397
- Create markdown in `docs` folder
- Add a link to this file to `sorrentum/README.md` to `In-depth docs` section

FYI @DanilYachmenev

**Comment by aaryapatel100** [comment]
Is the convert_docx_to_markdown.py deprecated because even after pulling its just an empty file?

**Comment by DanilYachmenev** [comment]
> Is the convert_docx_to_markdown.py deprecated because even after pulling its just an empty file?

weird, did you check out the [full path](https://github.com/sorrentum/sorrentum/blob/master/dev_scripts/convert_docx_to_markdown.py) `dev_scripts/convert_docx_to_markdown.py`?

**Comment by DanilYachmenev** [comment]
try to pull master to your branch
it should definitely be there

if it does not appear pls share the output for 
`> ls dev_scripts `

**Comment by DanilYachmenev** [comment]
@aaryapatel100 could you find a script file?
if not, see my previous message and pls share the contents of your `/dev_scripts` folder

**Comment by aaryapatel100** [comment]
Here is the output after running `git pull`:
```
aaryapatel100@aaryapatel100VM:~/src/sorrentum1$ cd dev_scripts
aaryapatel100@aaryapatel100VM:~/src/sorrentum1/dev_scripts$ ls
ack                          convert_docx_to_markdown.sh  find_unused_golden_files.py    jack                  lib_tasks_data_reconcile.py  poetry                      run_profiling.sh             timestamp              vigit
aws                          create_class_diagram.sh      fix_perms.sh                   jackipynb             lint_md.sh                   print_paths.sh              save_screenshot.sh           tmux_amp.sh            vigitp
call_graph.sh                ctags.sh                     git                            jackmd                lint_solidity.sh             process_prof.py             scraping_script              tmux_kill_session.sh   vil
cie                          cvxpy_setup                  github                         jackmk                manage_cache.py              README.md                   script_skeleton.py           to_clean               vit
cleanup_scripts              diff_to_vimdiff.py           go_amp.sh                      jackppy               measure_import_times.py      release_encrypted_model.sh  setenv_amp.configure_env.sh  toml_merge.py          viw
clean_up_text_files.sh       docker_clean_all.sh          grsync.py                      jackpy                mkbak                        release_sorrentum           setenv_amp.sh                traceback_to_cfile.py  zip_files.py
client_setup                 docker_clean_postgres.sh     helpers.sh                     jackpyc               mk_targets                   remove_empty_lines.sh       string_to_file.py            transform_skeleton.py
code_stats.sh                email_notify.py              infra                          jacktxt               notebooks                    remove_escape_chars.py      sync_repo.sh                 tree.sh
compile_all.py               encrypt_model.py             __init__.py                    kga                   old                          remove_jupyter_metadata.sh  test                         url.py
compress_files.sh            export_vars.sh               integrate_repos                latex                 parallel_script_skeleton.py  remove_redundant_paths.sh   testing                      viack
convert_docx_to_markdown.py  ffind.py                     invite_github_collaborator.py  lib_tasks_data_qa.py  path                         replace_text.py             tg.py                        vic
```
and then opening the convert_docx_to_markdown.py on text editor just shows an empty file.

**Comment by DanilYachmenev** [comment]
@aaryapatel100 well, it seems that the file is here
also could you open the [link](https://github.com/sorrentum/sorrentum/blob/master/dev_scripts/convert_docx_to_markdown.py)?

if nothing works I suggest you to re-install the repo and try again
because the file is here and it seems like you can reach it out as well
so the problem is in the set-up

**Comment by shab95** [comment]
Need access to google doc please
