### ISSUE TITLE
Expose plotting gallery notebook config

### ISSUE THREAD

**Issue by DanilYachmenev** [sorrentum/sorrentum#492]
Currently `core/plotting/notebooks/gallery_notebook.ipynb` is just being run without its own config
This is why we haven't set global params in it and use a dummy config in `core/plotting/test/test_gallery_notebook.py`

We need to:
- [x] Expose a notebook config with just `"figsize": (20, 10),` for now and expose it wherever `figsize` is used in the notebook currently
- [x] Update the config in `core/plotting/test/test_gallery_notebook.py` and make sure the test pass

For reference you can see how it is done in `oms/notebooks/Master_system_reconciliation_fast.ipynb` or some other master notebooks

FYI @samarth9008

**Comment by dchoi127** [comment]
@DanilYachmenev It appears that `oms/notebooks/Master_system_reconciliation_fast.ipynb` calls a function in reconcilation.py named `build_reconciliation_configs()` which then builds a cconfig.ConfigList. Should I follow a similar approach of building the config from `build_reconciliation_configs()` but directly build it in the notebook?

**Comment by DanilYachmenev** [comment]
done
