### ISSUE TITLE
LIN: Rename the gsheets in doc and code

### ISSUE THREAD

**Issue by gpsaggese** [sorrentum/sorrentum#493]
We want to rename the gsheets
<img width="741" alt="image" src="https://github.com/sorrentum/sorrentum/assets/33238329/20c8d8ba-3700-4cb5-88ff-1a824b136c14">

so that the flow is clear in both the notebooks and in the documentation (https://docs.google.com/document/d/1dfAVMJZtHtQ3sX7UHwpXNAWPiJs17w0V8FlsOI7a32M/edit)
like:

- Sn_search5.step1.export_search
- Sn_search5.step2.export_search.filtered
- Sn_search5.step3.export_profile
- Sn_search5.step4.export_profile.filtered

**Comment by yiyunlei** [comment]
Rename them as shown below to make them more concise and clear:
<img width="862" alt="image" src="https://github.com/sorrentum/sorrentum/assets/42398651/e666861e-e3b0-4cd2-9ab5-032a16e1edec">
