### ISSUE TITLE
Fix each cause of issues when running regressions

### ISSUE THREAD

**Issue by gpsaggese** [sorrentum/sorrentum#501]
From #283

Create a test list for each class of broken tests based on
https://docs.google.com/document/d/1Qm54LwNRlBwzYroDGviW32NevK_V8L4Sufsg5u6IKwI/edit#heading=h.6bhp1lld1a4v

We want to create a GH issue for each of the issues we need to propose a solution (e.g., fix so that it works outside our server, disabled since it can't run outside CK infra)

At the end the regressions should pass with a subset of the tests skipped only when running CK infra

**Comment by LibertasSpZ** [comment]
For some reason I get access denied for that doc now.

**Comment by gpsaggese** [comment]
Let's add a switch to force a test list to run. This should be a separate issue.

The workflow is going to be like:
- enable a subset of tests from command line (e.g., `requires_ck_infra` that would be skipped otherwise)
- classify failures like in the gdoc https://docs.google.com/document/d/1Qm54LwNRlBwzYroDGviW32NevK_V8L4Sufsg5u6IKwI/edit
- file an issue for each root cause
- decide why it fails, if it can be fixed, and how
   - e.g., the timeout issue is fixed by increasing the timeout)
   - e.g., `Got permission denied while trying to connect to the Docker daemon socket at` we will mark it as `requires_dind` and skip them (so is_laptop implies `requires_dind`)

Does it make sense?

**Comment by LibertasSpZ** [comment]
Yes. I'll start by creating a branch and adding a switch to allow only the `requires_ck_infra` to run, and create a new issue for each type of failure / error.
