### ISSUE TITLE
Disable timeout for tests when running outside of CI

### ISSUE THREAD

**Issue by gpsaggese** [sorrentum/sorrentum#502]
Thanks. Took a glance. Maybe for the timeouts [Category 1] we can mark them as `slow` instead.

_Originally posted by @LibertasSpZ in https://github.com/sorrentum/sorrentum/issues/283#issuecomment-1656294100_

The proposed solution for this is in
           
https://docs.google.com/document/d/1Qm54LwNRlBwzYroDGviW32NevK_V8L4Sufsg5u6IKwI/edit#heading=h.6bhp1lld1a4v

We want to make the timeout in `pytest` larger when we are running the tests outside of GH actions / CI, when we build the command line option for `run_fast_tests`

In practice, it's something like in `_build_run_command_line`
```
if is_ck_server() or CI:
        # Make the timeout much larger.
        pytest_opts_tmp.append("-o timeout_func_only=true")
        timeout_secs *= 10
        pytest_opts_tmp.append(f"--timeout {timeout_in_sec}")
```

**Comment by LibertasSpZ** [comment]
So after merging #500 today we have the following in `helpers/lib_tasks_pytest.py`

   ```
   skip_ck_infra_tests = not hserver.is_dev_ck()
      if skip_ck_infra_tests:
          _LOG.warning("Skipping CK infra related tasks")
          skipped_tests += " and not requires_ck_infra"
          timeout_in_sec *= 10
   ```


I believe that already disables [or significantly extends] timeouts for fast tests running outside of ck infrastructure.

**Comment by gpsaggese** [comment]
Done
