### ISSUE TITLE
Create brownie test script for TimeLock contract

### ISSUE THREAD

**Issue by tamriq** [sorrentum/sorrentum#51]
Test the flow of TimeLock contract locally with brownie test. Create local tests in `tokens/test` dir to run with `brownie test` command from /tokens project root.
Since TimeLock should interact with ERC20 tokens, to test its flow we need first create mock erc20 token contract and deploy it to local network (within test script).

The common flow of TimeLock contract is already described in deployment notebook (not merged to this repo yet), so in fact the goal is to transform the web3.py code form the notebook to brownie test script.

Refs:
- link to deployment notebook https://github.com/sorrentum/sorrentum/blob/master/defi/tokens/CmTask3864_deploy_vesting_contract.ipynb
- about mock contracts: https://soliditydeveloper.com/mocking-contracts
- guide to testing ethereum smart contracts with brownie+pytest: https://iamdefinitelyahuman.medium.com/an-in-depth-guide-to-testing-ethereum-smart-contracts-3e07b8c38755

**Comment by samarth9008** [comment]
@tamriq Can you please explain how this deployment notebook and testing scripts are related? Whats the use of this notebook? Is it for deploying the contract?

**Comment by tamriq** [comment]
@samarth9008 
1) We use the notebook to deploy the contract to testnet (Goeli) or mainnet. In fact we could do the same with deployment script and run it through CLI, but on this stage we prefer to have it as the notebook since it's easier to follow the process step by step.
2) After the deployment I used to check the contract functionality, you can find this part in 'Interactions' section of the notebook. I just check if the contract functions work as expected. These checks work exactly like tests, but are written with bulky web3.py syntax.
3) Brownie testing scripts allow us to run tests in local environment, so we can just run them each time we re-compile the contract to make sure contract works as it should.
4) Your goal is to cover with brownie tests the whole contract functionality, the deployment notebook just shows you the test cases you can use.

**Comment by samarth9008** [comment]
Hello @tamriq 

In the TokenTimeLock contract, according to my understanding from the deployment notebook, we are passing the address  where ERC20 token is deployed as a constructor argument of this contract. Additionally, in the releaseToken() function "token.transfer(msg.sender, participants[msg.sender].amount);" (token refers to the address where our ERC20 token is deployed) will transfer "amount" number of tokens from ERC20 to the caller of the function. So how does the deployed address of ERC20 contract is getting tokens? Because when I run test it shows me "ERC20: transfer amount exceeds balance". I have pushed the code to "Issue51_Create_brownie_test_script_for_TimeLock_Contract" branch. Please help me with this.

**Comment by tamriq** [comment]
To re-create the natural flow of TimeLock contract we need:
1) Deploy some ERC20 token to local network as part of the test. You can import the code of SorrentumToken.sol or create some mock ERC20 specially
 for the test. The example of mock ERC20:
```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.9;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";

contract MyToken is ERC20 {
    constructor() ERC20("MyToken", "MTK") {
        _mint(msg.sender, 1000 * 10 ** decimals());
    }
}
```
2) While u deploy the token the address from which u deployed automatically gets tokens. In the example above `_mint(msg.sender, 1000 * 10 ** decimals());` sends to your address 1000 tokens.
3) After u deploy you can get the address of the token. Initialize TimeLock contract with token address and deploy.
4) Send tokens to TimeLock contract. Run `token.transfer(timeLockAddr, amount, {"from": accountWithTokens})`. accountWithTokens is the account from which u deployed the token.

Some details about how ERC20 interface works:

1) Balances. The contract maintains a mapping of addresses to their respective token balances. This mapping is used to keep track of each user's token holdings.

2) Transfers. The contract provides functions for transferring tokens between addresses, including `token.transfer()` for direct transfers and `token.transferFrom()` for transfers that have been approved by the token owner.

3) Approvals. The ERC20 contract allows token owners to grant permission to other addresses (typically, smart contracts) to spend a specific amount of their tokens. This is done using the `token.approve()` function, which updates an allowance mapping. The approved spender can then use `token.transferFrom()` to transfer the allowed tokens on behalf of the token owner.
