### ISSUE TITLE
Clean-up documentation

### ISSUE THREAD

**Issue by DanilYachmenev** [sorrentum/sorrentum#511]
We need to do some minor clean-ups to the `/docs` folder and also to [README](https://github.com/sorrentum/sorrentum#readme)

It is big but in fact it mostly renamings, adding pointers, and running linter, so should be easy one

- [ ] Refactor `docs/How_to_integrate_repos.md`
    - Add a header `# How to integrate repos`
    - Add a pointer to README in `Project management` section at the bottom of it (with small desc of what is it about)
    - Run `lint_md` on the doc and create a correct [TOC]
- [ ] Refactor `docs/DataFlow.md`
    - Add a pointer to README in `In-depth docs` section
    - Run `lint_md` on the doc and create a correct [TOC]
- [ ] Refactor `docs/DataPull.md`
    - Add a pointer to README in `In-depth docs` section
    - Run `lint_md` on the doc and create a correct [TOC]
- [ ] Add a pointer to `docs/Scrum_methodology.md` to README in `Learn how to become efficient at developing` section
- [ ] Add a pointer to `docs/Workflows.md` to README at the end of  `In-depth docs` section
- [ ] Check all the ref links on the README and update if some are broken
- [ ] Check if all the docs from `/docs` folder are referenced anywhere in the README and report here if not

FYI @samarth9008

**Comment by DanilYachmenev** [comment]
@samarth9008 feel free to add any documentation improvements that you may encounter
I will distribute it to available interns from here

Also feel free the pick a not yet filed bullet points for a warm-up issues

**Comment by Dylan-Celli** [comment]
> Also feel free the pick a not yet filed bullet points for a warm-up issues

Since I am assigned to the issue, should I just address all the issues unless told that it has been assigned to someone else?

**Comment by DanilYachmenev** [comment]
> > Also feel free the pick a not yet filed bullet points for a warm-up issues
> 
> Since I am assigned to the issue, should I just address all the issues unless told that it has been assigned to someone else?

you've been assigned with #513 which is a part of this task
lets do everything by little stapes with paying attention to details

**Comment by dhimuk** [comment]
https://github.com/sorrentum/sorrentum/pull/534#issuecomment-1674115040

**Comment by DanilYachmenev** [comment]
done
