### ISSUE TITLE
Clean-up `PyCharm` doc

### ISSUE THREAD

**Issue by DanilYachmenev** [sorrentum/sorrentum#514]
We need to clean-up `docs/Tools-PyCharm.md`:
- [x] Rename it to `PyCharm.md`
- [x] Add a header as the first line `# Pycharm ` 
- [x] Run `lint_md` on the doc and create a correct [TOC](https://github.com/sorrentum/sorrentum/blob/master/docs/Documentation_about_guidelines.md#table-of-content-toc) correctly
- [x] Add a ref link to it to [README](https://github.com/sorrentum/sorrentum#readme) in `In-depth docs` section 

There is a [documentation](https://github.com/sorrentum/sorrentum/blob/master/docs/Documentation_about_guidelines.md) about Gdocs that could help

**Comment by samarth9008** [comment]
Whats the update? @Ro0k1e

**Comment by samarth9008** [comment]
Re-routing it to @dhimuk

**Comment by DanilYachmenev** [comment]
@zli00185 lets implement this clean-up before moving documentation to [RTD](https://github.com/sorrentum/sorrentum/issues/516), should be an easy fix

You can finish work in https://github.com/sorrentum/sorrentum/pull/540 or use it as a reference

**Comment by samarth9008** [comment]
Closing as all the PR is merged.
