### ISSUE TITLE
Follow up for PB API

### ISSUE THREAD

**Issue by yiyunlei** [sorrentum/sorrentum#522]
Follow up for #515. 
Resolve the conversations in #515 PR later.
- Update to not use `hio.to_file()`

**Comment by gpsaggese** [comment]
Very good tracking this.

You can also reuse the same #515 and just do a PR with a name like
`SorrTask487_Automate_extracting_the_PB_results_and_download_to_local_storage_2`

**Comment by yiyunlei** [comment]
@gpsaggese @DanilYachmenev @samarth9008

Could you help me take a look at this issue?

https://github.com/sorrentum/sorrentum/pull/515#discussion_r1284895575

hio.to_file() seems like having an encoding issue.
After I used hio.to_file to save result CSV file, I got content like this:
```
â�¢        Dynamic global entrepreneur, visionary founder Global Coaches Network, a pioneer in the field of global leadership coaching with 300 coaches, operating in 75 countries
â�¢        25 years developing women organizational leaders and entrepreneurs to maximize their leadership potential   
â�¢        25 yearsâ�� experience developing global executives and their families in the US, Asia, and the Middle East as their coach, family business consultant, or their therapist. 
â�¢        Speaker and trainer on global leadership in the 21st century, global leadership coaching for coaches and leaders in Asia, Europe, the US, and Africa. 
â�¢        Award winning author of a series of articles on â��Ensuring Success on the International Assignmentâ��. 
â�¢        20 years marriage and family therapist
â�¢        Fun fact: Barrie was once a nanny for the Jordanian Royal family
```
Which should be:
```
•        Dynamic global entrepreneur, visionary founder Global Coaches Network, a pioneer in the field of global leadership coaching with 300 coaches, operating in 75 countries
•        25 years developing women organizational leaders and entrepreneurs to maximize their leadership potential   
•        25 years’ experience developing global executives and their families in the US, Asia, and the Middle East as their coach, family business consultant, or their therapist. 
•        Speaker and trainer on global leadership in the 21st century, global leadership coaching for coaches and leaders in Asia, Europe, the US, and Africa. 
•        Award winning author of a series of articles on “Ensuring Success on the International Assignment”. 
•        20 years marriage and family therapist
•        Fun fact: Barrie was once a nanny for the Jordanian Royal family
```

**Comment by gpsaggese** [comment]
It’s ok not to use to_file in this case

**Comment by yiyunlei** [comment]
@gpsaggese Thanks, will update it.

**Comment by gpsaggese** [comment]
Let's use the right way to save the data and merge.

**Comment by samarth9008** [comment]
@gpsaggese Shall we create a new epic for all this work related data extraction for business? If so, could you suggest a good name for it?

**Comment by why2000** [comment]
> Let's use the right way to save the data and merge.

@gpsaggese Just checked, it's not an issue from hio.to_file, but from python `requests` package's default encoding. It is fixed with `response.encoding = "UTF-8"`, should have a PR soon once other linkedin related changes are done.

**Comment by samarth9008** [comment]
Can we assign epic to it?

**Comment by why2000** [comment]
Copied to cmamp in cmamp issue [#6069](https://github.com/cryptokaizen/cmamp/pull/6069)

**Comment by why2000** [comment]
Should this issue be closed? Both PRs for it are merged.
