### ISSUE TITLE
Factor out and unit test marker generation code

### ISSUE THREAD

**Issue by gpsaggese** [sorrentum/sorrentum#537]
At this point we should factor out this function and then unit test carefully. 
Don't worry for now. We'll have an intern taking care of it

_Originally posted by @gpsaggese in https://github.com/sorrentum/sorrentum/pull/530#discussion_r1291337826_

**Comment by DanilYachmenev** [comment]
@gpsaggese let me clarify the specs for collaborator

Now part of the code body in `run_fast_tests` is responsible for processing strings of test names ([link](https://github.com/sorrentum/sorrentum/blob/7e94b4366fbcca8ff01cec7a5b174bb679756400/helpers/lib_tasks_pytest.py#L418-L443)), done in https://github.com/sorrentum/sorrentum/pull/530#discussion_r1291337826

We need to factor out these lines in a separate function like
```
def _get_custom_marker(
    run_only_test_list: str,
    skip_test_list: str,
) -> str:
    """
    Get a list of `pytest` markers to skip.
    """
    ...
    return custom_marker
```

and unit test it

**Comment by gpsaggese** [comment]
Yes, we want to extract the logic and test them.
I would pass also `is_outside_ck_infra` then you can test all the computed strings.

I would `assert_equal` the output of the function to compute the params and _build_run_command_line.
What we care is that given command line options we get a command line to execute that is what we expect.

@why2000 does it make sense? Let's do small steps to make sure we are in sync

**Comment by why2000** [comment]
That makes sense. I've finished extracting the code and was writing the doc/tests. Would add the verifications today

**Comment by gpsaggese** [comment]
Sg. Remember the target is 1 PR a day (even just a draft) so we can be in sync on the direction

**Comment by why2000** [comment]
All PR for this issue already merged, closing this one.
