### ISSUE TITLE
Introduce `apply_columns_mode()`

### ISSUE THREAD

**Issue by DanilYachmenev** [sorrentum/sorrentum#541]
There is a function `apply_index_mode()` in `helpers/hpandas.py`
We want to have the same function but it should handle columns, not indices

- [ ] Create a function, use `apply_index_mode()` as a reference
- [ ] Add unit tests to `helpers/test/test_hpandas.py`, use `Test_apply_index_mode` as a reference

We want it to be able to process multiindex column, but let us know in case of any questions
![Снимок экрана 2023-08-15 в 14.48.07.png](https://images.zenhubusercontent.com/5eb2faa8a46f457650df8a61/eda577d5-636f-428e-bb4a-6049c9b31fef)

FYI @PomazkinG @samarth9008

**Comment by DanilYachmenev** [comment]
@jainamp14 this is your 2nd warm-up issue
If you have any questions, post them here

FYI @rheenina

**Comment by rheenina** [comment]
@jainamp14 tag me when it's ready for review

**Comment by rheenina** [comment]
integrated to cmamp, closing here
