### ISSUE TITLE
Find new grads from UMD to hire

### ISSUE THREAD

**Issue by gpsaggese** [sorrentum/sorrentum#553]
There is a list of ideal traits (not all of them are easy or possible to extract from LinkedIn).

We want to find UMD grads with:
- at least master's in CS, Computer Eng, ... (they need to be coding machines)
- high GPA (e.g., > 3.75)
   - Difficult to find this info on the LinkedIn
   - Send them email with the form and ask for the GPA
- graduated or ready to graduate
   - Unfortunately, it's not easy to find a field from the blue circle "open to work", although maybe downloading the image and just checking the image directly is probably super simple...
- lots of GitHub projects
- focus on Python and Web3
- doing internships

Next steps:
- We want to create some LinkedIn (or SalesNavigator) searches
   - Search10: https://www.linkedin.com/search/results/people/?geoUrn=%5B%22103644278%22%2C%22100809221%22%5D&keywords=umd%20cs&origin=FACETED_SEARCH&sid=z0i
- Run our beloved LI scraping flow
- Use MailMerge to send them an email (I can show you the flow to do run it)
- Fill out this Google form
    - GPA?
    - Are you open to work?
    - Pointer to the best you wrote?
    - Did you do internships?
- We can then expand the search to other schools
   - Of course for UMD we have an advantage since we are affiliated with them

**Comment by yiyunlei** [comment]
> Next steps:
> 
> * We want to create some LinkedIn (or SalesNavigator) searches
>   
>   * Search10: https://www.linkedin.com/search/results/people/?geoUrn=%5B%22103644278%22%2C%22100809221%22%5D&keywords=umd%20cs&origin=FACETED_SEARCH&sid=z0i

I created a new search based on the search you provided:
https://www.linkedin.com/search/results/people/?geoUrn=%5B%22103644278%22%5D&keywords=umd%20cs%20master&origin=GLOBAL_SEARCH_HEADER&page=3&schoolFilter=%5B%223638%22%5D&sid=o8V

I changed the search keywords from "umd cs" to "umd cs master" and added another filter: school (University of Maryland). Thus, search results were reduced from 942 to 162 in my account.
How about we start with this search?


  
>   * Unfortunately, it's not easy to find a field from the blue circle "open to work", although maybe downloading the image and just checking the image directly is probably super simple...

I found that the LinkedIn recruiter account has way more filters than the personal account (Including filtering out "open to work"). Maybe a recruiter account is an easier and more effective solution in this case ...
