### ISSUE TITLE
Remove redundancy in code

### ISSUE THREAD

**Issue by gpsaggese** [sorrentum/sorrentum#557]
> Assume that you add another vendor, then we centralize the assertion and add a new vendor to assertion.
> Then we need to go and update all the if-then-else everywhere.
> Surely we will miss one. With your solution you will get a silent error (return a `None`), the solution above will at least assert and you can find that there is a missing branch.

> If the code in each branch I would actually remove the `dassert`.
> The `dassert` is mainly to fail quickly, but it is redundant. So you need a way to keep the redundancy in sync, hence the `else`.

@gpsaggese Thanks for clarifying I understood why the `else` should be implemented. Will keep this in mind for the future implementation.

Just one clarification. 

> ```python
>     elif vendor == "ccxt":
>         # Do something or raise NotImplementedError
>     elif vendor == "crypto_chassis":
>         # Do something or raise NotImplementedError
>     else:
>         raise ValueError("Invalid error vendor='${vendor}'")
> ```

The above part is already implemented [here](https://github.com/sorrentum/sorrentum/blob/edbd2a2133ace3e5e250a93b6d3f06826f80b64a/im_v2/common/data/extract/download_bulk.py#L82C9-L96C58) just [after](https://github.com/sorrentum/sorrentum/pull/552/files#:~:text=imvcdqviar.validate_vendor_arg(vendor%3Dvendor%2C%20args%3Dargs)) this function is called. As discussed earlier in this issue this function that we are implementing is just for validation purpose. And hence the remaining else if were transferred back to `im_v2/common/data/extract/download_bulk.p`. But do let me know if you want me to transfer it back and I'll make the needed changes.

_Originally posted by @Sameep2808 in https://github.com/sorrentum/sorrentum/issues/552#issuecomment-1694871757_

**Comment by gpsaggese** [comment]
I'm not sure if we can / should factor out the common code that @Sameep2808 pointed to.

We could make the function more like a getter (that does also the validation) and merge all the common code.
But we need to double check the intention of the code.
FYI @jsmerix

**Comment by jsmerix** [comment]
I wanted to decouple validation and the rest of the code to fail fast:
- You input command line arguments and if there is a logical fallacy you fail immediately - no confusion, no long stacktrace to examine. For a user this means only a single possible resolution of the problem "I need to double check what arguments I am passing"
