### ISSUE TITLE
Allow saving exchange data to local directory

### ISSUE THREAD

**Issue by jsmerix** [sorrentum/sorrentum#561]
1. Extend [_add_common_download_args](https://github.com/sorrentum/sorrentum/blob/master/im_v2/common/data/extract/extract_utils.py#L51) to add new argument `dst_dir` ( str type, not required, without default value)
2. Add a new function, `validate_dst_dir_arg` applied in https://github.com/sorrentum/sorrentum/blob/master/im_v2/common/data/extract/download_bulk.py which checks that the `data_format` argument is `csv` or `parquet` and make sure that `db_table` and `s3_path` arguments are not present when `dst_dir` is specified
Update im_v2/common/data/extract/extract_utils.py::process_downloaded_historical_data to allow saving to a local filesystem instead of only S3 or DB (start by handling the case where format is “csv”, we can handle parquet later.
     - When format is csv you can name the file by the corresponding timestamps from the script call (`<start_ts>_<end_ts>.csv`)
3. Add a unit test using this new argument -> you want to mock interaction with exchange to return some dummy data

After that you want check that it works correctly by executing locally:
```
im_v2/common/data/extract/download_bulk.py --end_timestamp '2022-08-08T00:00:00+00:00' --start_timestamp '2022-08-01T00:00:00+00:00' --exchange_id 'binance' --universe 'v3' --data_type 'ohlcv' --vendor 'ccxt' --contract_type 'futures'  --s3_path 's3://cryptokaizen-data-test' --download_mode 'bulk' --downloading_entity 'manual' --action_tag 'downloaded_1min' --data_format 'csv' --dst_dir tmp
```

**Comment by Sameep2808** [comment]
@jsmerix Running this `im_v2/common/data/extract/download_bulk.py --end_timestamp '2022-08-08T00:00:00+00:00' --start_timestamp '2022-08-01T00:00:00+00:00' --exchange_id 'binance' --universe 'v3' --data_type 'ohlcv' --vendor 'ccxt' --contract_type 'futures'  --s3_path 's3://cryptokaizen-data-test' --download_mode 'bulk' --downloading_entity 'manual' --action_tag 'downloaded_1min' --data_format 'csv' --dst_dir tmp` command is giving me the following error. Do you have any idea why this must be happening?

```
Traceback (most recent call last):
  File "im_v2/common/data/extract/download_bulk.py", line 122, in <module>
    _main(_parse())
  File "im_v2/common/data/extract/download_bulk.py", line 118, in _main
    _run(args)
  File "im_v2/common/data/extract/download_bulk.py", line 99, in _run
    exchange = imvcdexex.CcxtExtractor(
  File "/app/im_v2/ccxt/data/extract/extractor.py", line 55, in __init__
    self.currency_pairs = self.get_exchange_currency_pairs()
  File "/app/im_v2/ccxt/data/extract/extractor.py", line 110, in get_exchange_currency_pairs
    return list(self._sync_exchange.load_markets().keys())
  File "/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1431, in load_markets
    markets = self.fetch_markets(params)
  File "/venv/lib/python3.8/site-packages/ccxt/binance.py", line 1468, in fetch_markets
    response = getattr(self, method)(query)
  File "/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 500, in inner
    return entry(_self, **inner_kwargs)
  File "/venv/lib/python3.8/site-packages/ccxt/binance.py", line 5583, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 2625, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 639, in fetch
    raise ExchangeError(details) from e
ccxt.base.errors.ExchangeError: binance GET https://fapi.binance.com/fapi/v1/exchangeInfo
```

Error from the link:
```
code	0
msg	"Service unavailable from a restricted location according to 'b. Eligibility' in https://www.binance.com/en/terms. Please contact customer service if you believe you received this message in error."
```

**Comment by jsmerix** [comment]
> Do you have any idea why this must be happening?

Since you are based in the USA the global API won't work can you try what happens if you specify `--exchange_id 'binanceus'.
