### ISSUE TITLE
On-board Hanyuan Wu 

### ISSUE THREAD

**Issue by DanilYachmenev** [sorrentum/sorrentum#567]
Please follow this checklist. Post any errors you face in this issue.

  - [x] Acknowledge the pledge to put time in the project [here](https://github.com/sorrentum/sorrentum/blob/master/README.md#Important) 
  - [x] Read [How to organize your work](https://github.com/sorrentum/sorrentum/blob/master/docs/How_to_organize_your_work.md)
  - [x] Read [Quick start for developing](https://github.com/sorrentum/sorrentum/blob/master/docs/Sorrentum_development_setup.md)
  - [x] Make sure the [Docker dev container](https://github.com/sorrentum/sorrentum/blob/master/docs/Sorrentum_development_setup.md#sorrentum-dev-docker-container-aka-dev-container-cmamp-container) works
  - [x] Make sure the [unit tests](https://github.com/sorrentum/sorrentum/blob/master/docs/Unit_tests.md) run successfully
  - [x] Read [Sorrentum Python coding style guide](https://github.com/sorrentum/sorrentum/blob/master/docs/Coding_Style_Guide.md)
  - [x] Fork, star, watch the Sorrentum repo so that GitHub promotes our repo (we gotta work the system)
  - [x] Get assigned a warm-up issue
  - [x] Learn about the [Morning Email](https://github.com/sorrentum/sorrentum/blob/master/docs/General_rules_of_collaboration.md#morning-email)
  - [x] How to do a [review](https://github.com/sorrentum/sorrentum/blob/master/docs/First_review_process.md)
  - [x] If you are graduating soon and you would like to get a full-time job in one of the companies in the Sorrentum ecosystem reach out to GP at gp@sorrentum.org
 
FYI @gpsaggese @samarth9008

**Comment by why2000** [comment]
Hi, task 3 "Quick Start for developing" shows a file not found, I guess it is moved to this one? https://github.com/sorrentum/sorrentum/blob/master/docs/Sorrentum_development_setup.md

**Comment by DanilYachmenev** [comment]
Thx for the notes! Updated links

**Comment by why2000** [comment]
Hi @DanilYachmenev, I've finished setting up the env and run the unit tests. There are several issue I met in the process:
1. While setting up the venv, since I use a brand new distro and have python3.10 with cython>3.0, this will cause a build error in awscli due to pyyaml 5.4.1, as shown in the link: [awscli build failure](https://stackoverflow.com/questions/76708329/docker-compose-no-longer-building-image-attributeerror-cython-sources). Upgrading pyyaml to >6.0 can solve the issue yet causing other conflicts. The only solution I found that solves this build error is downgrading pyyaml to 5.3.1, which is not having conflict with cython>3.0. So I added pyyaml == 5.3.1 in the first line of my local dev_scripts/client_setup/requirements.txt. I guess that conflict is a potential risk and this change may need to be applied for further set-ups.
2. In the unit tests, I got one ERROR and 2 FAIL, the fail shows that gh is not logged in but I've run gh auth login in both local and docker env. The stack trace is attached below:
```shell
ERROR dataflow/core/nodes/test/test_volatility_models.py::TestVolatilityModel::test08 - TypeError: __init__() got an unexpected keyword argument 'msg' - maybe you meant pytest.mark.skipif?
FAILED helpers/test/test_lib_tasks.py::TestGhLogin1::test_gh_login - RuntimeError: cmd='(gh auth status) 2>&1' failed with rc='1'
truncated output=
You are not logged into any GitHub hosts. Run gh auth login to authenticate.
FAILED helpers/test/test_lib_tasks_gh.py::TestLibTasks1::test_get_gh_issue_title4 - RuntimeError: cmd='(gh auth status) 2>&1' failed with rc='1'
truncated output=
You are not logged into any GitHub hosts. Run gh auth login to authenticate.
=============== 2 failed, 2071 passed, 270 skipped, 387 deselected, 2 xfailed, 1 error in 100.59s (0:01:40) ===============
```

**Comment by why2000** [comment]
Also, I want to know where can I get a warm-up issue? I joined the email group and if there's any, will start to send my progress from tomorrow on.

**Comment by DanilYachmenev** [comment]
@why2000 

Filed you 2 simple tasks to warm-up
Should be no problem, but use them to practise following our PR processes

Start with a document task first
And don't hesitate to ask in case of any questions

Doc conversion: https://github.com/sorrentum/sorrentum/issues/568
Unit testing: https://github.com/sorrentum/sorrentum/issues/459

**Comment by DanilYachmenev** [comment]
About the questions in https://github.com/sorrentum/sorrentum/issues/567#issuecomment-1720320041

1) @jsmerix @gpsaggese could you ptal please? don't have enough expertise in this domain

2) could you pls provide output of your `gh auth login`?

**Comment by samarth9008** [comment]
> ```shell
> dataflow/core/nodes/test/test_volatility_models.py::TestVolatilityModel::test08
> ```

Feel free to pull latest master and this error will not appear.

**Comment by why2000** [comment]
> About the questions in [#567 (comment)](https://github.com/sorrentum/sorrentum/issues/567#issuecomment-1720320041)
> 
> 1. @jsmerix @gpsaggese could you ptal please? don't have enough expertise in this domain
> 2. could you pls provide output of your `gh auth login`?

for 2, where should I run the gh auth login? I ran it on both my local sorrentum folder (while the sorrentum venv is activated), and the container started by `i docker_bash`. Both get the following output (ends with "Logged in as why2000"):
```shell
sudo gh auth login
[sudo] password for why: 
? What account do you want to log into? GitHub.com
? You're already logged into github.com. Do you want to re-authenticate? Yes
? What is your preferred protocol for Git operations? SSH
? Generate a new SSH key to add to your GitHub account? No
? How would you like to authenticate GitHub CLI? Login with a web browser

! First copy your one-time code: 66F4-20E4
- Press Enter to open github.com in your browser... 
✓ Authentication complete. Press Enter to continue...

- gh config set -h github.com git_protocol ssh
✓ Configured git protocol
✓ Logged in as why2000
```

**Comment by jsmerix** [comment]
> @jsmerix @gpsaggese could you ptal please? don't have enough expertise in this domain

It's difficult since we operate under different assumptions...python 3.8 instead of 3.10 not much can be done rwally.

**Comment by why2000** [comment]
> > @jsmerix @gpsaggese could you ptal please? don't have enough expertise in this domain
> 
> It's difficult since we operate under different assumptions...python 3.8 instead of 3.10 not much can be done rwally.

If you want to reproduce this issue, I think simply creating a latest python3.10 venv (make sure it's the latest one with cython>3.0) and running the dev_scripts/client_setup/build.sh would cause the issue. Many discussions in Stackoverflow think 5.4.1 <= pyyaml < 6.0.1 is not able to be installed on cython>3.0. Yet our awscli 1.x version requires pyyaml < 6.0. Not sure if upgrading to awscli 2.x would solve the issue, but that would be a major upgrade, thus I think force downgrading pyyaml to 5.3.1 would be a better temporary solution for now.

**Comment by gpsaggese** [comment]
Good work and debugging @why2000 

Two observations that should solve your problem
1) We should disable the 2 GitHub tests that are failing for you (there is issue / fix in another repo)
   - FYI @jsmerix 
2) We had this 3.8 vs 3.10 issue in the thin env also and there is a issue / fix in another repo
    - @samarth9008 @vladimir-yakovenko can you guys propagate the fix to Sorrentum

In any case you can keep moving while we fix these small problems
