### ISSUE TITLE
Convert Contributor Scoring Gdoc to Markdown

### ISSUE THREAD

**Issue by DanilYachmenev** [sorrentum/sorrentum#568]
Warm-up issue

- We need to convert a [Gdoc](https://docs.google.com/document/d/1wkG7c8LYhCnBINDRTpWcCLEQ5E9cW_A_bt4jr-Vxy64/edit) of Contributor Scoring to Markdown
- Instructions on how to convert Gdocs to Markdown are [here](https://github.com/sorrentum/sorrentum/blob/master/docs/Documentation_about_guidelines.md#gdocs---markdown)
- Read about the [First Review Process](https://github.com/sorrentum/sorrentum/blob/master/docs/First_review_process.md)
- Lint the markdown file using the [linter](https://github.com/sorrentum/sorrentum/blob/master/dev_scripts/lint_md.sh)
- PR example is https://github.com/sorrentum/sorrentum/pull/397
- Create markdown in `docs` folder
- Replace [Contributor_Scorecard.md](https://github.com/sorrentum/sorrentum/blob/master/docs/Contributor_Scorecard.md) doc with  this one and update a reference to it in [README](https://github.com/sorrentum/sorrentum/blob/master/README.md) (description and ref place can stay the same)

FYI @samarth9008

**Comment by gpsaggese** [comment]
Shared the gdoc with Henry

**Comment by why2000** [comment]
Hi @DanilYachmenev, this task is finished, see PR #570 
While using the convert_docx_to_markdown.py, I found the "filename_fig" folder and its contents are created under root:root, causing possible permission issues. That is because they are CREATED by a command running inside the docker (the pandoc command). Thus adding a user:group config would solve this problem.

**Comment by why2000** [comment]
The issue that might be triggered by this is:
In convert_docx_to_markdown.py, line 65 created the filename_fig folder and it's contents under root:root, no matter whether the current user has root access. But line 78 of the same file tries to move the created contents, causing permission denied when the current user doesn't have root access.
