### ISSUE TITLE
On-board Jainam Patel

### ISSUE THREAD

**Issue by DanilYachmenev** [sorrentum/sorrentum#577]
Please follow this checklist. Post any errors you face in this issue.

  - [x] Acknowledge the pledge to put time in the project [here](https://github.com/sorrentum/sorrentum/blob/master/README.md#Important) 
  - [x] Read [How to organize your work](https://github.com/sorrentum/sorrentum/blob/master/docs/How_to_organize_your_work.md)
  - [x] Read [Quick start for developing](https://github.com/sorrentum/sorrentum/blob/master/docs/Sorrentum_development_setup.md)
  - [x] Make sure the [Docker dev container](https://github.com/sorrentum/sorrentum/blob/master/docs/Sorrentum_development_setup.md#sorrentum-dev-docker-container-aka-dev-container-cmamp-container) works
  - [x] Make sure the [unit tests](https://github.com/sorrentum/sorrentum/blob/master/docs/Unit_tests.md) run successfully
  - [x] Read [Sorrentum Python coding style guide](https://github.com/sorrentum/sorrentum/blob/master/docs/Coding_Style_Guide.md)
  - [x] Fork, star, watch the Sorrentum repo so that GitHub promotes our repo (we gotta work the system)
  - [x] Get assigned a warm-up issue
  - [x] Learn about the [Morning Email](https://github.com/sorrentum/sorrentum/blob/master/docs/General_rules_of_collaboration.md#morning-email)
  - [x] How to do a [review](https://github.com/sorrentum/sorrentum/blob/master/docs/First_review_process.md)
  - [x] If you are graduating soon and you would like to get a full-time job in one of the companies in the Sorrentum ecosystem reach out to GP at gp@sorrentum.org
 
FYI @gpsaggese @sonaalKant

**Comment by samarth9008** [comment]
This will help

https://github.com/sorrentum/sorrentum/issues/437#issuecomment-1646058893
https://github.com/sorrentum/sorrentum/issues/437#issuecomment-1646249800

**Comment by jainamp14** [comment]
Thank you so much that was able to fix the error but towards the end of that same command I got another error stating:
```
Installing from the API is now the default behaviour!
You can save space and time by running:
  brew untap homebrew/core
  brew untap homebrew/cask
Already up-to-date.
# brew version=Homebrew 4.1.13
Homebrew/homebrew-core (git revision b7d32df24b0; last commit 2023-09-28)
Homebrew/homebrew-cask (git revision f8baf75561; last commit 2023-09-28)
Error: Cannot install under Rosetta 2 in ARM default prefix (/opt/homebrew)!
To rerun under ARM use:
    arch -arm64 brew install ...
To install under x86_64, install Homebrew into /usr/local.

[Process completed]
```

I did what it said and installed homebrew into /usr/local but got the same error. I tried to active the environment to see if it worked using the command "source dev_scripts/setenv_amp.sh" and it said Success but the message isn't similar to what is provided on GitHub. This is what comes up on my end:

```
jainampatel@Jainams-MacBook-Pro sorrentum1 % source dev_scripts/setenv_amp.sh
# Activate virtual env '/Users/jainampatel/src/venv/amp.client_venv/bin/activate'
which python=/Users/jainampatel/src/venv/amp.client_venv/bin/python
python -v=Python 3.11.5
# Set path
PATH=
/Users/jainampatel/src/sorrentum1/dev_scripts/testing
/Users/jainampatel/src/sorrentum1/dev_scripts/notebooks
/Users/jainampatel/src/sorrentum1/dev_scripts/install
/Users/jainampatel/src/sorrentum1/dev_scripts/infra
/Users/jainampatel/src/sorrentum1/dev_scripts/git
/Users/jainampatel/src/sorrentum1/dev_scripts/aws
/Users/jainampatel/src/sorrentum1/dev_scripts
/Users/jainampatel/src/sorrentum1
.
/Users/jainampatel/src/venv/amp.client_venv/bin
/Users/jainampatel/.opam/default/bin
/Users/jainampatel/opt/anaconda3/bin
/Library/Frameworks/Python.framework/Versions/3.11/bin
/opt/homebrew/bin
/opt/homebrew/sbin
/usr/local/bin
/System/Cryptexes/App/usr/bin
/usr/bin
/bin
/usr/sbin
/sbin
/Library/TeX/texbin
/opt/X11/bin
/Library/Apple/usr/bin
/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin
/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin
/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin
/Users/jainampatel/.cargo/bin
# Set PYTHONPATH
PYTHONPATH=
/Users/jainampatel/src/sorrentum1

# Configure env
which gh=gh not found
AM_AWS_PROFILE=am
AM_AWS_S3_BUCKET=alphamatic-data
AM_ECR_BASE_PATH=665840871993.dkr.ecr.us-east-1.amazonaws.com
CK_AWS_PROFILE=ck
CK_AWS_S3_BUCKET=cryptokaizen-data
OPAM_SWITCH_PREFIX=/Users/jainampatel/.opam/default
TERM_PROGRAM_VERSION=447
i=invoke
ih='invoke --help'
il='invoke --list'
it='invoke traceback'
itpb='pbpaste | traceback_to_cfile.py -i - -o cfile'
run-help=man
which-command=whence
==> SUCCESS <==
```
Am I good to continue or is it something I need to fix?

**Comment by jainamp14** [comment]
I was able to find a fix and it is working now, I can open the docker container and Jupyter server.

**Comment by jainamp14** [comment]
I have finished setting up and reading everything before the warm-ups. I will start the warm-up on Monday.

**Comment by DanilYachmenev** [comment]
@jainamp14 mark all the checkboxes in issue desc when you read and prepared everything so we close this issue
