### ISSUE TITLE
On-board Shabarish Nair

### ISSUE THREAD

**Issue by DanilYachmenev** [sorrentum/sorrentum#583]
Please follow this checklist. Post any errors you face in this issue.

  - [x] Acknowledge the pledge to put time in the project [here](https://github.com/sorrentum/sorrentum/blob/master/README.md#Important) 
  - [x] Read [How to organize your work](https://github.com/sorrentum/sorrentum/blob/master/docs/How_to_organize_your_work.md)
  - [x] Read [Quick start for developing](https://github.com/sorrentum/sorrentum/blob/master/docs/Sorrentum_development_setup.md)
  - [x] Make sure the [Docker dev container](https://github.com/sorrentum/sorrentum/blob/master/docs/Sorrentum_development_setup.md#sorrentum-dev-docker-container-aka-dev-container-cmamp-container) works
  - [x] Make sure the [unit tests](https://github.com/sorrentum/sorrentum/blob/master/docs/Unit_tests.md) run successfully
  - [x] Read [Sorrentum Python coding style guide](https://github.com/sorrentum/sorrentum/blob/master/docs/Coding_Style_Guide.md)
  - [x] Fork, star, watch the Sorrentum repo so that GitHub promotes our repo (we gotta work the system)
  - [x] Get assigned a warm-up issue
  - [x] Learn about the [Morning Email](https://github.com/sorrentum/sorrentum/blob/master/docs/General_rules_of_collaboration.md#morning-email)
  - [x] How to do a [review](https://github.com/sorrentum/sorrentum/blob/master/docs/First_review_process.md)
  - [x] If you are graduating soon and you would like to get a full-time job in one of the companies in the Sorrentum ecosystem reach out to GP at gp@sorrentum.org
 
FYI @gpsaggese @sonaalKant

**Comment by DanilYachmenev** [comment]
Warm-up issue https://github.com/sorrentum/sorrentum/issues/491

**Comment by shab95** [comment]
I'm encountering an issue while trying to run 

`source dev_scripts/client_setup/build.sh`

When running the command, I encountered this message, after which the terminal immediately closed:

`which python=
python -v=Command 'python' not found, did you mean: command 'python' from deb python3 command 'python' from deb-python-is-python3
which python3=/usr/bin/python3
python3 -v=Python 3.10.12
AM_SRC_DIR=/home/shab95/src
# VENV_DIR=/home/shab95/venv/amp.client_venv
# Deleting old virtual environment in '/home/shab95/src/venv/amp.client_venv
# Creating virtual environment in '/home/shab95/src/venv/amp.client_venv'`

I thought this issue had to do with something to do with the statement 'python' itself, so I ran this command
`alias python='python3'`

I then ran this command again:
`source dev_scripts/client_setup/build.sh`

and the result was this(terminal still closes immediately afterwards):
`which python=
python -v=Python 3.10.12
which python3=/usr/bin/python3
python3 -v=Python 3.10.12
AM_SRC_DIR=/home/shab95/src
# VENV_DIR=/home/shab95/venv/amp.client_venv
# Deleting old virtual environment in '/home/shab95/src/venv/amp.client_venv
# Creating virtual environment in '/home/shab95/src/venv/amp.client_venv'`

There was no error in this output, so I decided to open a new terminal and run this command as well:
`source dev_scripts/setenv_amp.sh`

This was the result:
`# Activate virtual env '/home/shab95/src/venv/amp.client_venv/bin/activate'
ERROR: Can't find '/home/shab95/src/venv/amp.client_venv/bin/activate'`

Not sure where to go from here. Also i'm running this with Ubuntu 22.04.3 on VMware. 

Going to skip this issue for now and continue with the on boarding tasks

**Comment by DanilYachmenev** [comment]
@shab95 did you connect to out server?
Judging from your logs, you're trying to set up a virtual env at your local dir
```
/home/shab95/src/venv/amp.client_venv
```

Could you provide full cmd that you run, like
```
dan@dev1:~/src/orange1$ source dev_scripts_orange/setenv.sh 
```

**Comment by shab95** [comment]
Sorry, not sure what you mean by connect to server. These are the full commandsI ran:

`shab95@shab95-virtual-machine:~/Documents/Sorrentum/src/sorrentum1$ source dev_scripts/client_setup/build.sh`
`shab95@shab95-virtual-machine:~/Documents/Sorrentum/src/sorrentum1$ source dev_scripts/setenv_amp.sh`

If you can point me to how I can connect to the server that may help. Apologize for the delay.

**Comment by gpsaggese** [comment]
@shab95 on Sorrentum you should run on your laptop, no need for the server.

@DanilYachmenev do we have info on @shab95 set-up? It seems that he is running on Windows using VMware which is the suggested set-up.

E.g., on the server I believe we use an earlier version (Ubuntu 20 or even 18?). There should be a doc on how to configure the system `docs/Sorrentum_development_setup.md:13`
I remember that @Sameep2808 improved the documentation but maybe it was not integrated in Sorrentum yet?

We need to clarify exactly which version people needs to use so that it's easy to keep things aligned with our dev server set-up

**Comment by DanilYachmenev** [comment]
> @DanilYachmenev do we have info on @shab95 set-up? It seems that he is running on Windows using VMware which is the suggested set-up.

@shab95, could you provide it for us pls?

> E.g., on the server I believe we use an earlier version (Ubuntu 20 or even 18?). There should be a doc on how to configure the system `docs/Sorrentum_development_setup.md:13` I remember that @Sameep2808 improved the documentation but maybe it was not integrated in Sorrentum yet?

@gpsaggese this is what we have on Windows VMware, it seems to be in-line with `cmamp` doc version
https://github.com/sorrentum/sorrentum/blob/master/docs/Sorrentum_development_setup.md#supporting-os 

@Sameep2808 could you ptal at the problem with Shabarish's set-up?

**Comment by shab95** [comment]
@DanilYachmenev 
Yes, I'm running Ubuntu 22.04.3 VMware on my Windows 11 laptop. Based on the [Supporting OS section ](https://github.com/sorrentum/sorrentum/blob/master/docs/Sorrentum_development_setup.md#supporting-os), I thought I would need to clone Sorrentum into a VM and do everything in the VM.

I also attempted to build the thin environment locally(Windows not Ubuntu VM) in Windows Powershell and WSL Ubuntu terminal, but I am getting errors for both. 

Are there any other pieces of information needed?

**Comment by gpsaggese** [comment]
Correct. You need to do everything inside the VM.

@Sameep2808 can you pls chime in here?

**Comment by shab95** [comment]
Thank you so much! The commands work, but I am not seeing the correct result.

I think what may have also helped it was using Ubuntu version 20.04.6 instead of 22.04.3 or the fact that 20.04.6 comes with python verison 3.8(not exactly sure). After running these commands, I was able to build and activate the thin environment.

Here are the end of the results that I see

```
# Configure env
which gh=
AM_AWS_PROFILE=am
AM_AWS_S3_BUCKET=alphamatic-data
AM_ECR_BASE_PATH=665840871993.dkr.ecr.us-east-1.amazonaws.com
CK_AWS_PROFILE=ck
CK_AWS_S3_BUCKET=cryptokaizen-data
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias i='invoke'
alias ih='invoke --help'
alias il='invoke --list'
alias it='invoke traceback'
alias itpb='pbpaste | traceback_to_cfile.py -i - -o cfile'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'
alias ls='ls --color=auto'
==> SUCCESS <==
```

Here is what it says in the development setup:

```
alias sp='echo '\''source ~/.profile'\''; source ~/.profile'
alias vi='/usr/bin/vi'
alias vim='/usr/bin/vi'
alias vimdiff='/usr/bin/vi -d'
alias vip='vim -c "source ~/.vimrc_priv"'
alias w='which'
==> SUCCESS <==
```

Also, I tried pulling afterwards:
` i git_pull`

However, I get this error when I run the command:
```
One and only one set-up config should be true:
is_cmamp_prod=False
is_dev4=False
is_dev_ck=False
is_ig_prod=False
is_inside_ci=False
is_mac=False
INFO: > cmd='/home/shab95/src/venv/amp.client_venv/bin/invoke git_pull'
## git_pull: 
git pull --autostash
fatal: --[no-]autostash option is only valid with --rebase.
```

Any help would be appreciated.

**Comment by gpsaggese** [comment]
Make sure to read/investigate errors on your own before asking for help.
A Google search might tell you that you have an old version of git

What version do you have?

**Comment by shab95** [comment]
I did have git version 2.25, but upgrading to 2.42 did help resolve the issue. Sorry about that, I definitely should have put some more time into resolving it myself. 

Also, is it ok that the results of the setup command in the development setup is different from the ouput I received from running the setup command?
