### ISSUE TITLE
Use `str_to_timestamp()` instead of `timestamp_as_str_to_timestamp()`

### ISSUE THREAD

**Issue by rheenina** [sorrentum/sorrentum#584]
We want to replace `timestamp_as_str_to_timestamp()` with `str_to_timestamp()`.

Related files:
- `oms/reconciliation.py`
- `helpers/hdatetime.py`

- Search for cases where `timestamp_as_str_to_timestamp()` is used.
```
jackpy "timestamp_as_str_to_timestamp"
```
- Group all cases by regex or just a text. E.g., to replace function name with import, use:
```
--old "omreconc.timestamp_as_str_to_timestamp" \
--new "hdatetime.str_to_timestamp" \
```
- To replace text, use the script  https://github.com/cryptokaizen/cmamp/blob/master/dev_scripts/replace_text.py
- Run the script and then check the changes:
    - using jackpy to make sure if all have been replaced
    - using `git diff` or `git diff --staged` in case if files were added
- Name the script you used as the task, e.g., SorrTask{task_num}_{task_name}
- Commit changed files and the script

If any questions, feel free to ask in the issue comments.

FYI @DanilYachmenev

**Comment by rheenina** [comment]
Also please name branch and PRs as `SorrTask{task_num}_{task_name}`

**Comment by jainamp14** [comment]
Quick question before I run the script to replace text, you have mentioned only files `oms/reconciliation.py` and `helpers/hdatetime.py` but `helpers/hdatetime.py` doesn't have any text that needs to be replaced and there are other occurrences outside of those 2 files as show below from using jackpy. Should I replace it everywhere or should I only do it in `oms/reconciliation.py` file?
```
(amp.client_venv) jainampatel@Jainams-MacBook-Pro sorrentum1 % jackpy "timestamp_as_str_to_timestamp"
oms/reconciliation.py:236:    start_timestamp = timestamp_as_str_to_timestamp(start_timestamp_as_str)
oms/reconciliation.py:237:    end_timestamp = timestamp_as_str_to_timestamp(end_timestamp_as_str)
oms/reconciliation.py:408:def timestamp_as_str_to_timestamp(
oms/reconciliation.py:595:            if timestamp_as_str_to_timestamp(system_run_start_timestamp, tz=tz)
oms/reconciliation.py:606:            if timestamp_as_str_to_timestamp(system_run_start_timestamp, tz=tz)
oms/notebooks/Master_multiday_system_reconciliation.py:196:    start_timestamp = omreconc.timestamp_as_str_to_timestamp(
oms/notebooks/Master_multiday_system_reconciliation.py:199:    end_timestamp = omreconc.timestamp_as_str_to_timestamp(end_timestamp_as_str)
dataflow_amp/system/Cx/Cx_dump_market_data.py:60:    start_timestamp = oms.timestamp_as_str_to_timestamp(start_timestamp_as_str)
dataflow_amp/system/Cx/Cx_dump_market_data.py:61:    end_timestamp = oms.timestamp_as_str_to_timestamp(end_timestamp_as_str)
```

**Comment by rheenina** [comment]
> Should I replace it everywhere or should I only do it in oms/reconciliation.py file?

Replace everywhere.

`timestamp_as_str_to_timestamp()`  is located in `helpers/hdatetime.py`, `timestamp_as_str_to_timestamp()` is in `oms/reconciliation.py`

**Comment by rheenina** [comment]
You have two functions:
- str_to_timestamp() in hdatetime.py
- timestamp_as_str_to_timestamp() in reconciliation.py

You need to replace everywhere usage of `timestamp_as_str_to_timestamp()` to `str_to_timestamp()`. You did it but it requires a small fix:
- `def timestamp_as_str_to_timestamp` should remain as is
- change not only function name but also import (see issue description for an example). If it requires more explanation, here's one more example:
1. We have a line `ts = timestamp_as_str_to_timestamp(time_as_str)` in oms/reconciliation.py NOTE: line and a function in the same file so there's no any import when we call the function.
2. We have `str_to_timestamp()` in hdatetime.py.
3. We want to use the above-mentioned function in the line from p.1. To do that, we import hdatetime to reconciliation.py and replace the line with `ts = hdatetime.str_to_timestamp(time_as_str)`

You need to find all cases to replace, two already found:
1. timestamp_as_str_to_timestamp -> hdatetime.str_to_timestamp
This one requires a regex because we don't want to change `def timestamp_as_str_to_timestamp`.
2. omreconc.timestamp_as_str_to_timestamp -> hdatetime.str_to_timestamp

timestamp_as_str_to_timestamp() could be used as oms.timestamp_as_str_to_timestamp() -- check results you've got from jackpy cmd.

**Comment by gpsaggese** [comment]
@rheenina since your explanation is so good, should we update `docs/Codebase_clean_up_scripts.md` with some of this text as an example. 
This is just a 5% extra work, but then maybe next time we can just point somebody to the doc instead of explaining.

I'm with literally copying the text in a section like
`# Example of how to ...
As an example see https://github.com/sorrentum/sorrentum/issues/584

In brief
...
```
It doesn't have to be well-written but rather some text that we can improve over time. You can even ask @jainamp14 to take care of this

@PomazkinG WDYT? (Towards developing a continuous documentation mindset)

**Comment by dremdem** [comment]
@jainamp14 
Please assign in this issue: 
- sprint
- estimate
- EPIC
FYI @samarth9008

**Comment by rheenina** [comment]
> @jainamp14 Please assign in this issue:
> 
> * sprint
> * estimate
> * EPIC
>   FYI @samarth9008

I’ll take care of this one

**Comment by rheenina** [comment]
Pass to @samarth9008 to update docs https://github.com/sorrentum/sorrentum/issues/584#issuecomment-1761317468

Basically, you need to add an example to the [doc section](https://github.com/sorrentum/sorrentum/blob/master/docs/Codebase_clean_up_scripts.md#usage-examples), i.e. a short description and a reference to the issue.

PR here and in cmamp.

**Comment by rheenina** [comment]
@why2000 We need to integrate this PR https://github.com/sorrentum/sorrentum/commit/acf0de670f9dc1e2401946d6fab9f7c8e92fd08e into cmamp, note that PR has old dir layout and file names so make a search by functions where changes were made.

Check if we can safely add this changes without applying `dev_scripts/cleanup_scripts/SorrTask584_Use_str_to_timestamp_instead_of_timestamp_as_str_to_timestamp.sh` to the whole cmamp as a part of an integration https://github.com/cryptokaizen/cmamp/issues/6674#issuecomment-1881568251. I don't want to apply this script for the whole repo for now because it touches system and system reconciliation workflows.

The goal is:
- tests (superslow included) in orange and cmamp are green;
- nothing else is changed in cmamp (for the 1st iteration at least).

FYI @PomazkinG changes you wanted an eternity ago :)

FYI @gpsaggese

**Comment by why2000** [comment]
@rheenina Just to check, do we need to add `dev_scripts/cleanup_scripts/SorrTask584_Use_str_to_timestamp_instead_of_timestamp_as_str_to_timestamp.sh` to cmamp? I'm not applying it but not sure if the script itself should be included in the cmamp PR.

**Comment by why2000** [comment]
There seems to be a bug in fast tests, which is due to an old checkpoint file not deleted and is recognized by the `i run_fast_tests` as a pytest. Should we add some rule to exclude all the `.ipynb_checkpoints` folder from the pytest runner?
`FAILED amp/oms/test/.ipynb_checkpoints/test_notebooks-checkpoint.py::Test_run_master_notebooks::test_run_master_cross_component_reconciliation - TypeError: get_s3_input_dir() takes 1 positional argument but 2 were given.`
```
____________________________________________________ Test_run_master_notebooks.test_run_master_cross_component_reconciliation ____________________________________________________
Traceback (most recent call last):
  File "/usr/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.9/unittest/case.py", line 593, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/app/amp/oms/test/.ipynb_checkpoints/test_notebooks-checkpoint.py", line 127, in test_run_master_cross_component_reconciliation
    self._run_notebook(
  File "/app/amp/oms/test/.ipynb_checkpoints/test_notebooks-checkpoint.py", line 139, in _run_notebook
    s3_input_dir = self.get_s3_input_dir(aws_profile)
TypeError: get_s3_input_dir() takes 1 positional argument but 2 were given
```

**Comment by why2000** [comment]
The failure in run_fast_tests also happens in run_superslow_tests. And it has multiple more tests that seems unrelated to the modifications I made:
```
FAILED dataflow_orange/system/Cx/test/test_run_Cx_prod_system_simulation.py::Test_run_Cx_prod_simulation::test1 - AttributeError: module 'dataflow_amp.system.Cx' has no attribute
 'get_Cx_prod_process_forecasts_config'                                                                                                                                           
FAILED dataflow_orange/system/Cx/test/test_run_Cx_prod_system_simulation.py::Test_run_Cx_prod_simulation::test2 - AttributeError: module 'dataflow_amp.system.Cx' has no attribute
 'get_Cx_prod_process_forecasts_config'                                                                                                                                           
FAILED dataflow_orange/system/Cx/test/test_run_Cx_prod_system_simulation.py::Test_run_Cx_prod_simulation_with_replayed_fills::test1 - AttributeError: module 'dataflow_amp.system.
Cx' has no attribute 'get_Cx_prod_process_forecasts_config'
···

**Comment by rheenina** [comment]
> @rheenina Just to check, do we need to add dev_scripts/cleanup_scripts/SorrTask584_Use_str_to_timestamp_instead_of_timestamp_as_str_to_timestamp.sh to cmamp? I'm not applying it but not sure if the script itself should be included in the cmamp PR.

Yes, let's add it so we have script when we ready to apply changes fully.

**Comment by rheenina** [comment]
> The failure in run_fast_tests also happens in run_superslow_tests. And it has multiple more tests that seems unrelated to the modifications I made:
> 
> ```
> FAILED dataflow_orange/system/Cx/test/test_run_Cx_prod_system_simulation.py::Test_run_Cx_prod_simulation::test1 - AttributeError: module 'dataflow_amp.system.Cx' has no attribute
>  'get_Cx_prod_process_forecasts_config'                                                                                                                                           
> FAILED dataflow_orange/system/Cx/test/test_run_Cx_prod_system_simulation.py::Test_run_Cx_prod_simulation::test2 - AttributeError: module 'dataflow_amp.system.Cx' has no attribute
>  'get_Cx_prod_process_forecasts_config'                                                                                                                                           
> FAILED dataflow_orange/system/Cx/test/test_run_Cx_prod_system_simulation.py::Test_run_Cx_prod_simulation_with_replayed_fills::test1 - AttributeError: module 'dataflow_amp.system.
> Cx' has no attribute 'get_Cx_prod_process_forecasts_config'
> ···
> ```

Seems like you used outdated version of orange. Tests are passed for me locally.

> There seems to be a bug in `orange` run_fast_tests, which is due to an old checkpoint file not deleted and is recognized by the `i run_fast_tests` as a pytest. Should we add some rule to exclude all the `.ipynb_checkpoints` folder from the pytest runner? `FAILED amp/oms/test/.ipynb_checkpoints/test_notebooks-checkpoint.py::Test_run_master_notebooks::test_run_master_cross_component_reconciliation - TypeError: get_s3_input_dir() takes 1 positional argument but 2 were given.`
> 
> ```
> ____________________________________________________ Test_run_master_notebooks.test_run_master_cross_component_reconciliation ____________________________________________________
> Traceback (most recent call last):
>   File "/usr/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
>     yield
>   File "/usr/lib/python3.9/unittest/case.py", line 593, in run
>     self._callTestMethod(testMethod)
>   File "/usr/lib/python3.9/unittest/case.py", line 550, in _callTestMethod
>     method()
>   File "/app/amp/oms/test/.ipynb_checkpoints/test_notebooks-checkpoint.py", line 127, in test_run_master_cross_component_reconciliation
>     self._run_notebook(
>   File "/app/amp/oms/test/.ipynb_checkpoints/test_notebooks-checkpoint.py", line 139, in _run_notebook
>     s3_input_dir = self.get_s3_input_dir(aws_profile)
> TypeError: get_s3_input_dir() takes 1 positional argument but 2 were given
> ```

It's a local folder and not presented on gh. ok to skip

**Comment by rheenina** [comment]
Sum up: PR is moved to cmamp seamless, however we didn't apply script to other repos so this part as a follow-up.

I believe we can close here, the rest of changes are not a part of sorrentum.
