### ISSUE TITLE
Move `_dassert_is_date` to a more general lib

### ISSUE THREAD

**Issue by DanilYachmenev** [sorrentum/sorrentum#588]
- [x] Move `_dassert_is_date()` from `oms/reconciliation.py` to `helpers/hdatetime.py`
     - Put it right after `dassert_is_strict_datetime()`
     - Update the calls
- [x] Rename it to `_dassert_str_is_date()` and update the calls
- [x] Add simple unit tests (1 passing, 1 failing) at the corresponding dir (see [unit tests doc](https://github.com/sorrentum/sorrentum/blob/master/docs/Unit_tests.md))

FYI @rheenina

**Comment by gpsaggese** [comment]
Nice specs. I like the checklist

**Comment by DanilYachmenev** [comment]
done

**Comment by rheenina** [comment]
@shab95 address as follow up https://github.com/sorrentum/sorrentum/pull/590#pullrequestreview-1695371069

@DanilYachmenev before closing, should be integrated to `cmamp`.

**Comment by rheenina** [comment]
done
