### ISSUE TITLE
Extend unit testing of `str_to_timestamp()`

### ISSUE THREAD

**Issue by DanilYachmenev** [sorrentum/sorrentum#592]
There is a function `str_to_timestamp()` in `/helpers/hdatetime`

It already has unit test under `Test_str_to_timestamp1` class in `amp/helpers/test/test_hdatetime.py`, but all the tests use `timezone_info = "US/Eastern"`

To explain its functionality better we need to:
- [x] Add 1 unit test where `timezone_info = "UTC"`
- [x] Extend function docstring with the following:
    ```
    """
    Convert timestamp as string to `pd.Timestamp`.

    The function localizes input time to the specified timezone,
    e.g., if `timestamp_as_str=20230523_150513` and:
    - `tz="UTC"` -> `2023-05-23 15:05:13+0000`
    - `tz="US/Eastern"` -> `2023-05-23 15:05:13-0400`

    : param ...
    ```

FYI @rheenina

**Comment by rheenina** [comment]
Could be a nice task for @shab95 to learn how to fix tests:
https://github.com/sorrentum/sorrentum/actions/runs/6617086925/job/17972675723

Related to `str_to_timestamp()` function. Feel free to push to mentioned PR

**Comment by samarth9008** [comment]
Can we close this?

**Comment by rheenina** [comment]
> Can we close this?

should be integrated to cmamp first

**Comment by DanilYachmenev** [comment]
Agree
@samarth9008 could you pls make an integration PR to cmamp for #593?
You can close this one afterwards

**Comment by rheenina** [comment]
done
