### ISSUE TITLE
Extract email from LinkedIn profiles

### ISSUE THREAD

**Issue by gpsaggese** [sorrentum/sorrentum#596]
Given the result of extracting LinkedIn profiles from a search using PhantomBuster
https://docs.google.com/spreadsheets/d/1TwHK7HgW3-mWvFFiMLYP8u7ANZOjGuae1ajbMID5jo4/edit#gid=1196653151

we want to extract the email from the contact info (if available) of all the targets.

E.g.,
https://www.linkedin.com/in/alvarojimenezjimenez	Alvaro	Jimenez Jimenez

https://www.linkedin.com/in/alvarojimenezjimenez/overlay/contact-info/
<img width="542" alt="image" src="https://github.com/cryptokaizen/cmamp/assets/33238329/5ee1b9b4-5f5a-4189-8cb4-91b184a9a491">

We can use BeautifulSoup.

Can we build a quick prototype and see if it works? What is the ETA?

This replaces a PB flow that we use to scrape profile info just to get the emails

**Comment by samarth9008** [comment]
@yiyunlei Keep me in loop as a reviewer whenever you create a PR for any tasks related to this.

**Comment by samarth9008** [comment]
Some early suggestion from https://github.com/sorrentum/sorrentum/pull/599

1. Can you create python script instead of `.ipynb` file?
2. Instead of just printing the emails, Can we write it to that same file creating an email column?

**Comment by yiyunlei** [comment]
1. Sure, I'll make it a `.py`, but should we keep it in the same folder, or should it be moved to some helpers folder?
2. Yes, but should we write it to the same datasheet tab as a new col, or create a new datasheet tab and put only the results needed there?
3. Yes we can use `helpers/hgoogle_file_api.py` to implement that, I'll try after finishing the first two.

**Comment by samarth9008** [comment]
> 1. Sure, I'll make it a `.py`, but should we keep it in the same folder, or should it be moved to some helpers folder?

Same is fine

> 2. Yes, but should we write it to the same datasheet tab as a new col, or create a new datasheet tab and put only the results needed there?

I would insist on same datasheet

**Comment by samarth9008** [comment]
Whats the status @yiyunlei ? Can this be closed?

**Comment by yiyunlei** [comment]
closed.
