### ISSUE TITLE
Use other services to get emails from a LinkedIn profile

### ISSUE THREAD

**Issue by samarth9008** [sorrentum/sorrentum#600]
We can extract the email from the contact info page of LinkedIn automatically, whenever we can, scraping the contact info page.

We know PB(Phantom Buster) can get the emails (probably using some of these services) but it's very slow. We want to do it directly.

What services can automatically retrieve emails (professional and personal) from LinkedIn?

![unnamed](https://github.com/sorrentum/sorrentum/assets/58821247/2364cb18-6e9d-4990-92d0-d26b55c0b702)

Create a free account with some of these systems and experiment a bit.

Spend 2-3 hours to build a prototype.

FYI @gpsaggese

**Comment by C-Nubela** [comment]
Hey there! I work at [Proxycurl](https://nubela.co/proxycurl/?utm_campaign=content_amplification&utm_source=github&utm_medium=social&utm_content=comments)--we're a B2B data provider and enrichment API.

You could definitely use us for this purpose, and the best part is you can flawlessly integrate us into your workflow.

[Give this article here a read.](https://nubela.co/blog/linkedin-email-finder-api/?utm_campaign=content_amplification&utm_source=github&utm_medium=social&utm_content=comments) it'll show you how to pull personal/professional emails from LinkedIn.

**Comment by shab95** [comment]
Plan of action
- Create a new notebook in /linkedin/notebooks called retrieve_email_from_linkedin_profile
- For each service, create a free account(if there is a free version) and attempt to use their API to retrieve emails
    - determine whether it's possible to get an email by testing on a profile that has emails
    - record amount of time it takes to get the email
    - determine if a personal, professional, or both emails were found
