### ISSUE TITLE
Marketing: Build a mailing list for AI VCs from Tra

### ISSUE THREAD

**Issue by why2000** [sorrentum/sorrentum#601]
https://docs.google.com/document/d/1z-svt4K6dSy5ncuVZzrtL9ZYuBmknCp8UfGfxljaBNQ/edit#heading=h.3peqjdp00fga
We would like to get the list of VCs investing in certain areas
We have a license of tracxn, we create some queries, scroll to the bottom to get all the entries and then we save it into files 
The idea is to read the saved html files and scrape them with Beautiful soup to generate CSV files / Google sheets with the fields above
After this we can use LinkedIn to extract the people working there

**Comment by why2000** [comment]
Looks like the emails are not loaded in the Tracxn company info page, we have to click the little icon to load email for certain person (which is not scrapable without login). But all of their linkedIn profile page links are directly loaded in the page. The following screenshots show that icon's inner layer is a javascript placeholder if not clicked.
![image](https://github.com/sorrentum/sorrentum/assets/30973831/a0466ecb-3794-4a46-a0b4-c1287c026b97)
![image](https://github.com/sorrentum/sorrentum/assets/30973831/b9dc302b-ee7d-4096-bcef-0ae5ad94b8ac)

**Comment by gpsaggese** [comment]
Follow up from https://github.com/sorrentum/sorrentum/pull/603

**Comment by why2000** [comment]
All PR merged, closing.
