### ISSUE TITLE
Marketing: Implement flow to find people that work at a firm

### ISSUE THREAD

**Issue by yiyunlei** [sorrentum/sorrentum#604]
- Given the name of a company, find the LinkedIn page
- E.g., Y-combinator -> https://www.linkedin.com/company/y%C2%A0combinator
- It seems that we can infer the name
- https://www.linkedin.com/company/y%C2%A0combinator/people/

Sequoia -> https://www.linkedin.com/company/sequoia/

Sales Navigator seems better than just LinkedIn

https://www.linkedin.com/sales/search/people?query=(recentSearchParam%3A(id%3A2952490922%2CdoLogHistory%3Atrue)%2Cfilters%3AList((type%3ACURRENT_COMPANY%2Cvalues%3AList((id%3Aurn%253Ali%253Aorganization%253A11190%2Ctext%3ASequoia%2520Capital%2CselectionType%3AINCLUDED%2Cparent%3A(id%3A0))))%2C(type%3ASENIORITY_LEVEL%2Cvalues%3AList((id%3A310%2Ctext%3ACXO%2CselectionType%3AINCLUDED)%2C(id%3A320%2Ctext%3AOwner%2520%252F%2520Partner%2CselectionType%3AINCLUDED)%2C(id%3A120%2Ctext%3ASenior%2CselectionType%3AINCLUDED)))))&sessionId=sWdqnl37SzytE%2FV7QPBjnQ%3D%3D&viewAllFilters=true

Try to do it 3-4 times by hand and see if it works

FYI @gpsaggese @samarth9008

**Comment by yiyunlei** [comment]
First step: Create a fake LIN account and update it to Sales Navigator for scraping.

**Comment by C-Nubela** [comment]
Hey there! If you want a more convenient way to do this, I work at Proxycurl, a B2B data provider, and you could definitely use our API to accomplish this.

[Give this page right here a quick read](https://nubela.co/proxycurl/company-api?utm_campaign=content_amplification&utm_source=github&utm_medium=social&utm_content=comments).

**Comment by samarth9008** [comment]
@yiyunlei 
Any progress on this one?

**Comment by yiyunlei** [comment]
I’m unsure whether to keep working on this issue.

**Comment by samarth9008** [comment]
Closing as not required anymore
