### ISSUE TITLE
Enrich Search4.Fintech_VC_ contacts with dropcontact

### ISSUE THREAD

**Issue by yiyunlei** [sorrentum/sorrentum#610]
We want to run the flow on the missing emails from PhantomBuster
https://docs.google.com/spreadsheets/d/1FqXXx7NfGfO8xDjbNlANqWJx0wmeXX95BaXy115W-9c/edit#gid=675826888

Let's put together a notebook called "add_emails_to_gsheet.ipynb" that

- reads a gsheet
- looks for the emails (skipping the ones that have already email) using dropcontact API
- saves the gsheet in place (with an option to create a backup for the gsheet adding a timestamp, like Missing emails -> Missing emails.20231117_082700)

Let's do a small run to make sure things work, before running a big batch

FYI @gpsaggese @samarth9008

**Comment by samarth9008** [comment]
Before starting this I would suggest to complete the follow-ups from this PR

https://github.com/sorrentum/sorrentum/pull/608

**Comment by yiyunlei** [comment]
> Before starting this I would suggest to complete the follow-ups from this PR
> 
> #608

Oh sure, thanks for the reminder.

**Comment by yiyunlei** [comment]
I've conducted experiments to obtain emails for this Google Sheet. However, it turns out that the PB results already include data from Dropcontact, so we can't get more emails than those provided by PB using Dropcontact APIs. 
(There are columns 'mailFromDropcontact', 'phoneFromDropcontact')

On the positive side, using Dropcontact is faster than PB (I tested 50 data entries in less than a minute).
@gpsaggese @samarth9008

**Comment by samarth9008** [comment]
Can this be closed now?

**Comment by yiyunlei** [comment]
> Can this be closed now?

Yes and closed.
