### ISSUE TITLE
Marketing: Get information from Signal

### ISSUE THREAD

**Issue by why2000** [sorrentum/sorrentum#612]
https://docs.google.com/document/d/1z-svt4K6dSy5ncuVZzrtL9ZYuBmknCp8UfGfxljaBNQ/edit#heading=h.g37b603qcnlr

Get information from here.
https://signal.nfx.com/investor-lists/top-fintech-seed-investors

**Comment by samarth9008** [comment]
Make sure you assigned epic and sprint

**Comment by why2000** [comment]
When accessing the website too many times, we will not be able to see any inner info of the investors. It will require us to login before being able to view details. But with certain actions we can continue loading the investors list page and read more investors' name and company. I'll implment the script in this way.

**Comment by gpsaggese** [comment]
@why2000 see convo on TG
