### ISSUE TITLE
Marketing: Process all the Tra queries with our flow

### ISSUE THREAD

**Issue by why2000** [sorrentum/sorrentum#613]
https://docs.google.com/document/d/1z-svt4K6dSy5ncuVZzrtL9ZYuBmknCp8UfGfxljaBNQ/edit#heading=h.6jseg67xphh4
This issue is a follow-up for #601. Use the notebook there to process all links mentioned in the above Gdoc

**Comment by why2000** [comment]
ALl links processed, result saved in:
https://drive.google.com/drive/folders/1MfTeNHR7sxex_rSpyp54HeJsxtLjKqy3

**Comment by gpsaggese** [comment]
Looks good. Good job @why2000. Let's review together in the next sync and we can close.

**Comment by samarth9008** [comment]
@why2000 

can this be closed?

**Comment by why2000** [comment]
@samarth9008 
Yes, the results have been uploaded to the folder, we've gone through that in a weekly meeting several weeks ago.
