### ISSUE TITLE
Postprocessing docsend data

### ISSUE THREAD

**Issue by shab95** [sorrentum/sorrentum#615]
- using this docsend data export: https://drive.google.com/file/d/1Ol6tIjElkLkEOmB1sNqBb5xmK5NK9qst/view
    - read in the notebook with helpers/hgoogle_file_api.py
- process the people(basically each row)

**Comment by shab95** [comment]
Just made the credentials for the GDrive API and connected it to the API in helpers/hgoogle_file_api.py

Looking through the available functions in this library, looks like there isn't a function yet to export a CSV as a dataframe. I see a couple options:
- using gspread-pandas looks like it has some API to get sheets
- Look at how to download/export files from gdrive using the [google drive API](https://developers.google.com/drive/api/guides/manage-downloads#python)

Would like some input whether I'm going down the right direction.
@samarth9008 

Please let me know if I am not missing this functionality if it is listed in helpers/hgoogle_file_api.py

**Comment by samarth9008** [comment]
@why2000 Can you guide @shab95 related to `hgoogle_file_api.py` since you guys have more clear idea related to it?

**Comment by samarth9008** [comment]
Probably gspread-pandas is used for google sheets, not sure about the CSVs. If you get nowhere, you can download the CSV and start making progress.

**Comment by why2000** [comment]
To use `hgoogle_file_api.py`, your service account must have access to the file/folder you are working on.  For reading GSheet, you can directly use `gspread-pandas`, it already contains most functions needed. The `hgoogle_file_api.py` is mainly used for creating and modifying certain files in Google drive.

**Comment by gpsaggese** [comment]
General rule: let's always try to "talk through the documentation". Like we can add tips and tricks like these in the doc, how-to-guide, etc. and then point to the doc from the GH issue.
I know that it takes longer in the short time, but it pays 100x dividends, so let's try to do that

**Comment by samarth9008** [comment]
@why2000 Can you create an md file related to using the `hgoogle_file_api.py`. You can mention what functionality it provides and how to use them with some examples if applicable.

**Comment by gpsaggese** [comment]
Great idea. Actually we can follow our approach of a docs/hgoogle_file_api.tutorial.md and docs/hgoogle_file.explanation.md which I think we already have in some form.
@samarth9008 pls be the DocMeister here.

**Comment by why2000** [comment]
> @why2000 Can you create an md file related to using the `hgoogle_file_api.py`. You can mention what functionality it provides and how to use them with some examples if applicable. Consider this as high priority.

Sure, will do tonight.
