### ISSUE TITLE
Add documentation for marketing works

### ISSUE THREAD

**Issue by why2000** [sorrentum/sorrentum#617]
https://docs.google.com/document/d/1z-svt4K6dSy5ncuVZzrtL9ZYuBmknCp8UfGfxljaBNQ/edit#heading=h.ay3pp84u7dmr
Documentations needed for several marketing works:
* helpers/hgoogle_file_api.py
  * `docs/Google_file_api.tutorial.md`
  * Based and referring on `Gsheet_into_pandas.md`
* Signal
  * `docs/marketing/signal.how_to_guide.md`
* Tra
  * `docs/marketing/tra.how_to_guide.md`
* Dropcontact
  * `docs/marketing/dropcontact.how_to_guide.md`

**Comment by gpsaggese** [comment]
Can you move the new files under `docs/marketing/...` and remove one level of dirs?
```
docs/marketing/signal.how_to_guide.md
docs/marketing/tra.how_to_guide.md
docs/marketing/dropcontact.how_to_guide.md
```

FYI the `doc` dir maintained up to date in cmamp so you can either work in cmamp or just merge back and forth.
We can add @yiyunlei to cmamp to make her life simpler, if needed

**Comment by why2000** [comment]
> We can add @yiyunlei to cmamp to make her life simpler, if needed

Would be good if it she can be added to cmamp. That would also be good for winter workloads since she would have more time after finals and might be able to help in cmamp.

**Comment by gpsaggese** [comment]
Added @yiyunlei to cmamp. Pls accept.

**Comment by yiyunlei** [comment]
> Added @yiyunlei to cmamp. Pls accept.

Thanks, accepted.

**Comment by samarth9008** [comment]
> @why2000
> 
> Lets create a different PR for
> 
> * helpers/hgoogle_file_api.py
>   
>   * `docs/Google_file_api.tutorial.md`
>   * Based and referring on `Gsheet_into_pandas.md`

@why2000 Any updates on this?

**Comment by why2000** [comment]
> > @why2000
> > Lets create a different PR for
> > 
> > * helpers/hgoogle_file_api.py
> >   
> >   * `docs/Google_file_api.tutorial.md`
> >   * Based and referring on `Gsheet_into_pandas.md`
> 
> @why2000 Any updates on this?

Yiyun is working on her final projects till Wednesday. Since this code work is mostly done by her, I only have a draft of the usages and shall get it polished by her after then. I can make a PR with the draft today.

**Comment by yiyunlei** [comment]
I'll work on `docs/Google_file_api.tutorial.md` this Thursday.

**Comment by samarth9008** [comment]
Closing as done
