### ISSUE TITLE
On-board Janesh Hasija

### ISSUE THREAD

**Issue by Sameep2808** [sorrentum/sorrentum#622]
Please follow this checklist. Post any errors you face in this issue.

  - [ ] Acknowledge the pledge to put time in the project [here](https://github.com/sorrentum/sorrentum/blob/master/README.md#commitment-to-contribute) 
  - [ ] Read [How to organize your work](https://github.com/sorrentum/sorrentum/blob/master/docs/How_to_organize_your_work.md)
  - [ ] Read [Quick start for developing](https://github.com/sorrentum/sorrentum/blob/master/docs/Sorrentum_development_setup.md)
  - [ ] Make sure the [Docker dev container](https://github.com/sorrentum/sorrentum/blob/master/docs/Sorrentum_development_setup.md#sorrentum-dev-docker-container-aka-dev-container-cmamp-container) works
  - [ ] Make sure the [unit tests](https://github.com/sorrentum/sorrentum/blob/master/docs/Unit_tests.md) run successfully
  - [ ] Read [Sorrentum Python coding style guide](https://github.com/sorrentum/sorrentum/blob/master/docs/Coding_Style_Guide.md)
  - [ ] Fork, star, watch the Sorrentum repo so that GitHub promotes our repo (we gotta work the system)
  - [ ] Get assigned a warm-up issue
  - [ ] Learn about the [Morning Email](https://github.com/sorrentum/sorrentum/blob/master/docs/General_rules_of_collaboration.md#morning-email)
  - [ ] How to pass through your first [review](https://github.com/sorrentum/sorrentum/blob/master/docs/First_review_process.md)
  - [ ] If you are graduating soon and you would like to get a full-time job in one of the companies in the Sorrentum ecosystem reach out to GP at gp@sorrentum.org
 
FYI @gpsaggese @samarth9008

**Comment by samarth9008** [comment]
Not here for now. We need to create it in the asana.

**Comment by samarth9008** [comment]
Like this

https://app.asana.com/0/1204526145297526/1205349910031843/f

**Comment by Er1-x** [comment]
How can  I join in Sorrentum project?

**Comment by samarth9008** [comment]
Not required so closing.
