### ISSUE TITLE
Integrate text editor with ChatGPT

### ISSUE THREAD

**Issue by why2000** [sorrentum/sorrentum#624]
The use case
I'm writing a lot of documentation with vim
Sometimes I want to use ChatGPT to clean up text, other times I want to apply a prompt to a piece of text, etc.
Right now I copy-paste to ChatGPT app back and forth, while I want to have it 

Create a Python to apply a GPT prompt to a piece of text coming from stdin and stdout (so that we can easily integrate with vim)

It should be model after ./dev_scripts/documentation/lint_txt.py

The command should look like:
process_chatgpt.py --config XYZ --prompt_id XYZ

where
`--config` is about ChatGPT3 vs 4
`--prompt_id` points to hardwired prompts inside the Python code

**Comment by why2000** [comment]
So actually openai's most recent API named `Assistant` is so powerful that I think it covers the current need and much more. So I write a library for fully functional Assistant API calling. With a sample instruction for markdown linting, which has an amazing result even with gpt-3.5 (results are in `dev_scripts/chatgpt/example_data`). See `helpers/hchatgpt.py` and `helpers/hchatgpt_instuctions.py` in the PR connected for the library.

**Comment by why2000** [comment]
@gpsaggese 
Looks like once uploaded to github, the openAI API key is revoked immediately. We should set up an openAI "organization" and include collaborators in it, so that each of us can use our own API key instead of publishing any key to a public place and get revoked.

**Comment by gpsaggese** [comment]
I'm not sure why it's revoked but we should keep the API keys on env vars. Yes, we can create a better org.

I'm reading your code and then we can have an informed discussion on how to use it

**Comment by samarth9008** [comment]
Closing as PR is merged
