### ISSUE TITLE
Document marketing flow

### ISSUE THREAD

**Issue by gpsaggese** [sorrentum/sorrentum#627]
Create a docs/marketing/all.marketing.how_to_guide.md

For each pipeline, there is either a description of how to use it or a pointer to a document

From https://docs.google.com/document/d/18_ArduguU2D9KjhCLgu2SIrgp5VoiYjPu7VmHcOLwLo/edit?pli=1#heading=h.qkyukal0uzg
```
# tracxn -> VC firms
(Henry)
There is a document.
Pointer to the output
Maybe people profile?

# VC firms -> LinkedIn company
Search for the name on LIN or try to guess the name of the page, PhantomBuster
(Yiyun)

VC names -> LIN people working there that are decision makers (PB)

LIN / SN query -> LIN people (PB search export)
It takes few seconds to extract 1000 people

LIN people -> emails (PB profile scrape)
(Yiyun + Shab)
Slow with PB: 10 people / 3 hours

LIN groups -> LIN people (PB)
Instead of having a search, the entry point is a LIN group. 

LIN people -> LIN messages (LinkedIn Message Sender)

Signal NFX -> script -> First, Last name, Company
(Henry)
There is a document
Pointer to the output
```

**Comment by samarth9008** [comment]
@why2000 

Lets start with creating a master doc which has reference to all the marketting pipelines we have implemented till now. Doc should contain

- Pipeline name
- Summarized version of what it is doing
- Reference to input and output data

Feel free to add more info if required

**Comment by samarth9008** [comment]
Closing as done
