### ISSUE TITLE
Expose the linter container to Sorrentum contributors

### ISSUE THREAD

**Issue by gpsaggese** [sorrentum/sorrentum#63]
Can we just commit the same container also to DockerHub for public consumption?
No need to change our internal toolchain.
We build in the usual way and then we add a switch to commit the container also outside.

P1

**Comment by jsmerix** [comment]
Added to the dockerhub

![image.png](https://images.zenhubusercontent.com/618bd253fce6ad42e07d4295/54a7c937-13d8-4f44-a526-13e99865a83d)
