### ISSUE TITLE
Conventions to follow

### ISSUE THREAD

**Issue by samarth9008** [sorrentum/sorrentum#639]
@Shaunak01 

Let start documenting the convention as you move forward and also make you and other students are implementing on the go. I would suggest to create an md file in `sorrentum_sandbox` folder with name `all.data605.conventions.md`. We will point students to this doc from the beginning of the semester so that we do not keep repeating same info to all the students all the time. We just point them to the doc.

Create a doc with this following sections

Convention to follow: 

Building the coding environment
- Downloading the VM if you are a windows users and install docker (For all users)
   Add this section - [Supporting OS](https://github.com/sorrentum/sorrentum/blob/master/docs/work_tools/all.sorrentum_development.how_to_guide.md#supporting-os)  

- Cloning the code - [Cloning the code](https://github.com/sorrentum/sorrentum/blob/master/docs/work_tools/all.sorrentum_development.how_to_guide.md#cloning-the-code)

- Building the thin env for running the linter - Add `thin environment` section only from [Sorrentum Dev Docker container (aka dev container, cmamp container)](https://github.com/sorrentum/sorrentum/blob/master/docs/work_tools/all.sorrentum_development.how_to_guide.md#sorrentum-dev-docker-container-aka-dev-container-cmamp-container)

Coding Style 
- Follow the coding style from here - https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.coding_style.how_to_guide.md
- Just add the link to this doc
- Make sure to internalize it

Writing and contributing the code
- Always start with creating an issue first, providing a summary of what you want to implement and assign it to yourself and your team
- Add just points of this section [How to contribute code (short version)](https://github.com/sorrentum/sorrentum/blob/master/docs/work_tools/all.sorrentum_development.how_to_guide.md#how-to-contribute-code-short-version)

FYI @gpsaggese

**Comment by gpsaggese** [comment]
Good specs @samarth9008

Let's think of Data605 students as contributors to Sorrentum to keep things simple. 

Our goal is to get somebody with Python experience and make them able to commit code in our repo without our head explode.

There are already some files
./docs/onboarding/all.sign_up_for_sorrentum.how_to_guide.md
./docs/onboarding/all.sorrentum_intro.reference.md
./docs/work_tools/all.sorrentum_development.how_to_guide.md

Let's review them and add more content to these files rather than new files pointing to each other.

**Comment by gpsaggese** [comment]
Point taken. Then let's separate Sorrentum users in "users" and "advanced_users" and we can tag different docs with the audience.

We want to keep DATA605 and Sorrentum users as aligned as possible.

Makes sense?

**Comment by samarth9008** [comment]
@Shaunak01 For now lets make this small changes

Can you create a new PR moving this [file](https://github.com/sorrentum/sorrentum/blob/master/sorrentum_sandbox/all.data605.conventions.md) to `docs/work_tools/`.

Lets rename it to basic_users.sorrentum_development.how_to_guide.md and point our student to this file.

**Comment by gpsaggese** [comment]
Plan sounds good. Can we call the file `docs/work_tools/all.basic_sorrentum_development.how_to_guide.md`?

**Comment by samarth9008** [comment]
Closing as done.
