### ISSUE TITLE
Permission Denied Error while Activating Thin Environment 

### ISSUE THREAD

**Issue by Shaunak01** [sorrentum/sorrentum#642]
Encountered a "Permission Denied" error while attempting to activate the Thin environment. The error message is as follows:

                                               command : source dev_scripts/setenv_amp.sh
                                             bash: dev_scripts/setenv_amp.sh: Permission denied

This issue seems to be related to insufficient permissions to execute the mentioned script. Followed the build steps, sourcing dev_scripts/client_setup/build.sh successfully, but encountered this obstacle when sourcing setenv_amp.sh.

FYI @gpsaggese @samarth9008

**Comment by gpsaggese** [comment]
Weird. `source` doesn't execute (and so it should have problems with perms). Yes, can you pls post more context?

**Comment by samarth9008** [comment]
Closing as resolved
