### ISSUE TITLE
Sorrentum Contributors Conventions

### ISSUE THREAD

**Issue by Shaunak01** [sorrentum/sorrentum#643]
This document serves as a comprehensive guide for Sorrentum contributors, detailing the conventions to be adhered to throughout the development process. By establishing and documenting these conventions, our objective is to enhance information flow and ensure a seamless contribution experience.

FYI @samarth9008 @gpsaggese

**Comment by gpsaggese** [comment]
Sounds good but let's reuse/reorg all the doc we already have for Sorrentum

./docs/infra/ck.sorrentum_experiments_aws_infrastructure.explanation.md
./docs/onboarding/all.sign_up_for_sorrentum.how_to_guide.md
./docs/onboarding/all.sorrentum_intro.reference.md
./docs/work_tools/all.sorrentum_development.how_to_guide.md

**Comment by samarth9008** [comment]
@Shaunak01 Can you add to these docs inside the convention doc?

**Comment by Shaunak01** [comment]
For sure!

**Comment by samarth9008** [comment]
Closing as done.
