### ISSUE TITLE
On-board Krishna Taduri

### ISSUE THREAD

**Issue by sonaalKant** [sorrentum/sorrentum#664]
Please follow this checklist. Post any errors you face in this issue.

  - [x] Acknowledge the pledge to put time in the project [here](https://github.com/sorrentum/sorrentum/blob/master/README.md#Important) 
  - [x] Read [How to organize your work](https://github.com/sorrentum/sorrentum/blob/master/docs/work_organization/all.organize_your_work.how_to_guide.md)
  - [x] Read [Quick start for developing](https://github.com/sorrentum/sorrentum/blob/master/docs/work_tools/sorrentum.development.how_to_guide.md)
  - [x] Make sure the [Docker dev container](https://github.com/sorrentum/sorrentum/blob/master/docs/work_tools/all.docker.how_to_guide.md) works
  - [x] Make sure the [unit tests](https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.write_unit_tests.how_to_guide.md) run successfully
  - [x] Read [Sorrentum Python coding style guide](https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.coding_style.how_to_guide.md)
  - [x] Fork, star, watch the Sorrentum repo so that GitHub promotes our repo (we gotta work the system)
  - [ ] Get assigned a warm-up issue
  - [x] Learn about the [Morning Email](https://github.com/sorrentum/sorrentum/blob/master/docs/work_organization/all.team_collaboration.how_to_guide.md#morning-email)
  - [x] How to do a [review](https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.submit_code_for_review.how_to_guide.md)
  - [x] If you are graduating soon and you would like to get a full-time job in one of the companies in the Sorrentum ecosystem reach out to GP at [gp@sorrentum.org](mailto:gp@sorrentum.org)

FYI @gpsaggese @samarth9008

**Comment by samarth9008** [comment]
The link to Read [Quick start for developing](https://github.com/sorrentum/sorrentum/blob/master/docs/work_tools/sorrentum.development.how_to_guide.md) is changed. Pls refer the updated link.

**Comment by tkpratardan** [comment]
@sonaalKant I have gone through the checklist and documentation. Could you please assign a warm-up task?

**Comment by tkpratardan** [comment]
@samarth9008 @sonaalKant
I am facing a similar issue while trying to enter the docker container in thin env, similar to #678 (aws authentication). Please let me know if there is a workaround.

**Comment by gpsaggese** [comment]
Fixed. See https://github.com/sorrentum/sorrentum/issues/668#issuecomment-1963078936

**Comment by samarth9008** [comment]
Updated link for setup - https://github.com/sorrentum/sorrentum/blob/master/docs/onboarding/sorrentum.set_up_development_environment.how_to_guide.md

**Comment by sonaalKant** [comment]
I have assigned you the issue https://github.com/sorrentum/sorrentum/issues/694

**Comment by gpsaggese** [comment]
We can close these bugs and create follow up, if there was anything to improve that we found during the on-boarding
