### ISSUE TITLE
On-board Swathi Baskaran

### ISSUE THREAD

**Issue by sonaalKant** [sorrentum/sorrentum#666]
Please follow this checklist. Post any errors you face in this issue.

  - [x] Acknowledge the pledge to put time in the project [here](https://github.com/sorrentum/sorrentum/blob/master/README.md#Important) 
  - [x] Read [How to organize your work](https://github.com/sorrentum/sorrentum/blob/master/docs/work_organization/all.organize_your_work.how_to_guide.md)
  - [x] Read [Quick start for developing](https://github.com/sorrentum/sorrentum/blob/master/docs/work_tools/sorrentum.development.how_to_guide.md)
  - [x] Make sure the [Docker dev container](https://github.com/sorrentum/sorrentum/blob/master/docs/work_tools/all.docker.how_to_guide.md) works
  - [x] Make sure the [unit tests](https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.write_unit_tests.how_to_guide.md) run successfully
  - [x] Read [Sorrentum Python coding style guide](https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.coding_style.how_to_guide.md)
  - [x] Fork, star, watch the Sorrentum repo so that GitHub promotes our repo (we gotta work the system)
  - [x] Get assigned a warm-up issue
  - [x] Learn about the [Morning Email](https://github.com/sorrentum/sorrentum/blob/master/docs/work_organization/all.team_collaboration.how_to_guide.md#morning-email)
  - [x] How to do a [review](https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.submit_code_for_review.how_to_guide.md)
  - [x] If you are graduating soon and you would like to get a full-time job in one of the companies in the Sorrentum ecosystem reach out to GP at [gp@sorrentum.org](mailto:gp@sorrentum.org)

FYI @gpsaggese @samarth9008

**Comment by samarth9008** [comment]
The link to Read [Quick start for developing](https://github.com/sorrentum/sorrentum/blob/master/docs/work_tools/sorrentum.development.how_to_guide.md) is changed. Pls refer the updated link.

**Comment by 11swathi** [comment]
@sonaalKant I have gone through the above checklist. Could you please assign me a warm up issue ?

**Comment by samarth9008** [comment]
https://github.com/sorrentum/sorrentum/issues/665#issuecomment-1962398137

**Comment by 11swathi** [comment]
I changed the code in repo_config.py file.

 ```
rc = os.system(cmd)
    _print("cmd=%s -> rc=%s" % (cmd, rc))
    # dind is supported on both Mac and GH Actions.
    check_repo = os.environ.get("AM_REPO_CONFIG_CHECK", "True") != "True"
```
I changed check_repo = "True". It worked and I ran pytest to see this result.

============= 135 failed, 2350 passed, 410 skipped, 2 xfailed, 22 errors in 448.40s (0:07:28) ============

I checked the comment in #678. Will go ahead and work on my task. Thanks!

**Comment by sonaalKant** [comment]
I have assigned you the warm up issue https://github.com/sorrentum/sorrentum/issues/696.
