### ISSUE TITLE
On-board Weiqi Yan

### ISSUE THREAD

**Issue by sonaalKant** [sorrentum/sorrentum#667]
Please follow this checklist. Post any errors you face in this issue.

  - [x] Acknowledge the pledge to put time in the project [here](https://github.com/sorrentum/sorrentum/blob/master/README.md#Important) 
  - [x] Read [How to organize your work](https://github.com/sorrentum/sorrentum/blob/master/docs/work_organization/all.organize_your_work.how_to_guide.md)
  - [x] Read [Quick start for developing](https://github.com/sorrentum/sorrentum/blob/master/docs/work_tools/sorrentum.development.how_to_guide.md)
  - [x] Make sure the [Docker dev container](https://github.com/sorrentum/sorrentum/blob/master/docs/work_tools/all.docker.how_to_guide.md) works
  - [x] Make sure the [unit tests](https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.write_unit_tests.how_to_guide.md) run successfully
  - [x] Read [Sorrentum Python coding style guide](https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.coding_style.how_to_guide.md)
  - [x] Fork, star, watch the Sorrentum repo so that GitHub promotes our repo (we gotta work the system)
  - [x] Get assigned a warm-up issue
  - [x] Learn about the [Morning Email](https://github.com/sorrentum/sorrentum/blob/master/docs/work_organization/all.team_collaboration.how_to_guide.md#morning-email)
  - [x] How to do a [review](https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.submit_code_for_review.how_to_guide.md)
  - [ ] If you are graduating soon and you would like to get a full-time job in one of the companies in the Sorrentum ecosystem reach out to GP at [gp@sorrentum.org](mailto:gp@sorrentum.org)

FYI @gpsaggese @samarth9008

**Comment by samarth9008** [comment]
The link to Read [Quick start for developing](https://github.com/sorrentum/sorrentum/blob/master/docs/work_tools/sorrentum.development.how_to_guide.md) is changed. Pls refer the updated link.

**Comment by Er1-x** [comment]
@sonaalKant I have completed the above checklist and have preliminarily set up the environment. Can you please help me get assigned a warm up issue ?

**Comment by Er1-x** [comment]
I have encountered the same issue in #665 and solved by Samarth's suggestion by changing 
[sorrentum/tasks.py](https://github.com/sorrentum/sorrentum/blob/d39076822ab9d6bf20f6b7e59c196a6b6589ecc3/tasks.py#L167)
Line 167 in [d390768](https://github.com/sorrentum/sorrentum/commit/d39076822ab9d6bf20f6b7e59c196a6b6589ecc3)

 "CK_ECR_BASE_PATH": ECR_BASE_PATH, 
"CK_ECR_BASE_PATH": ECR_BASE_PATH -> "CK_ECR_BASE_PATH": "sorrentum"

**Comment by Er1-x** [comment]
I have encountered the same issue in #665  and solved by Samarth's suggestion by changing 
"CK_ECR_BASE_PATH": ECR_BASE_PATH -> "CK_ECR_BASE_PATH": "sorrentum"
in [sorrentum/tasks.py](https://github.com/sorrentum/sorrentum/blob/d39076822ab9d6bf20f6b7e59c196a6b6589ecc3/tasks.py#L167)

**Comment by Er1-x** [comment]
Facing a problem about jupyter notebook.

**Comment by Er1-x** [comment]
@sonaalKant Facing a problem using jupyter notebook
I'm using WSL . It's ok for me to open a jupyter notebook by command 
```shell
jupyter-notebook --allow-root
``` 
but when i use the command in [Quick start for developing](https://github.com/sorrentum/sorrentum/blob/master/docs/work_tools/sorrentum.development.how_to_guide.md)
```shell
i docker_jupyter
``` 
I can't open the webpage in browser. I found that the port was 1, which is kind of unusual. Did anyone meet this problem before?
```
[W 06:50:24.729 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[W 06:50:24.729 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using authentication. This is highly insecure and not recommended.
[I 06:50:24.732 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.6.3
[I 06:50:24.810 NotebookApp] [Jupytext Server Extension] Deriving a JupytextContentsManager from LargeFileManager
[I 06:50:24.815 NotebookApp] Serving notebooks from local directory: /app
[I 06:50:24.815 NotebookApp] Jupyter Notebook 6.5.6 is running at:
[I 06:50:24.815 NotebookApp] http://605f3296960c:1/
[I 06:50:24.815 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 06:50:24.821 NotebookApp] No web browser found: could not locate runnable browser.
```

**Comment by gpsaggese** [comment]
Sorry @Er1-x we don't support Windows and WSL. We tried to get it working for several years but there are always small problems like the one you are experiencing, that make difficult to collaborate

We ask people to use dual boot or VM, see
https://github.com/sorrentum/sorrentum/blob/master/docs/work_tools/sorrentum.development.how_to_guide.md#supporting-os

**Comment by Er1-x** [comment]
> Sorry @Er1-x we don't support Windows and WSL. We tried to get it working for several years but there are always small problems like the one you are experiencing, that make difficult to collaborate
> 
> We ask people to use dual boot or VM, see https://github.com/sorrentum/sorrentum/blob/master/docs/work_tools/sorrentum.development.how_to_guide.md#supporting-os

okay, I will switch to VM

**Comment by samarth9008** [comment]
> I have encountered the same issue in https://github.com/sorrentum/sorrentum/issues/665 and solved by Samarth's suggestion by changing
"CK_ECR_BASE_PATH": ECR_BASE_PATH -> "CK_ECR_BASE_PATH": "sorrentum"
in [sorrentum/tasks.py](https://github.com/sorrentum/sorrentum/blob/d39076822ab9d6bf20f6b7e59c196a6b6589ecc3/tasks.py#L167)


FYI This change is not required anymore. Can you revert this changes, pull the latest master and see if it works? LMK if it doesn't.

**Comment by Er1-x** [comment]
> > I have encountered the same issue in #665 and solved by Samarth's suggestion by changing
> > "CK_ECR_BASE_PATH": ECR_BASE_PATH -> "CK_ECR_BASE_PATH": "sorrentum"
> > in [sorrentum/tasks.py](https://github.com/sorrentum/sorrentum/blob/d39076822ab9d6bf20f6b7e59c196a6b6589ecc3/tasks.py#L167)
> 
> FYI This change is not required anymore. Can you revert this changes, pull the latest master and see if it works? LMK if it doesn't.

It works. And I think this problem also has sth to do with WSL, cuz I pull the master in WSL it still remains. Anyway it works now in the VM environment.

**Comment by Er1-x** [comment]
> > I have encountered the same issue in #665 and solved by Samarth's suggestion by changing
> > "CK_ECR_BASE_PATH": ECR_BASE_PATH -> "CK_ECR_BASE_PATH": "sorrentum"
> > in [sorrentum/tasks.py](https://github.com/sorrentum/sorrentum/blob/d39076822ab9d6bf20f6b7e59c196a6b6589ecc3/tasks.py#L167)
> 
> FYI This change is not required anymore. Can you revert this changes, pull the latest master and see if it works? LMK if it doesn't.

It works.

**Comment by Er1-x** [comment]
When I'm running fast test with `i run_fast_tests` in new VM environment, this error showed up.
```
17:25:54 - INFO  lib_tasks_docker.py _docker_pull:227                   image='sorrentum/cmamp:dev'
docker pull sorrentum/cmamp:dev
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/create?fromImage=sorrentum%2Fcmamp&tag=dev": dial unix /var/run/docker.sock: connect: permission denied
```
Is this error triggered by some new commits?

**Comment by Er1-x** [comment]
I'm running pytest by `i run_fast_tests` . It failed , the error log points that 
```
=================================== FAILURES ===================================
_________________ TestReplayedCcxtExchange1.test_create_order1 _________________
Traceback (most recent call last):
  File "/usr/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.9/unittest/case.py", line 593, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/app/oms/broker/ccxt/test/test_replayed_ccxt_exchange.py", line 128, in test_create_order1
    ccxt_orders = self.get_ccxt_orders()
  File "/app/oms/broker/ccxt/test/test_replayed_ccxt_exchange.py", line 64, in get_ccxt_orders
    s3fs = hs3.get_s3fs(aws_profile)
  File "/app/helpers/hs3.py", line 780, in get_s3fs
    aws_credentials = get_aws_credentials(aws_profile)
  File "/app/helpers/hs3.py", line 723, in get_aws_credentials
    config = _get_aws_config(file_name)
  File "/app/helpers/hs3.py", line 520, in _get_aws_config
    hdbg.dassert_file_exists(file_name)
  File "/app/helpers/hdbg.py", line 785, in dassert_file_exists
    _dfatal(txt, msg, *args, only_warning=only_warning)
  File "/app/helpers/hdbg.py", line 142, in _dfatal
    dfatal(dfatal_txt)
  File "/app/helpers/hdbg.py", line 71, in dfatal
    raise assertion_type(ret)
AssertionError: 
################################################################################
* Failed assertion *
File '/home/.aws/credentials' doesn't exist
```

**Comment by samarth9008** [comment]
Ok to have this aws failure

**Comment by gpsaggese** [comment]
> Hey @Er1-x , I had faced a similar issue. Have mentioned a workaround here [#668 (comment)](https://github.com/sorrentum/sorrentum/issues/668#issuecomment-1963042611)

Good job helping.

**Comment by Er1-x** [comment]
@sonaalKant @gpsaggese If this aws failure is Ok to have, I think I'm ready to be assigned a warm-up issue.

**Comment by sonaalKant** [comment]
I have assigned you the warm up issue https://github.com/sorrentum/sorrentum/issues/692

**Comment by Er1-x** [comment]
@gpsaggese Is that Telegram group for new contributors closed ?

**Comment by sonaalKant** [comment]
If you are talking about "Sorrentum - Researchers", then no. It is still active.

**Comment by gpsaggese** [comment]
All done here closing
