### ISSUE TITLE
environment activation only works in src/sorrentum1 folder

### ISSUE THREAD

**Issue by jayhsu0627** [sorrentum/sorrentum#672]
It's inconvenient to activate the environment by `source dev_scripts/setenv_amp.sh`, because we have to navigate to `~/src/sorrentum1` every time we initialize a terminal. 
If we run this command by `source ~/src/sorrentum1/dev_scripts/setenv_amp.sh` from anywhere, we will came across this error:
```
/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin
/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin
/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin
/Library/TeX/texbin
# Set PYTHONPATH
PYTHONPATH=
/Users/USERNAME

/Users/USERNAME/src/sorrentum1/dev_scripts/setenv_amp.sh:source:85: no such file or directory: /Users/USERNAME/dev_scripts/setenv_amp.configure_env.sh
```

**Comment by gpsaggese** [comment]
We use tmux and there is a script `./dev_scripts/tmux_amp.sh` to create a tmux system and source automatically setenv_amp.

Can you try that? tmux is one of the best-kept secrets once we learn how to use it.  (I think we had some doc about this)

@samarth9008 / @sonaalKant can help with this

**Comment by jayhsu0627** [comment]
thanks! I've test with `./dev_scripts/tmux_amp.sh amp 1`
