### ISSUE TITLE
On-board Nehal Pillai

### ISSUE THREAD

**Issue by gpsaggese** [sorrentum/sorrentum#678]
Please follow this checklist. Post any errors you face in this issue.

  - [x] Acknowledge the pledge to put time in the project [here](https://github.com/sorrentum/sorrentum/blob/master/README.md#Important) 
  - [x] Read [How to organize your work](https://github.com/sorrentum/sorrentum/blob/master/docs/work_organization/all.organize_your_work.how_to_guide.md)
  - [x] Read [Quick start for developing](https://github.com/sorrentum/sorrentum/blob/master/docs/work_tools/sorrentum.development.how_to_guide.md)
  - [x] Make sure the [Docker dev container](https://github.com/sorrentum/sorrentum/blob/master/docs/work_tools/all.docker.how_to_guide.md) works
  - [x] Make sure the [unit tests](https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.write_unit_tests.how_to_guide.md) run successfully
  - [x] Read [Sorrentum Python coding style guide](https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.coding_style.how_to_guide.md)
  - [x] Fork, star, watch the Sorrentum repo so that GitHub promotes our repo (we gotta work the system)
  - [x] Get assigned a warm-up issue
  - [x] Learn about the [Morning Email](https://github.com/sorrentum/sorrentum/blob/master/docs/work_organization/all.team_collaboration.how_to_guide.md#morning-email)
  - [x] How to do a [review](https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.submit_code_for_review.how_to_guide.md)
  - [x] If you are graduating soon and you would like to get a full-time job in one of the companies in the Sorrentum ecosystem reach out to GP at [gp@sorrentum.org](mailto:gp@sorrentum.org)

FYI @samarth9008 @sonaalKant

**Comment by nehalR777** [comment]
@gpsaggese sir, A quick update on the tasks I wrapped up with today: I got started with some reading, understanding how things work in brief. Up next-will pick up tasks that include setting up the docker container and running the unit test cases.
cc: @samarth9008 @sonaalKant

**Comment by nehalR777** [comment]
Hey @samarth9008 @sonaalKant , 
I am facing a similar error as @Jd8111997 as mentioned here - https://github.com/sorrentum/sorrentum/issues/668#issuecomment-1962743616

Here is the error I'm facing:
```
alchemist@alchemist:/src/sorrentum1$ i docker_bash
One and only one set-up config should be true:
is_cmamp_prod=False
is_dev4=False
is_dev_ck=False
is_ig_prod=False
is_inside_ci=False
is_mac=False
WARNING: Can't find s3fs: continuing
Traceback (most recent call last):
  File "/usr/bin/invoke", line 11, in <module>
    load_entry_point('invoke==1.4.1', 'console_scripts', 'invoke')()
  File "/usr/lib/python3/dist-packages/invoke/program.py", line 373, in run
    self.parse_collection()
  File "/usr/lib/python3/dist-packages/invoke/program.py", line 465, in parse_collection
    self.load_collection()
  File "/usr/lib/python3/dist-packages/invoke/program.py", line 696, in load_collection
    module, parent = loader.load(coll_name)
  File "/usr/lib/python3/dist-packages/invoke/loader.py", line 76, in load
    module = imp.load_module(name, fd, path, desc)
  File "/usr/lib/python3.10/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.10/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 719, in _load
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/src/sorrentum1/tasks.py", line 10, in <module>
    from helpers.lib_tasks import (  # This is not an invoke target.
  File "/src/sorrentum1/helpers/lib_tasks.py", line 15, in <module>
    from helpers.lib_tasks_docker_release import *  # isort:skip  # noqa: F401,F403 # pylint: disable=unused-import,unused-wildcard-import,wildcard-import
  File "/src/sorrentum1/helpers/lib_tasks_docker_release.py", line 18, in <module>
    import helpers.hs3 as hs3
  File "/src/sorrentum1/helpers/hs3.py", line 49, in <module>
    AwsProfile = Optional[Union[str, s3fs.core.S3FileSystem]]
NameError: name 's3fs' is not defined
(amp.client_venv)

**Comment by nehalR777** [comment]
@samarth9008 @sonaalKant , 
It is trying to fetch an AWS profile 'ck' along with its related credentials.

**Comment by gpsaggese** [comment]
@samarth9008 fixed it at https://github.com/sorrentum/sorrentum/pull/686
Pls confirm

**Comment by nehalR777** [comment]
Thank you @gpsaggese @samarth9008 , it is working fine now :)

**Comment by nehalR777** [comment]
Hey @samarth9008 @sonaalKant ,
After entering the thin environment, I just ran pytest to see if everything ran well at my end and I saw the following text in the end:
```
!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 183 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!
=============================== 8 skipped, 183 errors in 19.01s =============================== 
```

Upon checking those errors, I noticed that they are mostly due to missing Python packages or libraries. Do we have a requirements.txt file already available that I could use to overcome this with ease?

**Comment by nehalR777** [comment]
@samarth9008 , I apologize for a delayed response 
running pytest inside the docker container gives me the following result:
```======= 136 failed, 2349 passed, 410 skipped, 2 xfailed, 22 errors in 848.07s (0:14:08) =======```

and for most of these failed test cases, I see one thing in common ```configparser.NoSectionError: No section: 'ck' ```

Might be because of the 'ck' aws profile we were referring to for a previous issue.

**Comment by samarth9008** [comment]
Updated link for setup - https://github.com/sorrentum/sorrentum/blob/master/docs/onboarding/sorrentum.set_up_development_environment.how_to_guide.md

**Comment by nehalR777** [comment]
Sure @samarth9008 , thank you for the updated document, I have gone through the checklist. Could you please assign me a warm-up issue?

**Comment by gpsaggese** [comment]
@samarth9008 moving ahead with the warm up issues sounds good, and yes let's file a bug with the failing tests to investigate. Probably just due to CK vs Sorrentum.

Let's also check why the GH action is passing. We might be skipping those tests or maybe we inject a placeholder AWS credentials. Ideally, we should align the GH action with what people run.

**Comment by sonaalKant** [comment]
I have assigned you your warm up issue https://github.com/sorrentum/sorrentum/issues/697.

**Comment by nehalR777** [comment]
Hey @samarth9008, As mentioned in https://github.com/sorrentum/sorrentum/issues/678#issuecomment-1964112814 - you can find the failed test cases in the text file below. 
[pytest_result.txt](https://github.com/sorrentum/sorrentum/files/14426135/pytest_result.txt)
cc: @gpsaggese

**Comment by nehalR777** [comment]
@samarth9008 can the recently closed issue https://github.com/sorrentum/sorrentum/issues/687  be considered a warmup task to tick on the checklist? I have also been actively working on another assigned issue https://github.com/sorrentum/sorrentum/issues/697
