### ISSUE TITLE
Fix to_datetime warning with 'unit'

### ISSUE THREAD

**Issue by samarth9008** [sorrentum/sorrentum#681]
Originally from https://github.com/cryptokaizen/cmamp/issues/6195

Currently when we use `pd.to_datetime` with specified `unit` like in `amp/oms/broker/ccxt/ccxt_logger.py` ([link](https://github.com/sorrentum/sorrentum/blob/c84e9ed114eadc7d6c5b44ff9243bd90d7ddacbe/oms/broker/ccxt/ccxt_logger.py#L1292)), we have a warning issued in the notebooks:
```
/app/amp/oms/broker/ccxt/ccxt_logger.py:1176: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
```

This gets annoying with a wall of warnings (see http://172.30.2.44/notebooks/Master_bid_ask_execution_analysis.20231115-144118.html)

Solution should be quite straightforward, I'd expect smth like
```
srs["info_datetime"] = pd.to_datetime(
    pd.to_numeric(info_timestamp), unit="ms", utc=True
)
```

So the task is to:
- [ ] Look for all the cases when we call `to_datetime` with `unit` explicitly specified
- [ ] Implement the fix
- [ ] Run some notebook to confirm that warning disappeared (do not commit the notebook though)

Seems easy, could be outsourced

FYI @gitpaulsmith @PomazkinG @rheenina

**Comment by samarth9008** [comment]
FYI @sonaalKant

**Comment by 11swathi** [comment]
@samarth9008 @sonaalKant I am not bale to access these links https://github.com/cryptokaizen/cmamp/issues/6195
Is it because I don't have access to this ?

**Comment by samarth9008** [comment]
You don't require access to it. This is just for our own purpose

**Comment by samarth9008** [comment]
Updated the links which I can and required for you. You can run the notebook from docker jupyter from Updated link for setup - https://github.com/sorrentum/sorrentum/blob/master/docs/onboarding/sorrentum.set_up_development_environment.how_to_guide.md

**Comment by 11swathi** [comment]
I ran the ccxt_logger.py file. I ran it using the i docker_jupyter command. I don't see any warnings after I ran the notebook. Could you please clarify if I am doing the correct thing or am I missing something? @samarth9008

**Comment by samarth9008** [comment]
> I ran the ccxt_logger.py file. I ran it using the i docker_jupyter command. I don't see any warnings after I ran the notebook. Could you please clarify if I am doing the correct thing or am I missing something? @samarth9008

Sorry for not mentioning the specs clearly. The notebook you have to run inside the jupyer docekr container is https://github.com/sorrentum/sorrentum/blob/master/oms/notebooks/Master_bid_ask_execution_analysis.ipynb

This notebook internally uses ` ccxt_logger.py` file.

When you will run this notebook, you will find a warning something like this

![image](https://github.com/sorrentum/sorrentum/assets/58821247/6b692230-e0dc-4a8d-a7ba-a810499e8375)

The end goal is, whenever we run the notebook this kind of warning should not appear.


Once this part is done, Make sure to look at other places in the code as well. If want to search something repo wide, you can use our internal tool on cli inside thin env `jackpy pd.to_datetime`

**Comment by gpsaggese** [comment]
@samarth9008 Another approach is to create a smaller unit test reproducing the problem instead of running the notebook

**Comment by 11swathi** [comment]
I ran the notebook with `i docker_jupyter` command and I am getting errors, I tried checking the code, I don't understand the error. 

Here is the screenshot and the error

<img width="1093" alt="image" src="https://github.com/sorrentum/sorrentum/assets/46857476/0500aa5b-514f-443e-9d96-ee3116e38d21">

```
AssertionError                            Traceback (most recent call last)
Cell In[6], line 1
----> 1 ccxt_log_reader = obcccclo.CcxtLogger(system_log_dir)
      2 data = ccxt_log_reader.load_all_data(
      3     convert_to_dataframe=True, abort_on_missing_data=False
      4 )

File /app/oms/broker/ccxt/ccxt_logger.py:138, in CcxtLogger.__init__(self, log_dir, mode)
    120     fields = [
    121         "args",
    122         "broker_config",
   (...)
    135         "reduce_only_child_orders",
    136     ]
    137     self._has_data = {field: False for field in fields}
--> 138     self._init_log_subdirectories()
    139 # We aim to log the initial exchange position once and avoid redundant
    140 # position logging. This strategy simplifies the process of mock/replay
    141 # for the exchange, as position updates are based on the executed
    142 # orders rather than continuous logging. By reducing the frequency of
    143 # position logging, we enhance logging efficiency and streamline
    144 # debugging when replaying exchange scenarios.
    145 self._enable_positions_logging = True

File /app/oms/broker/ccxt/ccxt_logger.py:1471, in CcxtLogger._init_log_subdirectories(self)
   1467     _LOG.info(
   1468         "No log directory provided, loading log files is impossible."
   1469     )
   1470     return
-> 1471 hdbg.dassert_path_exists(self._log_dir)
   1472 # Check if the broker config is saved.
   1473 # The presence of the config is not strictly enforced since earlier
   1474 # experiments did not dump the config data.
   1475 broker_config_file = os.path.join(self._log_dir, self.BROKER_CONFIG)

File /app/helpers/hdbg.py:754, in dassert_path_exists(path, msg, only_warning, *args)
    752 if not os.path.exists(path):
    753     txt = f"Path '{path}' doesn't exist!"
--> 754     _dfatal(txt, msg, *args, only_warning=only_warning)

File /app/helpers/hdbg.py:142, in _dfatal(txt, msg, only_warning, *args)
    139     _LOG.warning(dfatal_txt)
    140 else:
    141     # Abort.
--> 142     dfatal(dfatal_txt)

File /app/helpers/hdbg.py:71, in dfatal(message, assertion_type)
     69 if assertion_type is None:
     70     assertion_type = AssertionError
---> 71 raise assertion_type(ret)

AssertionError: 
################################################################################
* Failed assertion *
Path '/shared_data/ecs/test/system_reconciliation/C11a/prod/20240123_110000.20240123_154800/system_log_dir.manual/process_forecasts' doesn't exist!
################################################################################
```

Am I missing something here? 

To make sure I am understanding correctly - 

- I have to run the notebook [https://github.com/sorrentum/sorrentum/blob/master/oms/notebooks/Master_bid_ask_execution_analysis.ipynb](https://github.com/sorrentum/sorrentum/blob/master/oms/notebooks/Master_bid_ask_execution_analysis.ipynb). Check for the warning. (Now I am getting errors mentioned above)
- Then I have to check the `ccxt_logger.py` for `pd.to_datetime` with `unit` cases. Make the appropriate changes on the file, as mentioned on the task above, to eliminate the warnings in the notebook?
- Or should I create a smaller unit test(which internally uses ccxt_logger.py file) reproducing the problem instead of running the notebook?

Could you please clarify these? @samarth9008 @sonaalKant

**Comment by gpsaggese** [comment]
@samarth9008 @sonaalKant I don't think this notebook can run outside our infra.
As per the previous comment, it's better to create a smaller unit test reproducing the problem instead of running the notebook.

Let's add a rule to our guidelines to pick bugs to outsource to ensure no dependency from our KT infra.

**Comment by samarth9008** [comment]
@11swathi no need to work on it as it requires access to our infra which you do not have for now.

**Comment by samarth9008** [comment]
Closing as not for this repo
