### ISSUE TITLE
Improve hpandas.compare_dfs()

### ISSUE THREAD

**Issue by samarth9008** [sorrentum/sorrentum#682]
Orginally from - https://github.com/cryptokaizen/cmamp/issues/5941

There are a couple of issues with `hpandas.compare_dfs()`

1) The function issues an assertion only when computing pct difference 
2) Assertion works only if we remove infinities
3) I feel like we are reinventing the wheel when trying to compare dfs, i.e. most of the functionality implemented already exists in [`numpy.isclose`](https://numpy.org/doc/stable/reference/generated/numpy.isclose.html#numpy.isclose), not to mention that Numpy takes into account more edge cases

Some comparison invariants (copy-paste from https://numpy.org/doc/stable/reference/generated/numpy.isclose.html#numpy.isclose)

**Finite values:**

isclose uses the following equation to test whether two floating point values are equivalent.

`absolute(a - b) <= (atol + rtol * abs(b))`

**NaNs:**
NaNs are treated as equal if they are in the same place and if equal_nan=True.

**Infs:**

Infs are treated as equal if they are in the same place and of the same sign in both arrays.

So instead of

https://github.com/sorrentum/sorrentum/blob/476889c607fe17d72e574f56123366d1f2dc7df9/helpers/hpandas.py#L1990-L2000

and 

https://github.com/sorrentum/sorrentum/blob/476889c607fe17d72e574f56123366d1f2dc7df9/helpers/hpandas.py#L2015-L2024

we can use `numpy.allclose()` to check the equality before computing the diffs. E.g., seems like [`pd.testing.assert_frame_equal`](https://pandas.pydata.org/docs/reference/api/pandas.testing.assert_frame_equal.html) is a wrapper around `np.isclose()` and on top of that it returns a nice assertion, e.g.,

```
DataFrame.iloc[:, 1] (column name="B") values are different (33.33333 %)
[index]: [0, 1, 2]
[left]:  [4, 5, 6]
[right]: [4, 5, 7]
At positional index 2, first diff: 6 != 7
```

The plan is:
1) Check if `assert_frame_equal` complies with the comparison invariants
2) We should add the `only_warning = True` switch to issue a warning on demand only
3) Try to use `assert_frame_equal()` inside the `compare_dfs()` and see if the regressions still work
4) Add more unit tests to ensure the nice coverage (ideally 100%)

Side notes:
- The problem with the function is that it does 2 things at the same time: checks the equality and computes the difference. We could split the logic into 2 separate functions or check if we use the differences at all and remove the diff part -- it's a TODO

As a by-product I would convert the notes into a doc since comparing dfs is a common operation

FYI @gpsaggese @sonaalKant

**Comment by tkpratardan** [comment]
@samarth9008 I'm unable to access the links for the issues provided. I suspect it's because I don't have access to the repositories on github.com/cryptokaizen. Could you please assist me with this?"

**Comment by samarth9008** [comment]
The links required for you are updated

**Comment by tkpratardan** [comment]
@samarth9008 
I have been getting hands-on with the exercise. However, I need to clarify a few things, before I finish up the task:

1. 

> 1. The function issues an assertion only when computing pct difference

Are you suggesting that we implement assert_threshold for diff_mode = 'diff' ?

2. 
> 2. We should add the `only_warning = True` switch to issue a warning on demand only

will this switch issue warning on demand for "compare_nan" assertion or all the assertions that are implemented.

3.
> 2\. Assertion works only if we remove infinities
I am not sure I followed this completely. The implementation of remove_inf check is after the comparison invariants so I am not sure if I understand the code correctly. FYI
https://github.com/sorrentum/sorrentum/blob/e2a45a671b039fc7adf3d40efd879bb179f52a08/helpers/hpandas.py#L2015-L2027

To me, I am seeing this as a check that should be implemented before the assertions. 

Could you please clarify these things?

**Comment by samarth9008** [comment]
@sonaalKant Can you chime in if you know the answers? I will have to take a detailed look at the function first.

FYI @gpsaggese

**Comment by sonaalKant** [comment]
We would like to replace https://github.com/sorrentum/sorrentum/blob/476889c607fe17d72e574f56123366d1f2dc7df9/helpers/hpandas.py#L1990-L2000 and https://github.com/sorrentum/sorrentum/blob/476889c607fe17d72e574f56123366d1f2dc7df9/helpers/hpandas.py#L2015-L2024 with [pd.testing.assert_frame_equal](https://pandas.pydata.org/docs/reference/api/pandas.testing.assert_frame_equal.html). And see if the logic and corner cases still holds. 

Idea behind this is that we are implementing the same thing which is already done by the library in better way. 

> The plan is:
> 1. Check if assert_frame_equal complies with the comparison invariants

check if assert_frame_equal can handle invariants like finite values, infinite_values and nans.

> 2. We should add the only_warning = True switch to issue a warning on demand only

Instead of throwing assertions we would like to add an argument which will only throw warnings.

> 3. Try to use assert_frame_equal() inside the compare_dfs() and see if the regressions still work

> 4. Add more unit tests to ensure the nice coverage (ideally 100%)

Add more unit test for 100% coverage and corner cases.

**Comment by samarth9008** [comment]
Closing as merged.
