### ISSUE TITLE
On-board Rastislav

### ISSUE THREAD

**Issue by jsmerix** [sorrentum/sorrentum#691]
Please follow this checklist to on-board successfully, after all steps on your side are finished, you will be assigned your first issue.

- [x] Acknowledge the pledge to put effort and time in the project [here](https://github.com/sorrentum/sorrentum/blob/master/README.md#commitment-to-contribute)
- [x] Fork, star, watch the Sorrentum repo so that GitHub promotes our repo
- [x] Read and execute [set up development environment](https://github.com/sorrentum/sorrentum/blob/master/docs/docs/onboarding/sorrentum.set_up_development_environment.how_to_guide.md)
- [x] Read and start internalizing [Sorrentum Python coding style guide](https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.coding_style.how_to_guide.md)
- [x] Read about your [first code review](https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.submit_code_for_review.how_to_guide.md)
- [x] Peruse the map of [all the documentation](https://github.com/sorrentum/sorrentum/blob/master/docs/onboarding/all.development_documents.reference.md)
- [x] Learn about our [org process](https://github.com/sorrentum/sorrentum/blob/master/docs/work_organization/all.team_collaboration.how_to_guide.md)
- [x] Get assigned an issue

**Comment by rastislavpapco** [comment]
Prepared the dev environment following the installation guide. Read the mentioned documentation.

**Comment by gpsaggese** [comment]
@rastislavpapco can you pls mark the check list for what you have done?
