### ISSUE TITLE
Unit test `get_session()` from helpers/haws.py

### ISSUE THREAD

**Issue by samarth9008** [sorrentum/sorrentum#692]
We want to unit test `get_session()` from helpers/haws.py

The unit test file will `helpers/test/test_haws.py`

Make use [moto library](https://docs.getmoto.org/en/latest/) to mock aws services for the unit tests. 

Write a test and run it locally inside docker container and make sure it passes. Create a PR once done

FYI @gpsaggese @sonaalKant

**Comment by Er1-x** [comment]
@samarth9008 @sonaalKant I have posted a PR #714 , can you pls help me review and merge ?
