### ISSUE TITLE
Unit test `get_service_client` from helpers/haws.py

### ISSUE THREAD

**Issue by samarth9008** [sorrentum/sorrentum#693]
We want to unit test `get_service_client` from helpers/haws.py

The unit test file will helpers/test/test_haws.py

Make use [moto library](https://docs.getmoto.org/en/latest/) to mock aws services for the unit tests.

Write a test and run it locally inside docker container and make sure it passes. Create a PR once done

FYI @gpsaggese @sonaalKant

**Comment by tkpratardan** [comment]
@samarth9008 
Quick question. Should this be written in the version of `test_haws.py` (#700) that I created or in a new branch from master?

**Comment by samarth9008** [comment]
Same way but in a different PR and branch

In the end all will get merge to the same file.
