### ISSUE TITLE
Explore binance-futures-connector library

### ISSUE THREAD

**Issue by jsmerix** [sorrentum/sorrentum#701]
The goal of the issue is to prepare a jupyter notebook with a brief overview of websocket usage in
`binance-futures-connector` library.

References:
https://github.com/binance/binance-futures-connector-python
https://binance-docs.github.io/apidocs/futures/en/

There are specific example usages in: 
https://github.com/binance/binance-futures-connector-python/tree/main/examples/websocket/um_futures

Mainly:
- `agg_trade.py`
- `kline.py`
- `partial_book_depth.py`
- `symbol_kline.py`

We would like to:
- download 5 minutes worth of data using each of these examples (use a set of symbols: `BTC_USDT`, `ETH_USDT` and `XRP_USDT`)
- store the data as CSV (No need to apply any preprocessing)
- Load the datasets back and compute some basic statistics (number of data points per symbol, check for NaN values etc.)

To install a new package within your jupyter notebook run the following cell:
`! sudo /venv/bin/pip install binance-futures-connector`

**Comment by gpsaggese** [comment]
Good finding @jsmerix (the lib looks good, decent code, and lots of stars).

**Comment by rastislavpapco** [comment]
Pushed the work done so far on remote, but it's still in progress.

**Comment by gpsaggese** [comment]
@rastislavpapco you can open a draft PR and attach it here. This is a good way to get early feedback so you can course correct.
A good goal is 1 PR per working day at the beginning.

**Comment by rastislavpapco** [comment]
Created pull request.

**Comment by gpsaggese** [comment]
You should put the pointer to the PR (the goal is to make the job of the team easier. You don't want people to go look for the PR)
