### ISSUE TITLE
Review and improve Spring2024 class project README

### ISSUE THREAD

**Issue by gpsaggese** [sorrentum/sorrentum#702]
We want to make sure that the instructions make sense
https://github.com/sorrentum/sorrentum/blob/master/sorrentum_sandbox/projects/spring2024/README.md
Feel free to do a PR for changes and improvements.

We want to keep the flow of projects for DATA605, contributors to Sorrentum as close as possible.

**Comment by samarth9008** [comment]
Closing as done.
