### ISSUE TITLE
Improve Example1

### ISSUE THREAD

**Issue by gpsaggese** [sorrentum/sorrentum#703]
This is difficulty of this example is 1, but it's too easy we want to test it and make it more complex
https://github.com/sorrentum/sorrentum/tree/master/sorrentum_sandbox/projects/spring2024/SorrTask645_Redis_cache_to_fetch_user_profiles

Feel free to:
- review the readme
- add more stuff
- improve the readme

Let's have a quick chat before operating

Related is https://github.com/sorrentum/sorrentum/issues/702

**Comment by samarth9008** [comment]
Done closing
