### ISSUE TITLE
Script to simplify referring to docs in reviews

### ISSUE THREAD

**Issue by gpsaggese** [sorrentum/sorrentum#704]
A common problem is when we need to refer to a specific rule in a review, like here
<img width="835" alt="image" src="https://github.com/sorrentum/sorrentum/assets/33238329/97976c91-8a57-4838-abab-4fa177060b65">

It takes a bunch of time to search and refer to the link, and we don't want to re-explain the concept. We would like just to say "read here"

One idea is to have a simple script that searches the rules and reports the link in the link format

```
> jackmd "Naming and placement conventions"
docs/coding/all.write_unit_tests.how_to_guide.md:16:    + [Naming and placement conventions](#naming-and-placement-conventions)
docs/coding/all.write_unit_tests.how_to_guide.md:149:### Naming and placement conventions
```

https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.write_unit_tests.how_to_guide.md?plain=1#L16

We need to handle the fact that there are spurious matches due to the TOC.

So one would do `jackdoc "Naming and placement conventions"` and you get 
https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.write_unit_tests.how_to_guide.md?plain=1#L16

@samarth9008 @sonaalKant WDYT?
This can be outsourced of course

**Comment by sonaalKant** [comment]
Yes, this is absolutely relevant and can save a lot of review time.

**Comment by gpsaggese** [comment]
Wonderful. Let's add more specs here and put this in the list https://docs.google.com/document/d/1uuezdmcsV9TG2YwXGvEd0PBgWScCpR-QPOcySI5LPIA/edit#heading=h.faon2vtii2hh for outsourcing.

Giving priority to issues that improve productivity is always a win since compound interest exists.

**Comment by nehalR777** [comment]
Hey @samarth9008 , thank you for assigning me this issue . Could you help me with a quick outline on what is expected here?

**Comment by samarth9008** [comment]
`jackmd` tool is used to content from the md files. Any input provided to it we give us the filename, line number content from that line inside the file

As you can see running this 

```
> jackmd "Naming and placement conventions"
docs/coding/all.write_unit_tests.how_to_guide.md:16:    + [Naming and placement conventions](#naming-and-placement-conventions)
docs/coding/all.write_unit_tests.how_to_guide.md:149:### Naming and placement conventions
```

We want to create a script named `jackdoc` to which we provide some input. It will search all the md files and will provide link to the md file where the given input was found.

Reading the whole conversation will make things more clear.

**Comment by gpsaggese** [comment]
You should model the code of `jackdoc` on dev_scripts/script_skeleton.py
Some info is here docs/coding/all.coding_style.how_to_guide.md:1084

1) Please read the specs carefully

2) Create a PR with the a quick prototype of the code (e.g., with functions with interface and docstring but no implementation). We want to make sure that the specs is clear to you and your solution is ok.
The prototype should take a few hours

**Comment by nehalR777** [comment]
@gpsaggese @samarth9008  , A PR for this has been created[ here ](https://github.com/sorrentum/sorrentum/pull/723)

**Comment by samarth9008** [comment]
Closing as this is the follow-up issue

https://github.com/sorrentum/sorrentum/issues/754
