### ISSUE TITLE
Failing Unit tests in warm-up issues

### ISSUE THREAD

**Issue by tkpratardan** [sorrentum/sorrentum#705]
@samarth9008 @sonaalKant 

Context:
In my case (#700), the unit tests passed because the underlying scripts need not be changed and I had the option of passing the `aws_profle = '__mock__'` as a parameter to the haws.method() being tested. This allowed the MOCK AWS credentials that were setup to be fetched. However, as pointed out in #696, these methods don't have the option to pass the aws_profile as a paramter and by default check `ck` profile which is not present in our docker containers.

Problem:
Essentially, as an obvious first step, the functions in haws.py try to establish a boto3 session using the `haws.get_session()` func which uses `get_aws_credentials()` from `hs3.py`. `get_aws_credentials()` has a provision, for testing purposes, that if `aws_profile == '__mock__',` it fetches the access keys from the `os.environ` variables. As pointed out before, since the option of influencing the `aws_profile` value outside the functions, as in #696 is not possible, the purpose of setting up mock credentials is defeated and the moto mock services are rendered useless. Hence failed tests.

Possible solution:
change the function definitions in haws.py to accomodate `aws_profile` as a parameter.  set `default = "ck"` to avoid regressions.
@nehalR777 and I found this to be working.

let us know if this would be an ideal solution.

cc: @gpsaggese @11swathi 

FYI:
https://github.com/sorrentum/sorrentum/blob/e841aaa34c71b200f5405e7257cc108a57086fd8/helpers/hs3.py#L676-L686

#696 
https://github.com/sorrentum/sorrentum/blob/e841aaa34c71b200f5405e7257cc108a57086fd8/helpers/haws.py#L101-L112

**Comment by samarth9008** [comment]
Instead of changing the interface of the function, if you are testing `get_task_definition_image_url` function, can we mock the call to the `get_service_client` with the mocking object. It can be done using mock python library. Refer to online docs for implementation details.


For testing `update_task_definition`, can we try to mock the call to `get_ecs_client` function. 
FYI @nehalR777 

Feel free to post any any questions you have.

**Comment by nehalR777** [comment]
@samarth9008 , thanks for this https://github.com/sorrentum/sorrentum/issues/705#issuecomment-1973356329 , it worked
cc: @tkpratardan

**Comment by tkpratardan** [comment]
@samarth9008 
Thank you for the clarification. It is a lot clear now.
