### ISSUE TITLE
On boarding Vedanshu

### ISSUE THREAD

**Issue by sonaalKant** [sorrentum/sorrentum#715]
Please follow this checklist. Post any errors you face in this issue.

  - [x] Acknowledge the pledge to put time in the project [here](https://github.com/sorrentum/sorrentum/blob/master/README.md#Important) 
  - [x] Read [How to organize your work](https://github.com/sorrentum/sorrentum/blob/master/docs/work_organization/sorrentum.organize_your_work.how_to_guide.md)
  - [x] Read [Quick start for developing](https://github.com/sorrentum/sorrentum/blob/master/docs/onboarding/sorrentum.set_up_development_environment.how_to_guide.md)
  - [x] Make sure the [Docker dev container](https://github.com/sorrentum/sorrentum/blob/master/docs/work_tools/all.docker.how_to_guide.md) works
  - [x] Make sure the [unit tests](https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.write_unit_tests.how_to_guide.md) run successfully
  - [x] Read [Sorrentum Python coding style guide](https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.coding_style.how_to_guide.md)
  - [x] Fork, star, watch the Sorrentum repo so that GitHub promotes our repo (we gotta work the system)
  - [ ] Get assigned a warm-up issue
  - [x] Learn about the [Morning Email](https://github.com/sorrentum/sorrentum/blob/master/docs/work_organization/all.team_collaboration.how_to_guide.md#morning-email)
  - [x] How to do a [review](https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.submit_code_for_review.how_to_guide.md)
  - [x] If you are graduating soon and you would like to get a full-time job in one of the companies in the Sorrentum ecosystem reach out to GP at [gp@sorrentum.org](mailto:gp@sorrentum.org)

FYI @samarth9008 @gpsaggese

**Comment by sonaalKant** [comment]
Did you setup the sorrentum on your system? And ran the unit test to verify ?

**Comment by Vedanshu7** [comment]
@sonaalKant Yes, it was a bit complex, but I was able to solve most of my errors by referring previous Onboarding issues.

**Comment by gpsaggese** [comment]
@Vedanshu7 can you mark everything that was done in the checklist?

The goal of the checklist is to make sure you know how we expect things to be done. You'll have to re-read all the documentation over time to internalize and make the procedures run smoothly.

**Comment by Vedanshu7** [comment]
@gpsaggese I have marked everything on the checklist that I have completed.

**Comment by Vedanshu7** [comment]
@sonaalKant I have completed the task on the checklist. Could you please assign me a warm-up issue?

**Comment by sonaalKant** [comment]
I have assigned you the warm-up issue https://github.com/sorrentum/sorrentum/issues/736.
