### ISSUE TITLE
On-board Tianlu Lu

### ISSUE THREAD

**Issue by samarth9008** [sorrentum/sorrentum#734]
Please follow this checklist. Post any errors you face in this issue.

  - [x] Acknowledge the pledge to put time in the project [here](https://github.com/sorrentum/sorrentum/blob/master/README.md#Important) 
  - [x] Read [How to organize your work](https://github.com/sorrentum/sorrentum/blob/master/docs/work_organization/sorrentum.organize_your_work.how_to_guide.md)
  - [x] Read [Quick start for developing](https://github.com/sorrentum/sorrentum/blob/master/docs/onboarding/sorrentum.set_up_development_environment.how_to_guide.md)
  - [x] Make sure the [Docker dev container](https://github.com/sorrentum/sorrentum/blob/master/docs/work_tools/all.docker.how_to_guide.md) works
  - [x] Make sure the [unit tests](https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.write_unit_tests.how_to_guide.md) run successfully
  - [x] Read [Sorrentum Python coding style guide](https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.coding_style.how_to_guide.md)
  - [x] Fork, star, watch the Sorrentum repo so that GitHub promotes our repo (we gotta work the system)
  - [ ] Get assigned a warm-up issue
  - [x] Learn about the [Morning Email](https://github.com/sorrentum/sorrentum/blob/master/docs/work_organization/all.team_collaboration.how_to_guide.md#morning-email)
  - [x] How to do a [review](https://github.com/sorrentum/sorrentum/blob/master/docs/coding/all.submit_code_for_review.how_to_guide.md)
  - [x] If you are graduating soon and you would like to get a full-time job in one of the companies in the Sorrentum ecosystem reach out to GP at [gp@sorrentum.org](mailto:gp@sorrentum.org)

FYI @sonaalKant @gpsaggese

**Comment by samarth9008** [comment]
@ttiaNlluu Please follow this checklist for your on-boarding.

**Comment by ttiaNlluu** [comment]
Got it. Thank you.

**Comment by ttiaNlluu** [comment]
@samarth9008 Hello Samarth, I went over the on-boarding checklist. Here’s some problems I met:
1. Docker doesn’t work on My current laptop. I was able to use the laptop in UMD. But this resource is no longer accessible for me since I graduated. I need to reach to another laptop that Docker works. Please let me know if you have some resources.
2. Do I need to go over all the tutorial links before on-boarding? If not, can you assist me with the next step?
Thanks,
Tianlu

**Comment by samarth9008** [comment]
Docker is very crucial as our entire workflow works on docker

> Do I need to go over all the tutorial links before on-boarding?

yes the content from all the links should be internalize

**Comment by ttiaNlluu** [comment]
Ok, I will get my new laptop ready soon and make sure Docker works, I will also go over the details in every links. Can you give me a rough deadline of finishing the links? Can you also give me a guide on what happens next? Is there a interview, offer letter or something else?

Thanks,
Tianlu

**Comment by samarth9008** [comment]
> Can you give me a rough deadline of finishing the links?

Around a week

> Can you also give me a guide on what happens next?

As you can see from the checklist, you will be assigned a warm-up issue so that we can have better idea about you.

> Is there a interview, offer letter or something else?

We will have an idea about your abilities through simple warm-up tasks. Consider this as your interview. If we think you have skills to work with us, we will extend you a full-time offer. Related to that and how it will work, GP can provide better clarity. For now, I would suggest to focus on the on-boarding checklist and awesome performance in your waorm-up issues. Things will get more clear as you move forward.

**Comment by ttiaNlluu** [comment]
Got it, I will let you know when I finish the checklist. Thanks for the explanation.

**Comment by gpsaggese** [comment]
@samarth9008 answers are spot on.

For Docker you can install a VM, there are instructions in the repo.
You pass our (high) bar => full-time offer as data scientist / researcher / coder / devops.

**Comment by ttiaNlluu** [comment]
I have got my new laptop ready and Docker works. I’m still working on the on-boarding list. I will let you know once I’m ready for the warm-up tasks. Let me know how it can be. Thanks!

**Comment by ttiaNlluu** [comment]
Sorry for it took too long. If it's still available, can I get my warm-up issue next? Thanks!

**Comment by samarth9008** [comment]
We will assign you in some time

**Comment by gpsaggese** [comment]
@ttiaNlluu disappearing for 2 weeks is not compatible with our project. No need to explain why and how. I'm just telling how we judge contributors and potential employees.

**Comment by ttiaNlluu** [comment]
Sorry about taking that long to review the on-boarding list.

**Comment by samarth9008** [comment]
Assigned  https://github.com/sorrentum/sorrentum/issues/766

**Comment by ttiaNlluu** [comment]
Received. I'm working on it now. Thanks.

**Comment by gpsaggese** [comment]
Closing this since all done.
