### ISSUE TITLE
Replace TOC markers in MD files

### ISSUE THREAD

**Issue by sonaalKant** [sorrentum/sorrentum#736]
- To add TOC in the md files we use new markers `<!-- toc -->` and `<!-- tocstop -->`
- Before that we were using `<!—ts—>` and `<!—te—>`
- We would like to create a global replacement sh script which will replace old markers if any present with the new ones.
- Use `dev_scripts/replace_text.py` to replace it in one step

FYI @samarth9008 @gpsaggese

**Comment by samarth9008** [comment]
Also run the linter on all the changed files to generate Table Of Content

**Comment by Vedanshu7** [comment]
Hey @sonaalKant, I just wanted to let you know that I've submitted PR #737 for this issue.

**Comment by samarth9008** [comment]
Closing as done.
