### ISSUE TITLE
Factor out common code in test_haws

### ISSUE THREAD

**Issue by gpsaggese** [sorrentum/sorrentum#741]
> @samarth9008 I've noticed there are codes that repeat themselves, do we need to refactor it like GP requested in #714 ?

You can try implementing them in a separate PR. That would be actual a nice thing to do. I would do create a class like `haws_test_case` with common code and inherit into all other classes.

_Originally posted by @samarth9008 in https://github.com/sorrentum/sorrentum/issues/720#issuecomment-1995893616_

**Comment by Vedanshu7** [comment]
I opened a pull request for this task, #742.

**Comment by samarth9008** [comment]
Closing as done
