### ISSUE TITLE
Add new parameter to transform_bid_ask_long_data_to_wide and add unit test

### ISSUE THREAD

**Issue by jsmerix** [sorrentum/sorrentum#743]
The context is that we applied a temporary hack:

https://github.com/sorrentum/sorrentum/blob/09273bef802788bebdeb7fdcd266979b9d752ae7/core/finance/bid_ask.py#L196

Now we would like to address this by introducing a new argument to the function: `value_col_prefix` it will have default/ It will be based on the current hack `["log", "half"]`

Once the argument is added, we would also like to enrich the unit tests (add a test case where the input data is more rich, e.g. from multiple symbols, also test the new column). Attaching a snippet of data you could work with in the unit test
[data-1711052725313.csv](https://github.com/sorrentum/sorrentum/files/14706795/data-1711052725313.csv)

**Comment by Vedanshu7** [comment]
#744  I opened a pull request for this task.

**Comment by samarth9008** [comment]
Closing as merged.
